// GENERATED by scripts/generate-adwaita-framework-snippets.mjs — do not edit.
//
// Every gallery block that carries a React snippet, in ONE tree, compiled by
// this showcase's own build and asserted against the real GTK widget tree. The
// markup below is the SAME TEXT the website ships in
// `website/src/data/adwaita-framework-snippets.ts` — that is the whole point of
// generating both from `scripts/adwaita-gallery-trees.mjs`: a snippet nobody ran
// is a claim, and this file is what turns it into a measurement.

import Adw from 'gi://Adw?version=1';
import Gio from 'gi://Gio?version=2.0';
import Gtk from 'gi://Gtk?version=4.0';

import { registerBuiltinWidgets, runHostProbeApp, type ProbeCheck } from '@gjsify/gtk-host';
import { createRoot, flushSync } from '@gjsify/gtk-host/react';

registerBuiltinWidgets();

const AdwPreferencesGroup = () => (
    <adw-preferences-group
        title="Account"
        description="Manage how this device signs in and syncs."
    >
        <adw-entry-row
            title="Display name"
            text="Grace Hopper"
        />
        <adw-switch-row
            title="Sync over Wi-Fi only"
            subtitle="Avoid using mobile data for backups"
            active
        />
    </adw-preferences-group>
);

const AdwActionRow = () => (
    <adw-preferences-group>
        <adw-action-row
            title="Wi-Fi"
            subtitle="Connected to Highgarden 5GHz"
            activatable
        >
            <gtk-image
                slot="prefix"
                iconName="network-wireless-symbolic"
            />
            <gtk-button
                slot="suffix"
                iconName="go-next-symbolic"
                cssClasses={['flat']}
                valign="center"
            />
        </adw-action-row>
    </adw-preferences-group>
);

const AdwSwitchRow = () => (
    <adw-preferences-group>
        <adw-switch-row
            title="Automatic updates"
            subtitle="Download and install updates without asking"
            active
        />
    </adw-preferences-group>
);

const AdwEntryRow = () => (
    <adw-preferences-group>
        <adw-entry-row
            title="Display name"
            text="Ada Lovelace"
        />
    </adw-preferences-group>
);

const AdwPasswordEntryRow = () => (
    <adw-preferences-group>
        <adw-password-entry-row
            title="Password"
            text="correct-horse-battery"
        />
    </adw-preferences-group>
);

const AdwExpanderRow = () => (
    <adw-preferences-group>
        <adw-expander-row
            title="Proxy settings"
            subtitle="Route traffic through a custom proxy"
            expanded
        >
            <adw-entry-row
                title="Host"
                text="proxy.example.com"
            />
            <adw-switch-row title="Use authentication" />
        </adw-expander-row>
    </adw-preferences-group>
);

const AdwButtonRow = () => (
    <adw-preferences-group>
        <adw-button-row
            title="Add account"
            startIconName="list-add-symbolic"
            cssClasses={['suggested-action']}
        />
    </adw-preferences-group>
);

const AdwButtonContent = () => (
    <gtk-button cssClasses={['suggested-action', 'pill']}>
        <adw-button-content
            label="Download"
            iconName="folder-download-symbolic"
        />
    </gtk-button>
);

const GtkButton = () => (
    <gtk-box
        orientation="horizontal"
        spacing={12}
        halign="center"
    >
        <gtk-button
            label="Pill"
            cssClasses={['pill']}
        />
        <gtk-button
            iconName="list-add-symbolic"
            cssClasses={['circular']}
        />
        <gtk-button
            label="Suggested"
            cssClasses={['suggested-action']}
        />
        <gtk-button
            label="Delete"
            cssClasses={['destructive-action']}
        />
        <gtk-button
            label="Flat"
            cssClasses={['flat']}
        />
    </gtk-box>
);

const AdwSplitButton = () => (
    <adw-split-button
        label="Save"
        menuModel={[
            { label: 'Save as…', action: 'app.save-as' },
            { label: 'Export', action: 'app.export' },
            { label: 'Print', action: 'app.print' },
        ]}
    />
);

const GtkMenuButton = () => (
    <gtk-menu-button
        iconName="open-menu-symbolic"
        cssClasses={['flat']}
        menuModel={[
            { label: 'Preferences', action: 'app.preferences' },
            { label: 'Keyboard Shortcuts', action: 'win.show-help-overlay' },
            { label: 'About', action: 'app.about' },
        ]}
    />
);

const GtkEntry = () => (
    <gtk-entry
        placeholderText="Search files…"
        widthRequest={280}
    />
);

const AdwClamp = () => (
    <adw-clamp
        maximumSize={400}
        tighteningThreshold={300}
    >
        <gtk-label
            label="This content is clamped: it stops growing past the maximum size and stays centred."
            wrap
            xalign={0}
            cssClasses={['card']}
        />
    </adw-clamp>
);

const AdwHeaderBar = () => (
    <adw-header-bar>
        <gtk-button
            slot="start"
            iconName="go-previous-symbolic"
            cssClasses={['flat']}
        />
        <adw-window-title
            slot="title"
            title="Text Editor"
            subtitle="notes.md"
        />
        <gtk-menu-button
            slot="end"
            iconName="open-menu-symbolic"
            cssClasses={['flat']}
        />
    </adw-header-bar>
);

const AdwToolbarView = () => (
    <adw-toolbar-view>
        <adw-header-bar slot="top">
            <adw-window-title
                slot="title"
                title="Documents"
                subtitle="12 items"
            />
        </adw-header-bar>
        <adw-status-page
            slot="content"
            iconName="folder-documents-symbolic"
            title="Your library"
            description="Content sits between the toolbars and scrolls independently of them."
        />
        <gtk-box
            slot="bottom"
            cssClasses={['toolbar']}
            spacing={6}
        >
            <gtk-button
                iconName="list-add-symbolic"
                cssClasses={['flat']}
            />
            <gtk-button
                iconName="list-remove-symbolic"
                cssClasses={['flat']}
            />
            <gtk-label
                label="Selection: none"
                hexpand
            />
            <gtk-button
                iconName="send-to-symbolic"
                cssClasses={['flat']}
            />
        </gtk-box>
    </adw-toolbar-view>
);

const AdwWrapBox = () => (
    <adw-wrap-box
        childSpacing={8}
        lineSpacing={8}
    >
        <gtk-button
            label="Design"
            cssClasses={['pill']}
        />
        <gtk-button
            label="Adwaita"
            cssClasses={['pill']}
        />
        <gtk-button
            label="GNOME"
            cssClasses={['pill']}
        />
        <gtk-button
            label="GTK"
            cssClasses={['pill']}
        />
        <gtk-button
            label="TypeScript"
            cssClasses={['pill']}
        />
        <gtk-button
            label="Storybook"
            cssClasses={['pill']}
        />
        <gtk-button
            label="Wrapping"
            cssClasses={['pill']}
        />
        <gtk-button
            label="Layout"
            cssClasses={['pill']}
        />
    </adw-wrap-box>
);

const AdwOverlaySplitView = () => (
    <adw-overlay-split-view showSidebar>
        <adw-toolbar-view slot="sidebar">
            <adw-header-bar slot="top">
                <adw-window-title
                    slot="title"
                    title="Library"
                />
            </adw-header-bar>
            <adw-status-page
                slot="content"
                iconName="folder-music-symbolic"
                title="Sections"
            />
        </adw-toolbar-view>
        <adw-toolbar-view slot="content">
            <adw-header-bar slot="top">
                <adw-window-title
                    slot="title"
                    title="Your Library"
                />
            </adw-header-bar>
            <adw-status-page
                slot="content"
                iconName="folder-music-symbolic"
                title="Your Library"
                description="Toggle the sidebar to browse sections."
            />
        </adw-toolbar-view>
    </adw-overlay-split-view>
);

const AdwNavigationSplitView = () => (
    <adw-navigation-split-view showContent>
        <adw-navigation-page
            slot="sidebar"
            tag="sidebar"
            title="Mailboxes"
        >
            <adw-toolbar-view>
                <adw-header-bar slot="top">
                    <adw-window-title
                        slot="title"
                        title="Mailboxes"
                    />
                </adw-header-bar>
                <adw-status-page
                    slot="content"
                    iconName="mail-unread-symbolic"
                    title="Mailboxes"
                />
            </adw-toolbar-view>
        </adw-navigation-page>
        <adw-navigation-page
            slot="content"
            tag="content"
            title="All Mail"
        >
            <adw-toolbar-view>
                <adw-header-bar slot="top">
                    <adw-window-title
                        slot="title"
                        title="All Mail"
                    />
                </adw-header-bar>
                <adw-status-page
                    slot="content"
                    iconName="mail-unread-symbolic"
                    title="All Mail"
                    description="Select a conversation from the list to read it here."
                />
            </adw-toolbar-view>
        </adw-navigation-page>
    </adw-navigation-split-view>
);

const AdwNavigationView = () => (
    <adw-navigation-view>
        <adw-navigation-page
            tag="root"
            title="Contacts"
        >
            <adw-toolbar-view>
                <adw-header-bar slot="top">
                    <adw-window-title
                        slot="title"
                        title="Contacts"
                    />
                </adw-header-bar>
                <adw-status-page
                    slot="content"
                    title="Contacts"
                    description="Push a page to see the transition."
                />
            </adw-toolbar-view>
        </adw-navigation-page>
        <adw-navigation-page
            tag="detail"
            title="Ada Lovelace"
        >
            <adw-toolbar-view>
                <adw-header-bar slot="top">
                    <adw-window-title
                        slot="title"
                        title="Ada Lovelace"
                    />
                </adw-header-bar>
                <adw-status-page
                    slot="content"
                    iconName="avatar-default-symbolic"
                    title="Ada Lovelace"
                    description="Mathematician and writer, the first computer programmer."
                />
            </adw-toolbar-view>
        </adw-navigation-page>
    </adw-navigation-view>
);

const AdwAvatar = () => (
    <adw-avatar
        text="Ada Lovelace"
        size={96}
        showInitials
        iconName="avatar-default-symbolic"
    />
);

const AdwBanner = () => (
    <adw-banner
        title="Metered connection: updates paused"
        buttonLabel="Resume"
        revealed
    />
);

const AdwShortcutLabel = () => (
    <adw-shortcut-label accelerator="<Control>C" />
);

const AdwSpinner = () => (
    <adw-spinner
        widthRequest={48}
        heightRequest={48}
    />
);

const AdwStatusPage = () => (
    <adw-status-page
        iconName="folder-symbolic"
        title="No Documents"
        description="Documents you create or open will appear here."
    >
        <gtk-button
            label="New Document"
            cssClasses={['pill', 'suggested-action']}
            halign="center"
        />
    </adw-status-page>
);

const AdwWindowTitle = () => (
    <adw-window-title
        title="Inbox"
        subtitle="3 unread messages"
    />
);

/** Every gallery snippet in one column, so one root carries them all. */
const Gallery = () => (
    <gtk-box orientation="vertical" spacing={24}>
        <AdwPreferencesGroup />
        <AdwActionRow />
        <AdwSwitchRow />
        <AdwEntryRow />
        <AdwPasswordEntryRow />
        <AdwExpanderRow />
        <AdwButtonRow />
        <AdwButtonContent />
        <GtkButton />
        <AdwSplitButton />
        <GtkMenuButton />
        <GtkEntry />
        <AdwClamp />
        <AdwHeaderBar />
        <AdwToolbarView />
        <AdwWrapBox />
        <AdwOverlaySplitView />
        <AdwNavigationSplitView />
        <AdwNavigationView />
        <AdwAvatar />
        <AdwBanner />
        <AdwShortcutLabel />
        <AdwSpinner />
        <AdwStatusPage />
        <AdwWindowTitle />
    </gtk-box>
);

/**
 * What each adapter hands back.
 *
 * `root` is the ONE box holding the 18 gallery roots; `owner` is what has to be
 * disposed and presented, and the two differ by adapter: Solid builds the box
 * itself, while Vue and React render INTO a container, so their owner is that
 * container and the box is its first child. Keeping both is what lets the
 * assertions and the teardown each look at the right widget.
 */
interface Ui {
    readonly root: Gtk.Widget;
    readonly owner: Gtk.Widget;
    readonly app: Adw.Application | null;
}

/**
 * The GUI path. The window belongs to the APPLICATION and is never a free
 * toplevel: `scripts/showcase-smoke.mjs` launches this showcase and greps for
 * GJS's fatal markers, and a toplevel with no application is a Gtk-WARNING at
 * exit 0 — the shape that gate exists to catch.
 */
function present(ui: Ui, dialect: string): void {
    const window = new Adw.ApplicationWindow({
        application: ui.app ?? undefined,
        title: `Adwaita gallery — ${dialect}`,
        defaultWidth: 640,
        defaultHeight: 760,
    });
    const scroller = new Gtk.ScrolledWindow({ propagateNaturalHeight: true });
    scroller.set_child(ui.owner);
    window.set_content(scroller);
    window.present();
}

interface Expect {
    readonly tag: string;
    readonly gtype: string;
    readonly slot?: string;
    readonly props?: Record<string, unknown>;
    readonly children?: readonly Expect[];
}

/** Every gallery tree this probe builds, from `scripts/adwaita-gallery-trees.mjs`. */
const EXPECTED: readonly { widget: string; root: Expect }[] = [
    { widget: 'Adw.PreferencesGroup', root:
        { tag: 'adw-preferences-group', gtype: 'AdwPreferencesGroup', props: {"title":"Account","description":"Manage how this device signs in and syncs."}, children: [
                { tag: 'adw-entry-row', gtype: 'AdwEntryRow', props: {"title":"Display name","text":"Grace Hopper"} },
                { tag: 'adw-switch-row', gtype: 'AdwSwitchRow', props: {"title":"Sync over Wi-Fi only","subtitle":"Avoid using mobile data for backups","active":true} }
            ] }
    },
    { widget: 'Adw.ActionRow', root:
        { tag: 'adw-preferences-group', gtype: 'AdwPreferencesGroup', children: [
                { tag: 'adw-action-row', gtype: 'AdwActionRow', props: {"title":"Wi-Fi","subtitle":"Connected to Highgarden 5GHz","activatable":true}, children: [
                        { tag: 'gtk-image', gtype: 'GtkImage', slot: 'prefix', props: {"iconName":"network-wireless-symbolic"} },
                        { tag: 'gtk-button', gtype: 'GtkButton', slot: 'suffix', props: {"iconName":"go-next-symbolic","cssClasses":["flat"],"valign":"center"} }
                    ] }
            ] }
    },
    { widget: 'Adw.SwitchRow', root:
        { tag: 'adw-preferences-group', gtype: 'AdwPreferencesGroup', children: [
                { tag: 'adw-switch-row', gtype: 'AdwSwitchRow', props: {"title":"Automatic updates","subtitle":"Download and install updates without asking","active":true} }
            ] }
    },
    { widget: 'Adw.EntryRow', root:
        { tag: 'adw-preferences-group', gtype: 'AdwPreferencesGroup', children: [
                { tag: 'adw-entry-row', gtype: 'AdwEntryRow', props: {"title":"Display name","text":"Ada Lovelace"} }
            ] }
    },
    { widget: 'Adw.PasswordEntryRow', root:
        { tag: 'adw-preferences-group', gtype: 'AdwPreferencesGroup', children: [
                { tag: 'adw-password-entry-row', gtype: 'AdwPasswordEntryRow', props: {"title":"Password","text":"correct-horse-battery"} }
            ] }
    },
    { widget: 'Adw.ExpanderRow', root:
        { tag: 'adw-preferences-group', gtype: 'AdwPreferencesGroup', children: [
                { tag: 'adw-expander-row', gtype: 'AdwExpanderRow', props: {"title":"Proxy settings","subtitle":"Route traffic through a custom proxy","expanded":true}, children: [
                        { tag: 'adw-entry-row', gtype: 'AdwEntryRow', props: {"title":"Host","text":"proxy.example.com"} },
                        { tag: 'adw-switch-row', gtype: 'AdwSwitchRow', props: {"title":"Use authentication"} }
                    ] }
            ] }
    },
    { widget: 'Adw.ButtonRow', root:
        { tag: 'adw-preferences-group', gtype: 'AdwPreferencesGroup', children: [
                { tag: 'adw-button-row', gtype: 'AdwButtonRow', props: {"title":"Add account","startIconName":"list-add-symbolic","cssClasses":["suggested-action"]} }
            ] }
    },
    { widget: 'Adw.ButtonContent', root:
        { tag: 'gtk-button', gtype: 'GtkButton', props: {"cssClasses":["suggested-action","pill"]}, children: [
                { tag: 'adw-button-content', gtype: 'AdwButtonContent', props: {"label":"Download","iconName":"folder-download-symbolic"} }
            ] }
    },
    { widget: 'Gtk.Button', root:
        { tag: 'gtk-box', gtype: 'GtkBox', props: {"orientation":"horizontal","spacing":12,"halign":"center"}, children: [
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"Pill","cssClasses":["pill"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"iconName":"list-add-symbolic","cssClasses":["circular"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"Suggested","cssClasses":["suggested-action"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"Delete","cssClasses":["destructive-action"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"Flat","cssClasses":["flat"]} }
            ] }
    },
    { widget: 'Adw.SplitButton', root:
        { tag: 'adw-split-button', gtype: 'AdwSplitButton', props: {"label":"Save","menuModel":[{"label":"Save as…","action":"app.save-as"},{"label":"Export","action":"app.export"},{"label":"Print","action":"app.print"}]} }
    },
    { widget: 'Gtk.MenuButton', root:
        { tag: 'gtk-menu-button', gtype: 'GtkMenuButton', props: {"iconName":"open-menu-symbolic","cssClasses":["flat"],"menuModel":[{"label":"Preferences","action":"app.preferences"},{"label":"Keyboard Shortcuts","action":"win.show-help-overlay"},{"label":"About","action":"app.about"}]} }
    },
    { widget: 'Gtk.Entry', root:
        { tag: 'gtk-entry', gtype: 'GtkEntry', props: {"placeholderText":"Search files…","widthRequest":280} }
    },
    { widget: 'Adw.Clamp', root:
        { tag: 'adw-clamp', gtype: 'AdwClamp', props: {"maximumSize":400,"tighteningThreshold":300}, children: [
                { tag: 'gtk-label', gtype: 'GtkLabel', props: {"label":"This content is clamped: it stops growing past the maximum size and stays centred.","wrap":true,"xalign":0,"cssClasses":["card"]} }
            ] }
    },
    { widget: 'Adw.HeaderBar', root:
        { tag: 'adw-header-bar', gtype: 'AdwHeaderBar', children: [
                { tag: 'gtk-button', gtype: 'GtkButton', slot: 'start', props: {"iconName":"go-previous-symbolic","cssClasses":["flat"]} },
                { tag: 'adw-window-title', gtype: 'AdwWindowTitle', slot: 'title', props: {"title":"Text Editor","subtitle":"notes.md"} },
                { tag: 'gtk-menu-button', gtype: 'GtkMenuButton', slot: 'end', props: {"iconName":"open-menu-symbolic","cssClasses":["flat"]} }
            ] }
    },
    { widget: 'Adw.ToolbarView', root:
        { tag: 'adw-toolbar-view', gtype: 'AdwToolbarView', children: [
                { tag: 'adw-header-bar', gtype: 'AdwHeaderBar', slot: 'top', children: [
                        { tag: 'adw-window-title', gtype: 'AdwWindowTitle', slot: 'title', props: {"title":"Documents","subtitle":"12 items"} }
                    ] },
                { tag: 'adw-status-page', gtype: 'AdwStatusPage', slot: 'content', props: {"iconName":"folder-documents-symbolic","title":"Your library","description":"Content sits between the toolbars and scrolls independently of them."} },
                { tag: 'gtk-box', gtype: 'GtkBox', slot: 'bottom', props: {"cssClasses":["toolbar"],"spacing":6}, children: [
                        { tag: 'gtk-button', gtype: 'GtkButton', props: {"iconName":"list-add-symbolic","cssClasses":["flat"]} },
                        { tag: 'gtk-button', gtype: 'GtkButton', props: {"iconName":"list-remove-symbolic","cssClasses":["flat"]} },
                        { tag: 'gtk-label', gtype: 'GtkLabel', props: {"label":"Selection: none","hexpand":true} },
                        { tag: 'gtk-button', gtype: 'GtkButton', props: {"iconName":"send-to-symbolic","cssClasses":["flat"]} }
                    ] }
            ] }
    },
    { widget: 'Adw.WrapBox', root:
        { tag: 'adw-wrap-box', gtype: 'AdwWrapBox', props: {"childSpacing":8,"lineSpacing":8}, children: [
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"Design","cssClasses":["pill"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"Adwaita","cssClasses":["pill"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"GNOME","cssClasses":["pill"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"GTK","cssClasses":["pill"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"TypeScript","cssClasses":["pill"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"Storybook","cssClasses":["pill"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"Wrapping","cssClasses":["pill"]} },
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"Layout","cssClasses":["pill"]} }
            ] }
    },
    { widget: 'Adw.OverlaySplitView', root:
        { tag: 'adw-overlay-split-view', gtype: 'AdwOverlaySplitView', props: {"showSidebar":true}, children: [
                { tag: 'adw-toolbar-view', gtype: 'AdwToolbarView', slot: 'sidebar', children: [
                        { tag: 'adw-header-bar', gtype: 'AdwHeaderBar', slot: 'top', children: [
                                { tag: 'adw-window-title', gtype: 'AdwWindowTitle', slot: 'title', props: {"title":"Library"} }
                            ] },
                        { tag: 'adw-status-page', gtype: 'AdwStatusPage', slot: 'content', props: {"iconName":"folder-music-symbolic","title":"Sections"} }
                    ] },
                { tag: 'adw-toolbar-view', gtype: 'AdwToolbarView', slot: 'content', children: [
                        { tag: 'adw-header-bar', gtype: 'AdwHeaderBar', slot: 'top', children: [
                                { tag: 'adw-window-title', gtype: 'AdwWindowTitle', slot: 'title', props: {"title":"Your Library"} }
                            ] },
                        { tag: 'adw-status-page', gtype: 'AdwStatusPage', slot: 'content', props: {"iconName":"folder-music-symbolic","title":"Your Library","description":"Toggle the sidebar to browse sections."} }
                    ] }
            ] }
    },
    { widget: 'Adw.NavigationSplitView', root:
        { tag: 'adw-navigation-split-view', gtype: 'AdwNavigationSplitView', props: {"showContent":true}, children: [
                { tag: 'adw-navigation-page', gtype: 'AdwNavigationPage', slot: 'sidebar', props: {"tag":"sidebar","title":"Mailboxes"}, children: [
                        { tag: 'adw-toolbar-view', gtype: 'AdwToolbarView', children: [
                                { tag: 'adw-header-bar', gtype: 'AdwHeaderBar', slot: 'top', children: [
                                        { tag: 'adw-window-title', gtype: 'AdwWindowTitle', slot: 'title', props: {"title":"Mailboxes"} }
                                    ] },
                                { tag: 'adw-status-page', gtype: 'AdwStatusPage', slot: 'content', props: {"iconName":"mail-unread-symbolic","title":"Mailboxes"} }
                            ] }
                    ] },
                { tag: 'adw-navigation-page', gtype: 'AdwNavigationPage', slot: 'content', props: {"tag":"content","title":"All Mail"}, children: [
                        { tag: 'adw-toolbar-view', gtype: 'AdwToolbarView', children: [
                                { tag: 'adw-header-bar', gtype: 'AdwHeaderBar', slot: 'top', children: [
                                        { tag: 'adw-window-title', gtype: 'AdwWindowTitle', slot: 'title', props: {"title":"All Mail"} }
                                    ] },
                                { tag: 'adw-status-page', gtype: 'AdwStatusPage', slot: 'content', props: {"iconName":"mail-unread-symbolic","title":"All Mail","description":"Select a conversation from the list to read it here."} }
                            ] }
                    ] }
            ] }
    },
    { widget: 'Adw.NavigationView', root:
        { tag: 'adw-navigation-view', gtype: 'AdwNavigationView', children: [
                { tag: 'adw-navigation-page', gtype: 'AdwNavigationPage', props: {"tag":"root","title":"Contacts"}, children: [
                        { tag: 'adw-toolbar-view', gtype: 'AdwToolbarView', children: [
                                { tag: 'adw-header-bar', gtype: 'AdwHeaderBar', slot: 'top', children: [
                                        { tag: 'adw-window-title', gtype: 'AdwWindowTitle', slot: 'title', props: {"title":"Contacts"} }
                                    ] },
                                { tag: 'adw-status-page', gtype: 'AdwStatusPage', slot: 'content', props: {"title":"Contacts","description":"Push a page to see the transition."} }
                            ] }
                    ] },
                { tag: 'adw-navigation-page', gtype: 'AdwNavigationPage', props: {"tag":"detail","title":"Ada Lovelace"}, children: [
                        { tag: 'adw-toolbar-view', gtype: 'AdwToolbarView', children: [
                                { tag: 'adw-header-bar', gtype: 'AdwHeaderBar', slot: 'top', children: [
                                        { tag: 'adw-window-title', gtype: 'AdwWindowTitle', slot: 'title', props: {"title":"Ada Lovelace"} }
                                    ] },
                                { tag: 'adw-status-page', gtype: 'AdwStatusPage', slot: 'content', props: {"iconName":"avatar-default-symbolic","title":"Ada Lovelace","description":"Mathematician and writer, the first computer programmer."} }
                            ] }
                    ] }
            ] }
    },
    { widget: 'Adw.Avatar', root:
        { tag: 'adw-avatar', gtype: 'AdwAvatar', props: {"text":"Ada Lovelace","size":96,"showInitials":true,"iconName":"avatar-default-symbolic"} }
    },
    { widget: 'Adw.Banner', root:
        { tag: 'adw-banner', gtype: 'AdwBanner', props: {"title":"Metered connection: updates paused","buttonLabel":"Resume","revealed":true} }
    },
    { widget: 'Adw.ShortcutLabel', root:
        { tag: 'adw-shortcut-label', gtype: 'AdwShortcutLabel', props: {"accelerator":"<Control>C"} }
    },
    { widget: 'Adw.Spinner', root:
        { tag: 'adw-spinner', gtype: 'AdwSpinner', props: {"widthRequest":48,"heightRequest":48} }
    },
    { widget: 'Adw.StatusPage', root:
        { tag: 'adw-status-page', gtype: 'AdwStatusPage', props: {"iconName":"folder-symbolic","title":"No Documents","description":"Documents you create or open will appear here."}, children: [
                { tag: 'gtk-button', gtype: 'GtkButton', props: {"label":"New Document","cssClasses":["pill","suggested-action"],"halign":"center"} }
            ] }
    },
    { widget: 'Adw.WindowTitle', root:
        { tag: 'adw-window-title', gtype: 'AdwWindowTitle', props: {"title":"Inbox","subtitle":"3 unread messages"} }
    },
];

/** `AdwHeaderBar` for an `Adw.HeaderBar` instance — the GType, not the JS class. */
const gtypeOf = (w: Gtk.Widget): string =>
    (w as unknown as { constructor: { $gtype?: { name: string } } }).constructor.$gtype?.name ?? '?';

/** Enum props are authored as GTK's own nicks and read back as ints. */
const NICKS: Record<string, Record<string, number>> = {
    orientation: { horizontal: Gtk.Orientation.HORIZONTAL, vertical: Gtk.Orientation.VERTICAL },
    halign: { fill: Gtk.Align.FILL, start: Gtk.Align.START, end: Gtk.Align.END, center: Gtk.Align.CENTER },
    valign: { fill: Gtk.Align.FILL, start: Gtk.Align.START, end: Gtk.Align.END, center: Gtk.Align.CENTER },
};

/**
 * A `GMenuModel` property against the portable model the tree declares (ADR 0042).
 *
 * The declared value is an ARRAY and what the widget holds is a `Gio.MenuModel`, so
 * `!==` would fail every time. Compared item by item on the two attributes GIO
 * actually stores — the label, and the action `set_detailed_action` parsed out — which
 * is what proves the ARRAY became a real menu rather than merely being accepted.
 */
function menuMatches(actual: unknown, expected: unknown): boolean {
    const model = actual as Gio.MenuModel | null;
    const declared = expected as Array<{ label?: string; action?: string }>;
    if (model === null || model === undefined) return false;
    if (model.get_n_items() !== declared.length) return false;
    for (let i = 0; i < declared.length; i += 1) {
        const label = model.get_item_attribute_value(i, 'label', null)?.get_string()[0];
        if (label !== declared[i].label) return false;
        // `app.save-as` is stored under `action`; a targeted one would also carry
        // `target`, and no gallery tree writes one.
        const action = model.get_item_attribute_value(i, 'action', null)?.get_string()[0];
        if (action !== declared[i].action) return false;
    }
    return true;
}

/** Does the REAL widget carry every property the tree declares? */
function propsMatch(widget: Gtk.Widget, props: Record<string, unknown> | undefined): boolean {
    for (const [name, expected] of Object.entries(props ?? {})) {
        if (name === 'cssClasses') {
            const have = widget.get_css_classes();
            if (!(expected as string[]).every((c) => have.includes(c))) return false;
            continue;
        }
        if (name === 'menuModel') {
            if (!menuMatches((widget as unknown as Record<string, unknown>)[name], expected)) return false;
            continue;
        }
        const actual = (widget as unknown as Record<string, unknown>)[name];
        const wanted = typeof expected === 'string' && NICKS[name] !== undefined ? NICKS[name][expected] : expected;
        if (actual !== wanted) return false;
    }
    return true;
}

/** Breadth-first, so the nearest match under a parent wins over a deeper one. */
function findUnused(root: Gtk.Widget, expect: Expect, used: Set<Gtk.Widget>): Gtk.Widget | null {
    const queue: Gtk.Widget[] = [root];
    while (queue.length > 0) {
        const widget = queue.shift() as Gtk.Widget;
        if (widget !== root && !used.has(widget) && gtypeOf(widget) === expect.gtype && propsMatch(widget, expect.props))
            return widget;
        for (let c = widget.get_first_child(); c !== null; c = c.get_next_sibling()) queue.push(c);
    }
    return null;
}

/**
 * The widget a slot HOLDS, when the parent has an exact getter for it.
 *
 * `undefined` means no getter exists and the caller has to search. Selecting
 * beats searching wherever it is possible, and not only for exactness: two
 * children of the same GType with no distinguishing props are indistinguishable to
 * a structural search, and the first one BFS reaches wins. MEASURED on
 * `Adw.OverlaySplitView`, whose sidebar and content are both a bare
 * `<adw-toolbar-view>`: the sidebar declaration matched the CONTENT widget, and
 * the failure surfaced four levels down as "its window title was not built" — a
 * true statement about the wrong widget, which is the most expensive kind.
 */
function slotChild(parent: Gtk.Widget, slot: string): Gtk.Widget | null | undefined {
    if (parent instanceof Adw.ToolbarView) return slot === 'content' ? parent.get_content() : undefined;
    if (parent instanceof Adw.HeaderBar) return slot === 'title' ? parent.get_title_widget() : undefined;
    if (parent instanceof Adw.OverlaySplitView || parent instanceof Adw.NavigationSplitView) {
        if (slot === 'sidebar') return parent.get_sidebar();
        if (slot === 'content') return parent.get_content();
    }
    return undefined;
}

/**
 * Whether a slot was honoured — EXACTLY where the widget has a getter for it.
 *
 * `null` means the slot has no readable counterpart (`add_prefix` and
 * `add_suffix` are write-only and libadwaita puts no marker class on either), and
 * the caller records that as unverified rather than as a pass. A slot asserted as
 * "the child is somewhere in the subtree" asserts nothing: that is true of every
 * slot the child could have gone into.
 */
function slotHonoured(parent: Gtk.Widget, slot: string, child: Gtk.Widget): boolean | null {
    if (parent instanceof Adw.ToolbarView) {
        // `add_top_bar`/`add_bottom_bar` are write-only and the height getters read
        // 0 until allocation, which a headless probe never does. The style class
        // libadwaita puts on the revealer it wraps each bar in is readable, and it
        // separates the two slots — measured on libadwaita 1.9 / gjs 1.88.1.
        for (let w: Gtk.Widget | null = child; w !== null && w !== parent; w = w.get_parent()) {
            const classes = w.get_css_classes();
            if (classes.includes('top-bar')) return slot === 'top';
            if (classes.includes('bottom-bar')) return slot === 'bottom';
        }
        return false;
    }
    if (parent instanceof Adw.HeaderBar) {
        // Same shape: `pack_start`/`pack_end` are write-only, and what is readable
        // is the Gtk.CenterBox libadwaita builds inside every header bar.
        let centerBox: Gtk.CenterBox | null = null;
        const queue: Gtk.Widget[] = [parent];
        while (queue.length > 0 && centerBox === null) {
            const w = queue.shift() as Gtk.Widget;
            if (w instanceof Gtk.CenterBox) centerBox = w;
            else for (let c = w.get_first_child(); c !== null; c = c.get_next_sibling()) queue.push(c);
        }
        if (centerBox === null) return false;
        const side = slot === 'start' ? centerBox.get_start_widget() : centerBox.get_end_widget();
        for (let w: Gtk.Widget | null = child; w !== null; w = w.get_parent()) if (w === side) return true;
        return false;
    }
    return null;
}

/** A stable signature of the REAL tree, so the three dialects can be compared. */
function signature(widget: Gtk.Widget, depth = 0): string {
    let out = `${'  '.repeat(depth)}${gtypeOf(widget)}\n`;
    for (let c = widget.get_first_child(); c !== null; c = c.get_next_sibling()) out += signature(c, depth + 1);
    return out;
}

const hash = (text: string): string => {
    let h = 5381;
    for (let i = 0; i < text.length; i += 1) h = ((h * 33) ^ text.charCodeAt(i)) >>> 0;
    return h.toString(16);
};

/** Walk one declared tree against the widget the adapter actually built. */
function assertTree(expect: Expect, widget: Gtk.Widget, label: string, check: ProbeCheck, used: Set<Gtk.Widget>): void {
    used.add(widget);
    check(`${label}: is ${expect.gtype}`, gtypeOf(widget) === expect.gtype);
    for (const [name, value] of Object.entries(expect.props ?? {})) {
        check(`${label}: ${name} reached GTK`, propsMatch(widget, { [name]: value }));
    }
    for (const child of expect.children ?? []) {
        // SELECT before searching: a getter names the exact widget the slot holds,
        // which both proves the placement and removes the ambiguity a structural
        // search has between two same-typed children.
        const held = child.slot === undefined ? undefined : slotChild(widget, child.slot);
        if (held !== undefined) {
            check(`${label} > ${child.tag}: slot="${child.slot}" holds it`, held !== null);
            if (held === null) continue;
            assertTree(child, held, `${label} > ${child.tag}`, check, used);
            continue;
        }
        const found = findUnused(widget, child, used);
        check(`${label} > ${child.tag}: built`, found !== null);
        if (found === null) continue;
        if (child.slot !== undefined) {
            const honoured = slotHonoured(widget, child.slot, found);
            if (honoured === null) unverifiedSlots.push(`${label} > ${child.tag} slot="${child.slot}"`);
            else check(`${label} > ${child.tag}: slot="${child.slot}" honoured`, honoured);
        }
        assertTree(child, found, `${label} > ${child.tag}`, check, used);
    }
}

const unverifiedSlots: string[] = [];

/** Assert every declared tree against the roots the adapter mounted, in order. */
function assertAll(container: Gtk.Widget, check: ProbeCheck): Record<string, unknown> {
    const roots: Gtk.Widget[] = [];
    for (let c = container.get_first_child(); c !== null; c = c.get_next_sibling()) roots.push(c);
    check(`the adapter built ${EXPECTED.length} roots (saw ${roots.length})`, roots.length === EXPECTED.length);

    const signatures: Record<string, string> = {};
    for (let i = 0; i < EXPECTED.length && i < roots.length; i += 1) {
        const expect = EXPECTED[i];
        assertTree(expect.root, roots[i], expect.widget, check, new Set<Gtk.Widget>());
        signatures[expect.widget] = hash(signature(roots[i]));
    }
    return { widgets: EXPECTED.length, unverifiedSlots: unverifiedSlots.length, signatures };
}

await runHostProbeApp<Ui>({
    applicationId: 'eu.jumplink.AdwaitaGalleryReact',
    build: (app) => {
        // React renders INTO a container: a toplevel is not a child of anything, so
        // the container is a plain box and the window is the application's.
        const container = new Gtk.Box({ orientation: Gtk.Orientation.VERTICAL });
        const root = createRoot(container);
        // SYNCHRONOUS on purpose: `resolveUpdatePriority` returns the default lane, so
        // an ordinary render is handed to the scheduler and lands on a GLib timer —
        // the assertions would read an empty box. `flushSync` is the documented way
        // to make the commit happen before the call returns.
        flushSync(() => root.render(<Gallery />));
        return { root: container.get_first_child() as Gtk.Widget, owner: container, app };
    },
    assert: (ui, check) => assertAll(ui.root, check),
    teardown: (ui) => ui.owner.run_dispose(),
    present: (ui) => present(ui, 'React'),
});
