// The GtkBuilder XML exit of ADR 0053 clause 1, measured against the goldens in
// `corpus/rules/*.ui` — the bytes `blueprint-compiler` 0.20.4 produces.
//
// WHY THIS IS A WRITER WITH A `needsNewline` FLAG AND NOT A TREE SERIALISER
//
// Almost every whitespace rule in the goldens falls out of ONE piece of state the
// reference emitter keeps, and out of nothing else: whether the last thing written was an
// element (so a closing tag gets its own line) or text (so it does not). Reproduced here
// rather than re-derived, because the re-derivation is a list of special cases and the
// state machine is four methods:
//
//   `<object class="GtkBox"></object>`      01-object-minimal.ui — nothing was written
//                                           between the tags, so no newline is owed and
//                                           the empty object is never self-closed
//   `<property …>plain text</property>`     02-property-scalars.ui — text owes no newline
//   `<property …>\n  <object …/>\n</property>`  06-property-object-valued.ui — an element does
//   `…a newline \n</property>`              16-string-escapes.ui — a `\n` INSIDE the text is
//                                           just text, so `</property>` lands in column 0
//
// A serialiser that decided indentation from depth alone reproduces the third line and
// fails the other three. Depth is still what sets the amount of indent — two spaces per
// open tag, and the closing tag indents at the depth it is closing INTO, which is why the
// stack is popped before the newline is written.
//
// WHAT THIS FILE MAY NOT DECIDE
//
// ADR 0053 clause 6: "a tolerated divergence is a ledger entry, never an `if` inside the
// parser." The same applies here. Where the goldens carry a value that syntax alone cannot
// produce — an enum member resolved against the typelib — this file calls out to
// `options.resolveEnum` and, given no answer, emits the source spelling. It does not carry
// a table of enum members, and adding one for a single stubborn file would be exactly the
// `if` clause 6 refuses. `corpus/divergences.mjs` is where such a case is recorded.

/**
 * @import { BlueprintFile, BlueprintImport, Child, Extension, MenuItem, MenuNode, ObjectBody,
 *   ObjectNode, Property, Signal, TemplateNode, TypeRef, Value } from './ast.d.mts'
 */

/**
 * How the emitter is told what a bare identifier means, and the ONLY seam through which
 * introspection reaches this file.
 *
 * `03-property-enum.ui` is the file that forces it: `orientation: vertical` leaves the
 * reference compiler as `1` and `halign: center` as `3`, because it resolves the member
 * against the typelib. Nothing in the syntax carries those numbers.
 *
 * `typeName` is the GType name of the object the property sits ON (`GtkBox`), not the name
 * of the enum (`GtkOrientation`) — the emitter cannot know the latter without the ParamSpec
 * that only GIR has. A resolver therefore has to search the owner's enum-valued properties
 * for `member`. That the property NAME is not in this signature is a real limit of it and
 * is recorded rather than worked around: two properties of one widget whose enum types
 * share a member name of different value would be indistinguishable here.
 *
 * @typedef {Object} EmitOptions
 * @property {(typeName: string, member: string) => number | null} [resolveEnum]
 */

/**
 * Shared state for one emit: the caller's resolver, plus the two things a value cannot be
 * emitted without and a single node does not carry.
 *
 * @typedef {Object} EmitContext
 * @property {((typeName: string, member: string) => number | null) | undefined} resolveEnum
 * @property {Map<string, string>} idTypes  object id -> GType name, for `setters { }`
 * @property {string | undefined} templateClass  what the id `template` refers to
 */

/** Byte-identical in all 25 rule goldens and all 11 real ones, including the `@generated` marker. */
const GENERATED_NOTICE =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<!--\n' +
    'DO NOT EDIT!\n' +
    'This file was @generated by blueprint-compiler. Instead, edit the\n' +
    'corresponding .blp file and regenerate this file with blueprint-compiler.\n' +
    '-->';

/**
 * Emit the GtkBuilder XML for a parsed Blueprint file.
 *
 * @param {BlueprintFile} file
 * @param {EmitOptions} [options]
 * @returns {string}  the GtkBuilder XML, including the trailing newline
 */
export function emitGtkBuilderXml(file, options) {
    /** @type {EmitContext} */
    const context = {
        resolveEnum: options?.resolveEnum,
        idTypes: indexObjectIds(file),
        templateClass: findTemplateClass(file),
    };

    const xml = new XmlWriter();
    xml.startTag('interface', {});
    // One `<requires>` and only ever `gtk`, in every golden — 18-multiple-imports.ui pins
    // that: `using Adw 1;` is used by the file and reaches the XML nowhere.
    xml.selfClosing('requires', { lib: 'gtk', version: gtkVersion(file.imports) });

    for (const root of file.roots) {
        if (root.kind === 'template') emitTemplate(xml, root, context);
        else if (root.kind === 'menu') emitMenu(xml, root, context);
        else emitObject(xml, root, context);
    }

    xml.endTag();
    return `${xml.result}\n`;
}

// ------------------------------------------------------------------ the writer

/** The reference emitter's state machine; see the file header for what each line of it buys. */
class XmlWriter {
    constructor() {
        this.result = GENERATED_NOTICE;
        /** @type {string[]} */
        this.stack = [];
        /** Whether the last thing written was an element rather than text. */
        this.needsNewline = false;
    }

    /** @param {string} tag @param {Record<string, unknown>} attrs */
    startTag(tag, attrs) {
        this.break();
        this.result += `<${tag}${formatAttributes(attrs)}>`;
        this.stack.push(tag);
        this.needsNewline = false;
    }

    /** @param {string} tag @param {Record<string, unknown>} attrs */
    selfClosing(tag, attrs) {
        this.break();
        this.result += `<${tag}${formatAttributes(attrs)}/>`;
        this.needsNewline = true;
    }

    endTag() {
        const tag = this.stack.pop();
        if (this.needsNewline) this.break();
        this.result += `</${tag}>`;
        this.needsNewline = true;
    }

    /** @param {string} value */
    text(value) {
        this.result += escapeXml(value);
        this.needsNewline = false;
    }

    break() {
        this.result += `\n${'  '.repeat(this.stack.length)}`;
    }
}

/**
 * `&`, `<` and `>` — and NOT `"`, in attribute values as much as in text.
 *
 * 16-string-escapes.ui pins the first half (`a "quoted" word` survives verbatim while `&`
 * and `<` do not); `>` is not in any golden and was measured on 0.20.4, which reaches for
 * Python's `xml.sax.saxutils.escape` and applies it to attributes too. The consequence is
 * upstream's and is reproduced deliberately: a `"` inside an attribute value produces XML
 * that does not parse. Diverging here would cost a byte-equal diff on the file that finally
 * contains one.
 *
 * @param {unknown} value
 */
function escapeXml(value) {
    return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

/**
 * Attribute order is insertion order, and an attribute whose value is absent is omitted
 * rather than emitted empty — 13-binding.ui's `no-sync-create` sibling has no `bind-flags`
 * at all, and 04-children-implicit.ui's `<child>` has no `type`.
 *
 * @param {Record<string, unknown>} attrs
 */
function formatAttributes(attrs) {
    let out = '';
    for (const [name, value] of Object.entries(attrs)) {
        if (value === null || value === undefined) continue;
        out += ` ${name}="${escapeXml(value)}"`;
    }
    return out;
}

// ------------------------------------------------------------------ objects and bodies

/** @param {XmlWriter} xml @param {ObjectNode} object @param {EmitContext} context */
function emitObject(xml, object, context) {
    const className = gtypeName(object.type);
    xml.startTag('object', { class: className, id: object.id });
    emitBody(xml, object.body, className, context);
    xml.endTag();
}

/** @param {XmlWriter} xml @param {TemplateNode} template @param {EmitContext} context */
function emitTemplate(xml, template, context) {
    // 08-template.ui: `class` is the `$Name` without its sigil, `parent` the GType of the
    // type after the colon. The owner type for value resolution is the PARENT — the
    // template class is the one being defined and has no ParamSpecs of its own yet.
    xml.startTag('template', { class: template.className, parent: gtypeName(template.parent) });
    emitBody(xml, template.body, gtypeName(template.parent), context);
    xml.endTag();
}

/**
 * The one ordering rule in the file: an object's members are emitted in SOURCE order, with
 * properties, children, signals and extensions interleaved.
 *
 * The AST hands them over in four separate arrays, so the order has to be recovered from
 * the `line` every node carries. It is not cosmetic: `showcases/gtk/adw-blueprint-layout/
 * src/toolbar-view.blp` writes `[top]`, then `content:`, then `[bottom]`, and its golden
 * emits `<child type="top">`, `<property name="content">`, `<child type="bottom">` in
 * exactly that sequence. Grouping by kind would move the property past the second child.
 *
 * Two members on ONE line are not in any golden. The sort is stable, so they keep the
 * group order below.
 *
 * @param {XmlWriter} xml @param {ObjectBody} body @param {string} ownerType @param {EmitContext} context
 */
function emitBody(xml, body, ownerType, context) {
    const members = inSourceOrder([
        ['property', body.properties],
        ['child', body.children],
        ['signal', body.signals],
        ['extension', body.extensions],
    ]);

    for (const [kind, member] of members) {
        if (kind === 'property') emitProperty(xml, /** @type {Property} */ (member), ownerType, context);
        else if (kind === 'child') emitChild(xml, /** @type {Child} */ (member), context);
        else if (kind === 'signal') emitSignal(xml, /** @type {Signal} */ (member), context);
        else emitExtension(xml, /** @type {Extension} */ (member), ownerType, context);
    }
}

/**
 * @param {readonly [string, readonly { readonly line: number }[]][]} groups
 * @returns {[string, { readonly line: number }][]}
 */
function inSourceOrder(groups) {
    /** @type {[string, { readonly line: number }][]} */
    const merged = [];
    for (const [kind, nodes] of groups) {
        for (const node of nodes) merged.push([kind, node]);
    }
    return merged.sort((a, b) => a[1].line - b[1].line);
}

/** @param {XmlWriter} xml @param {Child} child @param {EmitContext} context */
function emitChild(xml, child, context) {
    // 05-child-slot-named.ui: the `[start]` bracket is an attribute on the CHILD WRAPPER,
    // and 25-bracket-breakpoint.ui says `[breakpoint]` is nothing more than another one of
    // those. An object-valued PROPERTY is a different construct and lives in emitProperty.
    xml.startTag('child', { type: child.slot });
    if (child.object.kind === 'menu') emitMenu(xml, child.object, context);
    else emitObject(xml, child.object, context);
    xml.endTag();
}

// ------------------------------------------------------------------ properties

/** @param {XmlWriter} xml @param {Property} property @param {string} ownerType @param {EmitContext} context */
function emitProperty(xml, property, ownerType, context) {
    const value = property.value;

    if (value.kind === 'binding') {
        // 13-binding.ui: a simple binding is a SELF-CLOSING property, and the compiler adds
        // a `sync-create` the source never wrote.
        xml.selfClosing('property', {
            name: property.name,
            'bind-source': objectId(value.source, context),
            'bind-property': value.property,
            'bind-flags': bindFlags(value.flags),
        });
        return;
    }

    if (value.kind === 'object') {
        // 06-property-object-valued.ui, and 08/18 for the `child:` spelling of it.
        xml.startTag('property', { name: property.name });
        emitObject(xml, value.object, context);
        xml.endTag();
        return;
    }

    if (value.kind === 'list') {
        emitListProperty(xml, property, value);
        return;
    }

    xml.startTag('property', { name: property.name, ...translatedAttributes(value) });
    xml.text(scalarText(value, ownerType, context));
    xml.endTag();
}

/**
 * The compiler's own flag set, in the compiler's own order, and absent entirely when empty.
 *
 * 13-binding.ui shows only the added `sync-create`; the other three answers were measured on
 * 0.20.4 and the manifest's note on that file says a parser that hardcodes `sync-create`
 * passes the corpus and is wrong: `no-sync-create` drops the attribute, and `inverted` /
 * `bidirectional` join with `|` in THIS order regardless of how the source spelled them.
 *
 * @param {readonly string[]} flags
 */
function bindFlags(flags) {
    const emitted = [];
    if (!flags.includes('no-sync-create')) emitted.push('sync-create');
    if (flags.includes('inverted')) emitted.push('invert-boolean');
    if (flags.includes('bidirectional')) emitted.push('bidirectional');
    return emitted.length === 0 ? null : emitted.join('|');
}

/**
 * `styles`, `strings` and `widgets` are three different XML shapes, told apart by the
 * property NAME because that is the only thing left of them in the AST.
 *
 * In Blueprint's own grammar these are three distinct block extensions; the AST this
 * emitter consumes flattens all bracketed lists into one `ListValue`, so the name is what
 * has to carry the difference — 10-styles.ui (`<style><class name="…"/></style>`, not a
 * property), 21-value-array.ui (`<items><item>…</item></items>`) and
 * 23-widget-reference-list.ui (`<widgets><widget name="…"/></widgets>`, so the ids they
 * point at are load-bearing) are three files that would otherwise collapse into one rule.
 *
 * Any other list-valued property throws rather than guessing a shape, in the spirit of ADR
 * 0053 clause 3: output that looks plausible and means something else is the defect worth
 * refusing.
 *
 * @param {XmlWriter} xml @param {Property} property @param {Extract<Value, { kind: 'list' }>} value
 */
function emitListProperty(xml, property, value) {
    if (property.name === 'styles') {
        xml.startTag('style', {});
        for (const item of value.items) xml.selfClosing('class', { name: listItemText(item) });
        xml.endTag();
        return;
    }

    if (property.name === 'widgets') {
        xml.startTag('widgets', {});
        for (const item of value.items) xml.selfClosing('widget', { name: listItemText(item) });
        xml.endTag();
        return;
    }

    if (property.name === 'strings') {
        xml.startTag('items', {});
        for (const item of value.items) {
            xml.startTag('item', translatedAttributes(item));
            xml.text(listItemText(item));
            xml.endTag();
        }
        xml.endTag();
        return;
    }

    throw new Error(
        `blueprint: line ${property.line}: no emitter rule for the list-valued property "${property.name}"`,
    );
}

/** @param {Value} item */
function listItemText(item) {
    if (item.kind === 'string') return item.value;
    if (item.kind === 'ident') return item.name;
    throw new Error(`blueprint: line ${item.line}: a list item that is neither a string nor an identifier`);
}

/**
 * 09-translatable.ui: `_()` is `translatable="yes"` alone, `C_()` is that PLUS `context`,
 * in that order. The marking travels with the value, so a menu attribute, a `<setter>` and
 * a `<item>` inside a string list all take the same two attributes.
 *
 * @param {Value} value
 * @returns {Record<string, unknown>}
 */
function translatedAttributes(value) {
    if (value.kind !== 'string' || value.translatable === undefined) return {};
    return { translatable: 'yes', context: value.translatable.context };
}

// ------------------------------------------------------------------ scalar values

/** @param {Value} value @param {string | null} ownerType @param {EmitContext} context */
function scalarText(value, ownerType, context) {
    if (value.kind === 'string') return value.value;
    if (value.kind === 'bool') return value.value ? 'true' : 'false';
    if (value.kind === 'number') return numberText(value.raw);
    if (value.kind === 'ident') return identText(value.name, ownerType, context);
    throw new Error(`blueprint: line ${value.line}: a ${value.kind} value where a scalar was expected`);
}

/**
 * The enum seam. See `EmitOptions.resolveEnum` for what `typeName` is and is not.
 *
 * With no resolver the identifier is emitted AS WRITTEN, which is a knowing divergence from
 * 03-property-enum.ui rather than a guess at its `1`: an emitter that shipped a table of
 * enum members would be the `if` ADR 0053 clause 6 refuses, and the first member it got
 * wrong would be wrong silently. An identifier that is an object reference rather than an
 * enum member takes the same path and is right without a resolver — 12-menu.ui's
 * `menu-model: mainMenu` emits the id as plain text.
 *
 * @param {string} name @param {string | null} ownerType @param {EmitContext} context
 */
function identText(name, ownerType, context) {
    if (ownerType !== null && context.resolveEnum !== undefined) {
        const resolved = context.resolveEnum(ownerType, name);
        if (resolved !== null && resolved !== undefined) return String(resolved);
    }
    return objectId(name, context);
}

/**
 * 17-numeric-forms.ui: `1.0` is normalised to `1` while `0.25` and `0.5` are not, and `-1`
 * and `0` survive. The rule behind those four lines is that a value the source spelled with
 * a `.` but which lands on a whole number is emitted as an integer — which is why the AST
 * keeps the raw spelling and this is the only place that reads it.
 *
 * BigInt and not Number: the reference goes through Python's arbitrary-precision `int`, so
 * `123456789012345678.0` emits all eighteen digits (measured on 0.20.4) and a 17-digit
 * literal is exact. Underscore separators and the `0x` form are Blueprint's own number
 * grammar; an exponent is not, so there is no `e` case to handle.
 *
 * @param {string} raw
 */
function numberText(raw) {
    const cleaned = raw.replaceAll('_', '');
    const negative = cleaned.startsWith('-');
    const digits = negative || cleaned.startsWith('+') ? cleaned.slice(1) : cleaned;

    if (!digits.includes('.')) {
        const whole = BigInt(digits);
        return (negative ? -whole : whole).toString();
    }

    const asFloat = negative ? -Number(digits) : Number(digits);
    return Number.isInteger(asFloat) ? BigInt(asFloat).toString() : String(asFloat);
}

// ------------------------------------------------------------------ signals

/** @param {XmlWriter} xml @param {Signal} signal @param {EmitContext} context */
function emitSignal(xml, signal, context) {
    // 11-signal.ui has the bare shape. The rest was measured on 0.20.4 and is stranger than
    // it looks: the flags are emitted as PYTHON booleans, so `swapped` becomes
    // `swapped="True"` — capital T, and `not-swapped` becomes `swapped="False"` rather than
    // dropping the attribute, while `after` drops it when absent. The detail of
    // `notify::sensitive` is folded back into `name`.
    xml.selfClosing('signal', {
        name: signal.detail === undefined ? signal.name : `${signal.name}::${signal.detail}`,
        handler: signal.handler,
        swapped: swappedAttribute(signal.flags),
        after: signal.flags.includes('after') ? 'True' : null,
        object: signal.object === undefined ? null : objectId(signal.object, context),
    });
}

/** @param {readonly string[]} flags */
function swappedAttribute(flags) {
    if (flags.includes('swapped')) return 'True';
    if (flags.includes('not-swapped')) return 'False';
    return null;
}

// ------------------------------------------------------------------ extension blocks

/** @param {XmlWriter} xml @param {Extension} extension @param {string} ownerType @param {EmitContext} context */
function emitExtension(xml, extension, ownerType, context) {
    if (extension.name === 'condition') {
        // 14-breakpoint.ui: the condition is element TEXT, not an attribute and not a property.
        xml.startTag('condition', {});
        xml.text(conditionText(extension));
        xml.endTag();
        return;
    }

    if (extension.name === 'setters') {
        // …and the `setters { }` BLOCK has no element of its own: each setter is a sibling
        // of the `<condition>`, which is why this arm writes no wrapper.
        for (const setter of extension.entries) emitSetter(xml, setter, context);
        return;
    }

    if (extension.name === 'layout' || extension.name === 'accessibility') {
        // 19-layout.ui and 20-accessibility.ui: same shape, one wrapper element named after
        // the block, holding ordinary `<property>` elements.
        xml.startTag(extension.name, {});
        for (const entry of extension.entries) {
            xml.startTag('property', { name: entry.name, ...translatedAttributes(entry.value) });
            xml.text(scalarText(entry.value, ownerType, context));
            xml.endTag();
        }
        xml.endTag();
        return;
    }

    throw new Error(`blueprint: line ${extension.line}: no emitter rule for the "${extension.name}" block`);
}

/** @param {XmlWriter} xml @param {Property} setter @param {EmitContext} context */
function emitSetter(xml, setter, context) {
    const dot = setter.name.indexOf('.');
    if (dot < 1) {
        throw new Error(`blueprint: line ${setter.line}: a setter needs an "<object>.<property>" target`);
    }
    const target = setter.name.slice(0, dot);
    const property = setter.name.slice(dot + 1);

    xml.startTag('setter', {
        object: objectId(target, context),
        property,
        ...translatedAttributes(setter.value),
    });
    // The owner type here is the type of the object the setter POINTS AT, not the
    // breakpoint it sits in, so an enum-valued setter resolves against the right widget.
    xml.text(scalarText(setter.value, context.idTypes.get(target) ?? null, context));
    xml.endTag();
}

/**
 * `Extension.argument` is documented as the parenthesised text UNDECODED, so unlike every
 * `StringValue` in the AST it still carries its quotes and its escapes. Decoded here and
 * nowhere else. A value that arrives without quotes is passed through, so a parser that
 * decodes it after all produces the same bytes.
 *
 * @param {Extension} extension
 */
function conditionText(extension) {
    const argument = extension.argument ?? '';
    const quote = argument.charAt(0);
    if (argument.length < 2 || (quote !== '"' && quote !== "'") || !argument.endsWith(quote)) return argument;
    return unescapeQuoted(argument.slice(1, -1));
}

/** Blueprint's escape set, and it is closed: an unknown escape is an error upstream, not a literal. */
const STRING_ESCAPES = new Map([
    ['n', '\n'],
    ['t', '\t'],
    ['\\', '\\'],
    ['"', '"'],
    ["'", "'"],
    ['\n', '\n'],
]);

/** @param {string} body */
function unescapeQuoted(body) {
    let out = '';
    for (let i = 0; i < body.length; i += 1) {
        if (body[i] !== '\\') {
            out += body[i];
            continue;
        }
        i += 1;
        const replacement = STRING_ESCAPES.get(body[i]);
        if (replacement === undefined) {
            throw new Error(`blueprint: invalid escape sequence "\\${body[i]}" in a condition`);
        }
        out += replacement;
    }
    return out;
}

// ------------------------------------------------------------------ menus

/** @param {XmlWriter} xml @param {MenuNode | MenuItem} menu @param {EmitContext} context */
function emitMenu(xml, menu, context) {
    // 12-menu.ui: a top-level `menu` is a SIBLING of the objects and carries the id; the
    // `section` / `item` / `submenu` inside it are elements named after their keyword and
    // carry none. 22-menu-nested.ui adds that an attribute and a nested item interleave in
    // source order, so the merge is the same one `emitBody` does.
    const isRoot = menu.kind === 'menu';
    xml.startTag(isRoot ? 'menu' : menu.kind, { id: isRoot ? menu.id : undefined });

    const members = inSourceOrder([
        ['attribute', isRoot ? [] : menu.attributes],
        ['item', menu.items],
    ]);
    for (const [kind, member] of members) {
        if (kind === 'item') {
            emitMenu(xml, /** @type {MenuItem} */ (member), context);
            continue;
        }
        const attribute = /** @type {Property} */ (member);
        xml.startTag('attribute', { name: attribute.name, ...translatedAttributes(attribute.value) });
        // No owner type: a menu attribute belongs to a GMenuModel, which has no ParamSpecs
        // for a resolver to search, and 22-menu-nested.ui's `item ("Deep", "app.deep")`
        // shorthand carries plain strings either way.
        xml.text(scalarText(attribute.value, null, context));
        xml.endTag();
    }

    xml.endTag();
}

// ------------------------------------------------------------------ names and ids

/**
 * The GType name, which is what every `class=` and `parent=` in the goldens holds.
 *
 * An unqualified type is a Gtk type and nothing else — 24-unqualified-type.ui's `Box` is
 * `GtkBox` under `using Gtk 4.0;`, and the manifest records that `using Adw 1;` does not
 * make a bare `Bin` legal. For a qualified one the goldens only ever show namespace and
 * name concatenated (`Adw.Bin` -> `AdwBin`), which is what the GIR C-prefix happens to be
 * for both namespaces every corpus file uses.
 *
 * @param {TypeRef} type
 */
function gtypeName(type) {
    return `${type.namespace ?? 'Gtk'}${type.name}`;
}

/**
 * `template` used as an object id means the template's own class — measured on 0.20.4,
 * which rewrites it in `bind-source`, in a signal's `object` and in a setter's `object`.
 * No golden carries it; the rewrite is one line and its absence would be a wrong id rather
 * than a missing one.
 *
 * @param {string} id @param {EmitContext} context
 */
function objectId(id, context) {
    return id === 'template' && context.templateClass !== undefined ? context.templateClass : id;
}

/** @param {readonly BlueprintImport[]} imports */
function gtkVersion(imports) {
    // 0.20.4 refuses anything but `using Gtk 4.0;` ("Expected the GIR version, not an exact
    // version number"), so this reads the import rather than hardcoding a constant it would
    // then have to keep in sync, and the fallback is for a file that names no Gtk import at
    // all — which the reference compiler rejects outright.
    return imports.find((entry) => entry.namespace === 'Gtk')?.version ?? '4.0';
}

/** @param {BlueprintFile} file */
function findTemplateClass(file) {
    for (const root of file.roots) {
        if (root.kind === 'template') return root.className;
    }
    return undefined;
}

/**
 * Every object id in the file with the GType it was declared as, so a `<setter>` can resolve
 * an enum against the object it targets rather than against the breakpoint it is written in.
 *
 * @param {BlueprintFile} file
 */
function indexObjectIds(file) {
    /** @type {Map<string, string>} */
    const byId = new Map();
    for (const root of file.roots) {
        if (root.kind === 'object') indexObject(root, byId);
        else if (root.kind === 'template') indexBody(root.body, byId);
    }
    return byId;
}

/** @param {ObjectNode} object @param {Map<string, string>} byId */
function indexObject(object, byId) {
    if (object.id !== undefined) byId.set(object.id, gtypeName(object.type));
    indexBody(object.body, byId);
}

/** @param {ObjectBody} body @param {Map<string, string>} byId */
function indexBody(body, byId) {
    for (const property of body.properties) indexValue(property.value, byId);
    for (const child of body.children) {
        if (child.object.kind === 'object') indexObject(child.object, byId);
    }
}

/** @param {Value} value @param {Map<string, string>} byId */
function indexValue(value, byId) {
    if (value.kind === 'object') indexObject(value.object, byId);
    else if (value.kind === 'list') {
        for (const item of value.items) indexValue(item, byId);
    }
}
