import { stringIsNotEmpty, stripMnemonic } from './glib.js';

// Headless `Adw.PreferencesGroup` / `Adw.PreferencesDialog` behaviour
// (ADR 0004 — headless Adwaita core).
//
// Two halves live here, deliberately the only two:
//
// 1. THE GROUP HEADER DERIVATION — five booleans, including `single-line`, which
// keys real metrics in the Adwaita stylesheet
// (`> box.header:not(.single-line) { margin-bottom: 6px }` vs
// `> box.single-line { min-height: 34px }`), and the zero-row listbox hide,
// without which an empty group still strokes the full-width `box-shadow`
// hairline of its `.boxed-list` card.
//
// 2. THE SEARCH PIPELINE. Its rules are spread over three C files and two are
// counter-intuitive:
// - `make_comparable` folds FIRST and parses markup SECOND, so the lowercased
// `<b>` tags still parse;
// - the corpus is `visible page → visible group → row that is a preferences row
// AND visible AND has a non-empty title`, with the three filters in three
// different C files.
// Get the corpus wrong and an application's search finds nothing, with no error
// anywhere.
//
// NOT HERE: `present`/`close`/`can-close`/`::closed` is `Adw.Dialog` behaviour, which
// the preferences dialog composes. The page collection (`visible-page`,
// `visible-page-name`, the auto-pick and the remove-vs-hide asymmetry) is
// `Adw.ViewStack`, already lifted as `ViewStackState` in `view-stack.ts` —
// `adw_preferences_dialog_add` binds a page onto exactly that, so a renderer reaches
// for `ViewStackState` rather than a second page model.
//
// Reference: refs/libadwaita/src/adw-preferences-group.c
// (update_title_visibility, update_description_visibility,
// update_listbox_visibility, is_single_line, update_header_visibility,
// row_has_title, adw_preferences_group_get_rows)
// Reference: refs/libadwaita/src/adw-preferences-page.c
// (is_visible_group, adw_preferences_page_get_rows, set_title/set_description)
// Reference: refs/libadwaita/src/adw-preferences-dialog.c
// (make_comparable, filter_search_results, get_n_pages,
// create_search_row_subtitle, new_search_row_for_preference)
// Reference: refs/libadwaita/src/adw-widget-utils.c (adw_strip_mnemonic)
// Reference: refs/libadwaita/src/adw-preferences-group.ui (use-markup on both labels)
// Reference: refs/libadwaita/src/stylesheet/widgets/_preferences.scss (single-line metrics)
// Copyright (c) GNOME contributors (libadwaita). LGPLv2.1+.

// Case folding

/**
 * A caseless-compare normaliser, i.e. what `g_utf8_casefold` does for the C. Injected
 * rather than hard-wired because full Unicode case folding is a DATA TABLE, not a
 * language builtin, and a size-sensitive renderer may legitimately trade the table away.
 */
export type CaseFolder = (text: string) => string;

/**
 * Every character whose Unicode **full case folding** differs from its lowercase
 * mapping, keyed by the LOWERCASED form. Generated by walking all of Unicode and
 * comparing `casefold(cp)` against `lower(cp)`, then verified exhaustively:
 * `applyExtras(lower(cp)) === casefold(cp)` for every code point. The two Cherokee
 * ranges are the only regular ones and are handled arithmetically in
 * {@link defaultCaseFolder} rather than as 86 more rows. The rows that matter in
 * shipped languages are `ß → ss`, final `ς → σ` and the `ﬁ`/`ﬂ` ligatures.
 */
const CASEFOLD_EXTRAS: ReadonlyMap<string, string> = new Map([
    ['\u00B5', '\u03BC'],
    ['\u00DF', 'ss'],
    ['\u0149', '\u02BCn'],
    ['\u017F', 's'],
    ['\u01F0', 'j\u030C'],
    ['\u0345', '\u03B9'],
    ['\u0390', '\u03B9\u0308\u0301'],
    ['\u03B0', '\u03C5\u0308\u0301'],
    ['\u03C2', '\u03C3'],
    ['\u03D0', '\u03B2'],
    ['\u03D1', '\u03B8'],
    ['\u03D5', '\u03C6'],
    ['\u03D6', '\u03C0'],
    ['\u03F0', '\u03BA'],
    ['\u03F1', '\u03C1'],
    ['\u03F5', '\u03B5'],
    ['\u0587', '\u0565\u0582'],
    ['\u1C80', '\u0432'],
    ['\u1C81', '\u0434'],
    ['\u1C82', '\u043E'],
    ['\u1C83', '\u0441'],
    ['\u1C84', '\u0442'],
    ['\u1C85', '\u0442'],
    ['\u1C86', '\u044A'],
    ['\u1C87', '\u0463'],
    ['\u1C88', '\uA64B'],
    ['\u1E96', 'h\u0331'],
    ['\u1E97', 't\u0308'],
    ['\u1E98', 'w\u030A'],
    ['\u1E99', 'y\u030A'],
    ['\u1E9A', 'a\u02BE'],
    ['\u1E9B', '\u1E61'],
    ['\u1F50', '\u03C5\u0313'],
    ['\u1F52', '\u03C5\u0313\u0300'],
    ['\u1F54', '\u03C5\u0313\u0301'],
    ['\u1F56', '\u03C5\u0313\u0342'],
    ['\u1F80', '\u1F00\u03B9'],
    ['\u1F81', '\u1F01\u03B9'],
    ['\u1F82', '\u1F02\u03B9'],
    ['\u1F83', '\u1F03\u03B9'],
    ['\u1F84', '\u1F04\u03B9'],
    ['\u1F85', '\u1F05\u03B9'],
    ['\u1F86', '\u1F06\u03B9'],
    ['\u1F87', '\u1F07\u03B9'],
    ['\u1F90', '\u1F20\u03B9'],
    ['\u1F91', '\u1F21\u03B9'],
    ['\u1F92', '\u1F22\u03B9'],
    ['\u1F93', '\u1F23\u03B9'],
    ['\u1F94', '\u1F24\u03B9'],
    ['\u1F95', '\u1F25\u03B9'],
    ['\u1F96', '\u1F26\u03B9'],
    ['\u1F97', '\u1F27\u03B9'],
    ['\u1FA0', '\u1F60\u03B9'],
    ['\u1FA1', '\u1F61\u03B9'],
    ['\u1FA2', '\u1F62\u03B9'],
    ['\u1FA3', '\u1F63\u03B9'],
    ['\u1FA4', '\u1F64\u03B9'],
    ['\u1FA5', '\u1F65\u03B9'],
    ['\u1FA6', '\u1F66\u03B9'],
    ['\u1FA7', '\u1F67\u03B9'],
    ['\u1FB2', '\u1F70\u03B9'],
    ['\u1FB3', '\u03B1\u03B9'],
    ['\u1FB4', '\u03AC\u03B9'],
    ['\u1FB6', '\u03B1\u0342'],
    ['\u1FB7', '\u03B1\u0342\u03B9'],
    ['\u1FBE', '\u03B9'],
    ['\u1FC2', '\u1F74\u03B9'],
    ['\u1FC3', '\u03B7\u03B9'],
    ['\u1FC4', '\u03AE\u03B9'],
    ['\u1FC6', '\u03B7\u0342'],
    ['\u1FC7', '\u03B7\u0342\u03B9'],
    ['\u1FD2', '\u03B9\u0308\u0300'],
    ['\u1FD3', '\u03B9\u0308\u0301'],
    ['\u1FD6', '\u03B9\u0342'],
    ['\u1FD7', '\u03B9\u0308\u0342'],
    ['\u1FE2', '\u03C5\u0308\u0300'],
    ['\u1FE3', '\u03C5\u0308\u0301'],
    ['\u1FE4', '\u03C1\u0313'],
    ['\u1FE6', '\u03C5\u0342'],
    ['\u1FE7', '\u03C5\u0308\u0342'],
    ['\u1FF2', '\u1F7C\u03B9'],
    ['\u1FF3', '\u03C9\u03B9'],
    ['\u1FF4', '\u03CE\u03B9'],
    ['\u1FF6', '\u03C9\u0342'],
    ['\u1FF7', '\u03C9\u0342\u03B9'],
    ['\uFB00', 'ff'],
    ['\uFB01', 'fi'],
    ['\uFB02', 'fl'],
    ['\uFB03', 'ffi'],
    ['\uFB04', 'ffl'],
    ['\uFB05', 'st'],
    ['\uFB06', 'st'],
    ['\uFB13', '\u0574\u0576'],
    ['\uFB14', '\u0574\u0565'],
    ['\uFB15', '\u0574\u056B'],
    ['\uFB16', '\u057E\u0576'],
    ['\uFB17', '\u0574\u056D'],
]);

/**
 * The two Cherokee case-folding ranges, which fold lowercase UP to uppercase —
 * the reverse of every other script, and the reason `toLowerCase()` alone
 * cannot be a case fold even for single-character mappings.
 *
 * `CaseFolding.txt`: `AB70..ABBF; C; 13A0..13EF` and `13F8..13FD; C; 13F0..13F5`.
 */
function foldCherokee(codePoint: number): string | undefined {
    if (codePoint >= 0xab70 && codePoint <= 0xabbf) return String.fromCodePoint(codePoint - 0xab70 + 0x13a0);
    if (codePoint >= 0x13f8 && codePoint <= 0x13fd) return String.fromCodePoint(codePoint - 8);
    return undefined;
}

/**
 * `g_utf8_casefold` — Unicode FULL case folding, i.e. `toLowerCase()` plus the mappings
 * where a case fold and a lowercase mapping disagree. The obvious implementation ships
 * wrong behaviour in languages people actually use, invisibly to an ASCII test suite;
 * the three canaries, verified against a real full-folding implementation:
 *
 * | input | `toLowerCase()` | case fold |
 * |----------|-----------------|------------|
 * | `Straße` | `straße` | `strasse` |
 * | `ΟΔΟΣ` | `οδος` | `οδοσ` |
 * | `ﬁle` | `ﬁle` | `file` |
 *
 * `normalize('NFKC').toLowerCase` is NOT a substitute: it repairs the
 * ligature, still misses `ß` and final sigma, and OVER-normalises `Ǆ` (U+01C4)
 * to the two-character `dž` where a case fold gives the single character `ǆ`.
 */
export const defaultCaseFolder: CaseFolder = (text: string): string => {
    let folded = '';
    for (const character of text.toLowerCase()) {
        const codePoint = character.codePointAt(0)!;
        // Latin-1 and below can never be Cherokee, and only two characters in it
        // are in the table — worth the branch, this runs on every keystroke.
        if (codePoint < 0xb5) {
            folded += character;
            continue;
        }
        folded += CASEFOLD_EXTRAS.get(character) ?? foldCherokee(codePoint) ?? character;
    }
    return folded;
};

// Pango markup

/** The tag names pango's markup parser knows; anything else is a parse ERROR. */
const PANGO_MARKUP_TAGS: ReadonlySet<string> = new Set([
    'markup',
    'span',
    'b',
    'big',
    'i',
    's',
    'sub',
    'sup',
    'small',
    'tt',
    'u',
]);

/** The five named entities GMarkup resolves. Everything else must be numeric. */
const NAMED_ENTITIES: ReadonlyMap<string, string> = new Map([
    ['amp', '&'],
    ['lt', '<'],
    ['gt', '>'],
    ['quot', '"'],
    ['apos', "'"],
]);

const NAME_START = /[A-Za-z_:]/;
const NAME_CHAR = /[A-Za-z0-9._:-]/;
const XML_SPACE = /[ \t\r\n]/;

/**
 * `g_markup_escape_text` — the escape `create_search_row_subtitle` puts a page title
 * through before it becomes a markup subtitle. GLib emits NUMERIC references for the
 * quote characters (`&#39;`, `&#34;`), not `&apos;`/`&quot;`, so a port that "tidies"
 * those up produces a different string. Control characters become `&#xN;`; GLib's own C1
 * branch is unreachable for valid UTF-8 (it compares a signed `char` against
 * `0x7f`-`0x9f`), so only the ASCII controls are escaped here.
 */
export function escapeMarkup(text: string): string {
    let escaped = '';
    for (const character of text) {
        switch (character) {
            case '&':
                escaped += '&amp;';
                break;
            case '<':
                escaped += '&lt;';
                break;
            case '>':
                escaped += '&gt;';
                break;
            case "'":
                escaped += '&#39;';
                break;
            case '"':
                escaped += '&#34;';
                break;
            default: {
                const codePoint = character.codePointAt(0)!;
                const isControl =
                    (codePoint >= 0x01 && codePoint <= 0x08) ||
                    (codePoint >= 0x0b && codePoint <= 0x0c) ||
                    (codePoint >= 0x0e && codePoint <= 0x1f) ||
                    codePoint === 0x7f;
                escaped += isControl ? `&#x${codePoint.toString(16)};` : character;
            }
        }
    }
    return escaped;
}

/** Where a passthrough construct (`<!-- -->`, `<![CDATA[]]>`, `<? ?>`) ends. */
function passthroughEnd(text: string, start: number): { terminator: string } | null {
    if (text.startsWith('<!--', start)) return { terminator: '-->' };
    if (text.startsWith('<![CDATA[', start)) return { terminator: ']]>' };
    if (text.startsWith('<!', start) || text.startsWith('<?', start)) return { terminator: '>' };
    return null;
}

/** Resolve one `&…;` reference at `start`, or `null` when GMarkup would error. */
function readEntity(text: string, start: number): { value: string; next: number } | null {
    const end = text.indexOf(';', start);
    if (end < 0) return null;

    const body = text.slice(start + 1, end);
    if (body.length === 0) return null;

    if (body.startsWith('#')) {
        const hex = body[1] === 'x' || body[1] === 'X';
        const digits = hex ? body.slice(2) : body.slice(1);
        if (digits.length === 0) return null;
        if (!(hex ? /^[0-9a-fA-F]+$/ : /^[0-9]+$/).test(digits)) return null;
        const codePoint = Number.parseInt(digits, hex ? 16 : 10);
        // GMarkup validates the reference is a legal XML character.
        if (codePoint <= 0 || codePoint > 0x10ffff) return null;
        if (codePoint >= 0xd800 && codePoint <= 0xdfff) return null;
        return { value: String.fromCodePoint(codePoint), next: end + 1 };
    }

    const named = NAMED_ENTITIES.get(body);
    return named === undefined ? null : { value: named, next: end + 1 };
}

/** Read a start or end tag beginning at `<`, or `null` on malformed markup. */
function readTag(
    text: string,
    start: number,
): { name: string; closing: boolean; selfClosing: boolean; hasAttributes: boolean; next: number } | null {
    let index = start + 1;
    const closing = text[index] === '/';
    if (closing) index += 1;

    if (index >= text.length || !NAME_START.test(text[index]!)) return null;
    const nameStart = index;
    while (index < text.length && NAME_CHAR.test(text[index]!)) index += 1;
    const name = text.slice(nameStart, index);

    let hasAttributes = false;
    let selfClosing = false;
    while (index < text.length) {
        while (index < text.length && XML_SPACE.test(text[index]!)) index += 1;
        const character = text[index];
        if (character === undefined) return null;
        if (character === '>') return { name, closing, selfClosing, hasAttributes, next: index + 1 };
        if (character === '/') {
            if (closing || text[index + 1] !== '>') return null;
            selfClosing = true;
            return { name, closing, selfClosing, hasAttributes, next: index + 2 };
        }
        if (closing) return null; // an end tag carries no attributes

        // attribute: name `=` quoted-value
        if (!NAME_START.test(character)) return null;
        while (index < text.length && NAME_CHAR.test(text[index]!)) index += 1;
        while (index < text.length && XML_SPACE.test(text[index]!)) index += 1;
        if (text[index] !== '=') return null;
        index += 1;
        while (index < text.length && XML_SPACE.test(text[index]!)) index += 1;
        const quote = text[index];
        if (quote !== '"' && quote !== "'") return null;
        const valueEnd = text.indexOf(quote, index + 1);
        if (valueEnd < 0) return null;
        index = valueEnd + 1;
        hasAttributes = true;
    }
    return null;
}

/**
 * `pango_parse_markup (text, -1, 0, NULL, &parsed, NULL, &error)` reduced to the part
 * `make_comparable` uses: the plain text, tags dropped and entities resolved.
 *
 * Returns `null` — NEVER throws — when the markup does not parse, so callers reproduce
 * the C fallback exactly (`g_critical`, keep the UNPARSED string): a row whose title
 * contains a bare `&` must stay in the search index under its literal text.
 *
 * Pango wraps the input in an implicit `<markup>` element, so several top-level tags are
 * legal, and unknown tag names are a parse error — which is why this keeps pango's tag
 * list rather than stripping anything tag-shaped: `<3` and `<div>` are TEXT to
 * libadwaita and a search for them must find them.
 *
 * Deviations, both fail-closed (unparsed → the caller keeps the raw string, never a
 * wrongly-stripped one): pango additionally validates `<span>`'s attribute NAMES, and
 * this does not; GMarkup's DOCTYPE/PI/CDATA handling is modelled as plain passthrough,
 * which is what pango's parser does with it (its `passthrough` handler is NULL, so the
 * content is discarded).
 */
export function stripMarkup(text: string): string | null {
    let plain = '';
    const open: string[] = [];
    let index = 0;

    while (index < text.length) {
        const character = text[index]!;

        if (character === '&') {
            const entity = readEntity(text, index);
            if (!entity) return null;
            plain += entity.value;
            index = entity.next;
            continue;
        }

        if (character !== '<') {
            plain += character;
            index += 1;
            continue;
        }

        const passthrough = passthroughEnd(text, index);
        if (passthrough) {
            const end = text.indexOf(passthrough.terminator, index + 2);
            if (end < 0) return null;
            index = end + passthrough.terminator.length;
            continue;
        }

        const tag = readTag(text, index);
        if (!tag) return null;
        if (!PANGO_MARKUP_TAGS.has(tag.name)) return null;
        // `check_no_attributes` — only <span> takes attributes.
        if (tag.hasAttributes && tag.name !== 'span') return null;

        if (tag.closing) {
            if (open.pop() !== tag.name) return null;
        } else if (!tag.selfClosing) {
            open.push(tag.name);
        }
        index = tag.next;
    }

    // `g_markup_parse_context_end_parse` fails on an unclosed element.
    return open.length === 0 ? plain : null;
}

/** Per-row flags `make_comparable` reads off the row it is comparing. */
export interface MakeComparableOptions {
    /** `AdwPreferencesRow:use-markup`. Defaults to `true`, as the property does. */
    useMarkup?: boolean;
    /** `AdwPreferencesRow:use-underline`. Defaults to `false`, as the property does. */
    useUnderline?: boolean;
    /**
     * `make_comparable`'s third argument. The TITLE path passes `true`, the
     * SUBTITLE path passes `false` — so a
     * subtitle keeps its underscores even on a row that uses mnemonics.
     */
    allowUnderline?: boolean;
}

/**
 * `make_comparable`: the form of a string the search compares against — case-folded,
 * markup-stripped and (for titles on mnemonic rows) mnemonic-stripped.
 *
 * THE ORDER IS NOT THE OBVIOUS ONE: fold FIRST, parse the FOLDED string second, as the C
 * does. The two differ for any markup whose tag name is case-sensitive to the parser;
 * folding a lowercase-only tag set leaves it parseable, which is why `<b>Dark</b> Style`
 * still reduces to `dark style` rather than keeping its tags.
 */
export function makeComparable(
    source: string | null | undefined,
    options: MakeComparableOptions = {},
    fold: CaseFolder = defaultCaseFolder,
): string {
    let plaintext = fold(source ?? '');

    if (options.useMarkup ?? true) {
        // A failed parse keeps the folded text — the C logs a g_critical and
        // carries on, so the row stays searchable under its literal spelling.
        plaintext = stripMarkup(plaintext) ?? plaintext;
    }

    if ((options.allowUnderline ?? true) && (options.useUnderline ?? false)) {
        plaintext = stripMnemonic(plaintext);
    }

    return plaintext;
}

// Group header derivation

/** What {@link derivePreferencesGroupHeader} is asked about. */
export interface PreferencesGroupHeaderInput {
    /**
     * `AdwPreferencesGroup:title`. `null`/`undefined` is the empty string —
     * `adw_preferences_group_set_title` normalises NULL to `""`.
     */
    title?: string | null;
    /**
     * `AdwPreferencesGroup:description`. Normalised here as well, although
     * `adw_preferences_group_set_description` passes NULL straight through
     * where its own `set_title` and `adw_preferences_page_set_title`
     * both normalise — an inconsistency in the C
     * with no behavioural consequence, since the visibility test treats NULL and
     * `""` alike.
     */
    description?: string | null;
    /** Whether an `AdwPreferencesGroup:header-suffix` widget is set. */
    hasHeaderSuffix?: boolean;
    /**
     * How many children the listbox holds. This is the RAW child count —
     * `update_listbox_visibility` reads `gtk_widget_observe_children (listbox)`,
     * NOT the title-filtered model that
     * `get_rows` builds, so a row with an empty title still keeps the card
     * painted.
     */
    rowCount?: number;
    /**
     * Whether the title/description labels interpret Pango markup. `true` by
     * default because both labels are `use-markup=True` in
     * adw-preferences-group.ui — a renderer that shows the strings verbatim
     * passes `false`.
     */
    useMarkup?: boolean;
}

/** The five derived visual states of a preferences group. */
export interface PreferencesGroupHeaderState {
    /** `update_title_visibility`. */
    titleVisible: boolean;
    /** `update_description_visibility`. */
    descriptionVisible: boolean;
    /** `update_header_visibility` — the header box takes no space otherwise. */
    headerVisible: boolean;
    /**
     * `is_single_line`, carried as the `single-line` style class.
     * Load-bearing: the stylesheet gives a single-line header `min-height: 34px`
     * and a multi-line one `margin-bottom: 6px`
     * (stylesheet/widgets/_preferences.scss).
     */
    singleLine: boolean;
    /** `update_listbox_visibility` — the `.boxed-list` card is hidden at zero rows. */
    listboxVisible: boolean;
}

/**
 * The text a `use-markup` label DISPLAYS, which is what the visibility tests
 * read: `update_title_visibility` compares `gtk_label_get_text` — markup already
 * stripped — while `adw_preferences_group_get_title` returns
 * `gtk_label_get_label`, the raw markup (adw-preferences-group.c vs:485).
 *
 * So a title of `<b></b>` reads back as `<b></b>` and is HIDDEN. Unparseable
 * markup keeps the raw string, which is both the safe direction and what a
 * renderer that paints the string verbatim shows.
 */
function displayedLabelText(value: string | null | undefined, useMarkup: boolean): string {
    const raw = value ?? '';
    if (!useMarkup) return raw;
    return stripMarkup(raw) ?? raw;
}

/**
 * The five header/listbox states of an `Adw.PreferencesGroup`, derived once for
 * every renderer.
 *
 * A pure derivation rather than a state machine, which is the honest shape: C
 * recomputes all of this from scratch in `update_*_visibility` on every change,
 * holding no state of its own beyond the widgets it is reading.
 *
 * Only the EXACT empty string hides a label — `g_strcmp0 (text, "")`, so a title
 * of a single space is a visible title and must not be trimmed. That is the same
 * rule {@link stringIsNotEmpty} carries for the label bindings, so it is applied
 * from there rather than respelled here; what stays local is only which STRING it
 * is applied to, since this widget judges the markup-stripped display text.
 */
export function derivePreferencesGroupHeader(input: PreferencesGroupHeaderInput): PreferencesGroupHeaderState {
    const useMarkup = input.useMarkup ?? true;
    const titleVisible = stringIsNotEmpty(displayedLabelText(input.title, useMarkup));
    const descriptionVisible = stringIsNotEmpty(displayedLabelText(input.description, useMarkup));
    const hasHeaderSuffix = input.hasHeaderSuffix ?? false;

    return {
        titleVisible,
        descriptionVisible,
        headerVisible: titleVisible || descriptionVisible || hasHeaderSuffix,
        // A description forces two lines; otherwise a suffix OR a title is one.
        singleLine: !descriptionVisible && (hasHeaderSuffix || titleVisible),
        listboxVisible: (input.rowCount ?? 0) > 0,
    };
}

// The search corpus

/**
 * One indexable row, as the search reasons about it.
 *
 * `isActionRow` is load-bearing and is NOT "has a subtitle": only
 * `ADW_IS_ACTION_ROW` rows have their subtitle searched,
 * and `AdwEntryRow` derives from
 * `AdwPreferencesRow`, not from `AdwActionRow` — so the
 * text typed into an entry row is deliberately not searchable. Same for
 * `AdwExpanderRow` and `AdwButtonRow`.
 */
export interface PreferencesSearchRow<T = unknown> {
    /** `AdwPreferencesRow:title`. A row with an empty title is not indexed at all. */
    title: string;
    /** `AdwActionRow:subtitle`, consulted only when `isActionRow`. */
    subtitle?: string | null;
    /** `AdwPreferencesRow:use-markup`, default `true`. */
    useMarkup?: boolean;
    /** `AdwPreferencesRow:use-underline`, default `false`. */
    useUnderline?: boolean;
    /** `gtk_widget_get_visible`, default `true`. A hidden row leaves the corpus. */
    visible?: boolean;
    /** Whether the row derives from `AdwActionRow`, default `false`. */
    isActionRow?: boolean;
    /** The renderer's own row object, carried through to the result untouched. */
    ref?: T;
}

/** One group of rows, as the search reasons about it. */
export interface PreferencesSearchGroup<T = unknown> {
    /** `AdwPreferencesGroup:title`; an empty one drops out of the result subtitle. */
    title?: string | null;
    /** `is_visible_group`, default `true`. */
    visible?: boolean;
    /** The group's preferences rows, in listbox order. */
    rows: readonly PreferencesSearchRow<T>[];
    /** The renderer's own group object. */
    ref?: T;
}

/**
 * One page, as the search reasons about it.
 *
 * `visible` is the same flag `ViewStackState.setPageVisible` maintains —
 * the dialog's pages ARE an `AdwViewStack`,
 * so a renderer holds the page ORDER and SELECTION there and describes the
 * same pages here for indexing.
 */
export interface PreferencesSearchPage<T = unknown> {
    /** `AdwPreferencesPage:name`, the view stack child name. */
    name?: string | null;
    /** `AdwPreferencesPage:title`; shown in a result subtitle when several pages are visible. */
    title?: string;
    /** `AdwPreferencesPage:icon-name`. Not read by the search; carried for the switcher. */
    iconName?: string | null;
    /** `AdwPreferencesPage:use-underline`, default `false`. */
    useUnderline?: boolean;
    /** `AdwViewStackPage:visible`, default `true`. An invisible page contributes nothing. */
    visible?: boolean;
    /** `AdwPreferencesPage:description`. Not searched — only rows are. */
    description?: string;
    /** The page's groups, in order. */
    groups: readonly PreferencesSearchGroup<T>[];
    /** The renderer's own page object. */
    ref?: T;
}

/** One row of the corpus, with the ancestors a result subtitle needs. */
export interface PreferencesSearchEntry<T = unknown> {
    page: PreferencesSearchPage<T>;
    group: PreferencesSearchGroup<T>;
    row: PreferencesSearchRow<T>;
}

/**
 * `get_n_pages` — how many pages are visible,
 * which is what decides whether a result subtitle names its page.
 */
export function countVisiblePages<T>(pages: readonly PreferencesSearchPage<T>[]): number {
    let count = 0;
    for (const page of pages) if (page.visible !== false) count += 1;
    return count;
}

/**
 * The search corpus: every row the dialog will ever match against.
 *
 * This is the filter → map → flatten chain of `adw_preferences_dialog_init`
 * composed with `adw_preferences_page_get_rows` and
 * `adw_preferences_group_get_rows`, i.e. THREE filters written in
 * three different C files:
 *
 * 1. visible PAGES only — a `GtkBoolFilter` over `AdwViewStackPage:visible`;
 * 2. visible GROUPS only — `is_visible_group`;
 * 3. rows that are preferences rows AND visible AND have a NON-EMPTY title —
 * `row_has_title`.
 *
 * Filter 3 is the one a port drops, and dropping it is invisible: nothing
 * errors, the search just silently indexes rows a user cannot recognise (an
 * untitled separator row) or, with the visibility half missing, rows that are
 * not on screen. The `ADW_IS_PREFERENCES_ROW` half of it is expressed
 * statically here — a `PreferencesSearchRow[]` cannot hold a plain list-box row.
 */
export function collectSearchRows<T>(pages: readonly PreferencesSearchPage<T>[]): PreferencesSearchEntry<T>[] {
    const entries: PreferencesSearchEntry<T>[] = [];

    for (const page of pages) {
        if (page.visible === false) continue;
        for (const group of page.groups) {
            if (group.visible === false) continue;
            for (const row of group.rows) {
                if (row.visible === false) continue;
                if (row.title === '') continue;
                entries.push({ page, group, row });
            }
        }
    }

    return entries;
}

/**
 * `filter_search_results`: whether a row
 * matches the current search terms.
 *
 * Three properties a port tends to get wrong, all of them user-visible:
 *
 * - it is a SUBSTRING test (`strstr`), not a prefix and not word-boundary —
 * `ARK` matches `Dark Style`;
 * - the EMPTY query matches everything (`strstr (title, "")` returns `title`),
 * which is why the dialog shows "results" and not "no results" before the
 * user has typed anything;
 * - the query is only case-FOLDED. It is not markup-parsed and not
 * mnemonic-stripped, so typing `_` searches for a literal underscore.
 */
export function rowMatchesQuery<T>(
    row: PreferencesSearchRow<T>,
    query: string,
    fold: CaseFolder = defaultCaseFolder,
): boolean {
    const terms = fold(query ?? '');
    const flags = { useMarkup: row.useMarkup, useUnderline: row.useUnderline };

    if (makeComparable(row.title, { ...flags, allowUnderline: true }, fold).includes(terms)) return true;
    if (!row.isActionRow) return false;

    return makeComparable(row.subtitle, { ...flags, allowUnderline: false }, fold).includes(terms);
}

/**
 * The translated fallback for a page with no title.
 * Exported so a renderer with a translation
 * catalogue can pass its own through `untitledPageLabel`.
 */
export const UNTITLED_PAGE_LABEL = 'Untitled page';

/** The `page → group` separator: U+2192, one space either side. */
const SUBTITLE_ARROW = '→';

/** What {@link createSearchRowSubtitle} needs about a matched row's ancestors. */
export interface SearchRowSubtitleInput {
    /** The group's title. `''` counts as absent. */
    groupTitle?: string | null;
    /**
     * The page's title. `undefined` means there is no page ancestor at all —
     * unreachable through the public API, since a row always sits in a page.
     */
    pageTitle?: string | null;
    /** `AdwPreferencesPage:use-underline` — decides whether the page title is mnemonic-stripped. */
    pageUseUnderline?: boolean;
    /** The matched ROW's `use-markup` — decides whether the page title is markup-escaped. Default `true`. */
    rowUseMarkup?: boolean;
    /** `get_n_pages` — the page is only named when more than one page is visible. */
    nVisiblePages: number;
    /** Override for {@link UNTITLED_PAGE_LABEL}. */
    untitledPageLabel?: string;
}

/**
 * `create_search_row_subtitle` — the second
 * line of a search result, e.g. `General → Appearance`.
 *
 * The rules, in the order the C applies them, none of them symmetric:
 *
 * - an empty GROUP title becomes "absent", and the whole `page → group` join
 * is then skipped — the result falls through to the bare page title;
 * - the PAGE title is mnemonic-stripped when the PAGE uses underline, then
 * markup-escaped when the ROW uses markup (a page-level property and a
 * row-level property deciding two steps on the same string), and only then
 * tested for emptiness;
 * - the join happens only when more than one page is VISIBLE; with a single
 * page the subtitle is the group title alone;
 * - the group title is NOT escaped, so the two halves of `page → group` are
 * escaped differently on purpose.
 *
 * `null` means "no subtitle at all", which is what a renderer should render as
 * an absent line rather than as an empty one.
 */
export function createSearchRowSubtitle(input: SearchRowSubtitleInput): string | null {
    let groupTitle: string | null = input.groupTitle ?? null;
    if (groupTitle === '') groupTitle = null;

    let pageTitle: string | null = null;
    if (input.pageTitle !== undefined && input.pageTitle !== null) {
        pageTitle = input.pageUseUnderline ? stripMnemonic(input.pageTitle) : input.pageTitle;
        if (input.rowUseMarkup ?? true) pageTitle = escapeMarkup(pageTitle);
        if (pageTitle === '') pageTitle = null;
    }

    if (groupTitle === null) return pageTitle;
    if (input.nVisiblePages <= 1) return groupTitle;

    const effectivePageTitle = pageTitle ?? input.untitledPageLabel ?? UNTITLED_PAGE_LABEL;
    return `${effectivePageTitle} ${SUBTITLE_ARROW} ${groupTitle}`;
}

/** One row of the search results list. */
export interface PreferencesSearchResult<T = unknown> {
    /** Copied verbatim from the matched row (`new_search_row_for_preference`). */
    title: string;
    /** {@link createSearchRowSubtitle}; `null` when there is nothing to show. */
    subtitle: string | null;
    /** The matched row's `use-markup`, copied onto the result row. */
    useMarkup: boolean;
    /** The matched row's `use-underline`, copied onto the result row. */
    useUnderline: boolean;
    /** The page the row lives on — what `search_result_activated_cb` switches to. */
    page: PreferencesSearchPage<T>;
    /** The group the row lives in. */
    group: PreferencesSearchGroup<T>;
    /** The matched row — what `search_result_activated_cb` focuses. */
    row: PreferencesSearchRow<T>;
}

/** Knobs for {@link searchPreferences}. */
export interface SearchPreferencesOptions {
    /** Case folder to compare with. Defaults to {@link defaultCaseFolder}. */
    fold?: CaseFolder;
    /** Translated replacement for {@link UNTITLED_PAGE_LABEL}. */
    untitledPageLabel?: string;
}

/**
 * The whole search half in one call: corpus → filter → result rows, in corpus
 * order (which is page order, then group order, then row order — the same order
 * `GtkFlattenListModel` produces).
 *
 * Each result carries the source `page`/`group`/`row` so a renderer can
 * implement `search_result_activated_cb` —
 * switch the visible page, focus the row — without re-deriving anything.
 */
export function searchPreferences<T>(
    pages: readonly PreferencesSearchPage<T>[],
    query: string,
    options: SearchPreferencesOptions = {},
): PreferencesSearchResult<T>[] {
    const fold = options.fold ?? defaultCaseFolder;
    const nVisiblePages = countVisiblePages(pages);
    const results: PreferencesSearchResult<T>[] = [];

    for (const { page, group, row } of collectSearchRows(pages)) {
        if (!rowMatchesQuery(row, query, fold)) continue;

        results.push({
            title: row.title,
            subtitle: createSearchRowSubtitle({
                groupTitle: group.title,
                // A row always has a page ancestor, so an absent title is an
                // EMPTY one, not a missing page.
                pageTitle: page.title ?? '',
                pageUseUnderline: page.useUnderline,
                rowUseMarkup: row.useMarkup,
                nVisiblePages,
                untitledPageLabel: options.untitledPageLabel,
            }),
            useMarkup: row.useMarkup ?? true,
            useUnderline: row.useUnderline ?? false,
            page,
            group,
            row,
        });
    }

    return results;
}

// Re-exported so existing importers keep working; it lives in `glib.ts`
// because the view switcher needs the same rule.
export { stripMnemonic };
