// AUTO-GENERATED by scripts/generate-adwaita-tokens.mjs. DO NOT EDIT BY HAND.
//
// Source: packages/web/adwaita-web/scss/_variables.scss (`light-theme`) and
// _theme.scss (`dark-theme`). ADR 0010 decision 2: these custom properties ARE
// the public theming contract of `@gjsify/adwaita-web`.

/** One token's declared values. `dark` is absent when the dark theme keeps the default. */
export interface AdwTokenValues {
    readonly light: string;
    readonly dark?: string;
}

/**
 * Every declared Adwaita token, light and dark.
 *
 * The VALUES as the stylesheet writes them — including the expressions listed in
 * {@link ADWAITA_UNRESOLVED_TOKENS}. Nothing here is evaluated.
 */
export const ADWAITA_TOKENS: Readonly<Record<string, AdwTokenValues>> = {
    '--window-bg-color': {
        light: '#fafafb',
        dark: '#222226',
    },
    '--window-fg-color': {
        light: 'rgba(0, 0, 6, 0.8)',
        dark: '#ffffff',
    },
    '--view-bg-color': {
        light: '#ffffff',
        dark: '#1d1d20',
    },
    '--view-fg-color': {
        light: 'rgba(0, 0, 6, 0.8)',
        dark: '#ffffff',
    },
    '--headerbar-bg-color': {
        light: '#ffffff',
        dark: '#2e2e32',
    },
    '--headerbar-fg-color': {
        light: 'rgba(0, 0, 6, 0.8)',
        dark: '#ffffff',
    },
    '--headerbar-shade-color': {
        light: 'rgba(0, 0, 6, 0.12)',
        dark: 'rgba(0, 0, 6, 0.36)',
    },
    '--separator-color': {
        light: 'rgba(0, 0, 6, 0.1)',
        dark: 'rgba(255, 255, 255, 0.08)',
    },
    '--shade-color': {
        light: 'rgba(0, 0, 6, 0.07)',
        dark: 'rgba(0, 0, 6, 0.25)',
    },
    '--sidebar-bg-color': {
        light: '#ebebed',
        dark: '#2e2e32',
    },
    '--sidebar-fg-color': {
        light: 'rgba(0, 0, 6, 0.8)',
        dark: '#ffffff',
    },
    '--sidebar-backdrop-color': {
        light: '#f2f2f4',
        dark: '#28282c',
    },
    '--sidebar-shade-color': {
        light: 'rgba(0, 0, 6, 0.07)',
        dark: 'rgba(0, 0, 6, 0.25)',
    },
    '--sidebar-border-color': {
        light: 'rgba(0, 0, 6, 0.07)',
        dark: 'rgba(0, 0, 6, 0.36)',
    },
    '--secondary-sidebar-bg-color': {
        light: '#f3f3f5',
        dark: '#28282c',
    },
    '--secondary-sidebar-fg-color': {
        light: 'rgba(0, 0, 6, 0.8)',
        dark: '#ffffff',
    },
    '--secondary-sidebar-backdrop-color': {
        light: '#f6f6fa',
        dark: '#252529',
    },
    '--secondary-sidebar-shade-color': {
        light: 'rgba(0, 0, 6, 0.07)',
        dark: 'rgba(0, 0, 6, 0.25)',
    },
    '--secondary-sidebar-border-color': {
        light: 'rgba(0, 0, 6, 0.07)',
        dark: 'rgba(0, 0, 6, 0.36)',
    },
    '--card-bg-color': {
        light: '#ffffff',
        dark: 'rgba(255, 255, 255, 0.08)',
    },
    '--card-fg-color': {
        light: 'rgba(0, 0, 6, 0.8)',
        dark: '#ffffff',
    },
    '--card-shade-color': {
        light: 'rgba(0, 0, 6, 0.07)',
        dark: 'rgba(0, 0, 6, 0.36)',
    },
    '--accent-bg-color': {
        light: '#3584e4',
    },
    '--accent-fg-color': {
        light: '#ffffff',
    },
    '--accent-color': {
        light: '#1c71d8',
        dark: '#78aeed',
    },
    '--popover-bg-color': {
        light: '#ffffff',
        dark: '#36363a',
    },
    '--popover-fg-color': {
        light: 'rgba(0, 0, 6, 0.8)',
        dark: '#ffffff',
    },
    '--popover-shade-color': {
        light: 'rgba(0, 0, 6, 0.07)',
        dark: 'rgba(0, 0, 6, 0.36)',
    },
    '--dialog-scrim-color': {
        light: 'rgba(0, 0, 6, 0.32)',
        dark: 'rgba(0, 0, 6, 0.55)',
    },
    '--button-bg-color': {
        light: 'rgba(0, 0, 6, 0.08)',
        dark: 'rgba(255, 255, 255, 0.1)',
    },
    '--button-hover-color': {
        light: 'rgba(0, 0, 6, 0.13)',
        dark: 'rgba(255, 255, 255, 0.15)',
    },
    '--button-active-color': {
        light: 'rgba(0, 0, 6, 0.19)',
        dark: 'rgba(255, 255, 255, 0.22)',
    },
    '--entry-bg-color': {
        light: '#ffffff',
        dark: 'rgba(255, 255, 255, 0.06)',
    },
    '--entry-border-color': {
        light: 'rgba(0, 0, 6, 0.18)',
        dark: 'rgba(255, 255, 255, 0.16)',
    },
    '--entry-border-hover-color': {
        light: 'rgba(0, 0, 6, 0.28)',
        dark: 'rgba(255, 255, 255, 0.26)',
    },
    '--destructive-bg-color': {
        light: '#e01b24',
        dark: '#c01c28',
    },
    '--destructive-fg-color': {
        light: '#ffffff',
    },
    '--success-bg-color': {
        light: '#2ec27e',
        dark: '#26a269',
    },
    '--success-fg-color': {
        light: '#ffffff',
    },
    '--success-color': {
        light: 'oklab(from var(--success-bg-color) min(l, 0.5) a b)',
        dark: 'oklab(from var(--success-bg-color) max(l, 0.85) a b)',
    },
    '--warning-bg-color': {
        light: '#e5a50a',
        dark: '#cd9309',
    },
    '--warning-fg-color': {
        light: 'rgba(0, 0, 0, 0.8)',
    },
    '--warning-color': {
        light: 'oklab(from var(--warning-bg-color) min(l, 0.5) a b)',
        dark: 'oklab(from var(--warning-bg-color) max(l, 0.85) a b)',
    },
    '--error-bg-color': {
        light: '#e01b24',
        dark: '#c01c28',
    },
    '--error-fg-color': {
        light: '#ffffff',
    },
    '--error-color': {
        light: 'oklab(from var(--error-bg-color) min(l, 0.5) a b)',
        dark: 'oklab(from var(--error-bg-color) max(l, 0.85) a b)',
    },
    '--switch-off-bg': {
        light: 'rgba(0, 0, 0, 0.2)',
        dark: 'rgba(255, 255, 255, 0.2)',
    },
    '--switch-knob-bg': {
        light: '#ffffff',
        dark: '#deddda',
    },
    '--window-radius': {
        light: '15px',
    },
    '--card-radius': {
        light: '12px',
    },
    '--button-radius': {
        light: '9px',
    },
    '--spacing-xs': {
        light: '6px',
    },
    '--spacing-s': {
        light: '9px',
    },
    '--spacing-m': {
        light: '12px',
    },
    '--spacing-l': {
        light: '18px',
    },
    '--spacing-xl': {
        light: '24px',
    },
    '--font-family': {
        light: "'Adwaita Sans', 'Cantarell', 'Inter', 'Segoe UI', sans-serif",
    },
    '--font-size-base': {
        light: '11pt',
    },
    '--font-size-small': {
        light: '9pt',
    },
    '--font-size-heading': {
        light: '12pt',
    },
    '--dim-opacity': {
        light: '0.55',
    },
    '--border-opacity': {
        light: '15%',
    },
    '--border-color': {
        light: 'color-mix(in srgb, currentColor var(--border-opacity), transparent)',
    },
    '--disabled-opacity': {
        light: '0.5',
    },
    '--document-font-family': {
        light: 'var(--font-family)',
    },
    '--document-font-size': {
        light: 'var(--font-size-base)',
    },
    '--monospace-font-family': {
        light: "'Adwaita Mono', ui-monospace, 'SF Mono', 'Menlo', monospace",
    },
    '--monospace-font-size': {
        light: 'var(--font-size-base)',
    },
};

/**
 * Tokens the dark theme declares and the light theme does not.
 *
 * Visible rather than merged away: a consumer reading only `light` would otherwise
 * miss them with no signal.
 */
export const ADWAITA_DARK_ONLY_TOKENS: readonly string[] = ['--active-toggle-fg-color'];

/**
 * Tokens whose value is a CSS expression, not a literal.
 *
 * `oklab(from …)` and `color-mix(…)` are deliberate: they track a re-themed base
 * colour, which a literal cannot. A browser evaluates them. A TypeScript scale and
 * NativeScript's CSS subset cannot — so a consumer that needs literals must refuse
 * these by name instead of passing the expression through as a colour.
 *
 * `--border-color` is the hard case and is in this list for a different reason:
 * `currentColor` is a value of the cascade at paint time, so it has no build-time
 * resolution at all, in any target.
 */
export const ADWAITA_UNRESOLVED_TOKENS: readonly string[] = [
    '--border-color',
    '--document-font-family',
    '--document-font-size',
    '--error-color',
    '--monospace-font-size',
    '--success-color',
    '--warning-color',
];

/** How many tokens the light contract carries — derived, never typed. */
export const ADWAITA_TOKEN_COUNT = 68;
