#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Regenerate src/cc/stubs.cc — the loud-stub remainder of the Node-API ABI.

Preprocesses the vendored headers (NAPI_VERSION=10, non-experimental),
extracts every declared `napi_status`-returning `napi_*`/`node_api_*`
function, subtracts the set already implemented in src/cc/*.cc (detected by
their `NAPI_CDECL name(` definitions), and emits exact-signature stubs that
return napi_generic_failure + set last_error.

Run from the package root after implementing a new ABI function:

    python3 scripts/gen-stubs.py

The checked-in stubs.cc is the artifact; a function implemented but not
removed here fails the link with a duplicate-symbol error (the guard).
"""

import glob
import re
import subprocess
import sys
import tempfile
from pathlib import Path

PKG = Path(__file__).resolve().parent.parent
HEADERS = PKG / "src" / "napi-headers"
OUT = PKG / "src" / "cc" / "stubs.cc"

DECL_RE = re.compile(
    r"\bnapi_status\s+((?:napi|node_api)_[a-z0-9_]+)\s*\(([^;{)]*(?:\([^)]*\)[^;{)]*)*)\)\s*;"
)
IMPL_RE = re.compile(r"NAPI_CDECL\s+((?:napi|node_api)_[a-z0-9_]+)\s*\(")


def preprocess() -> str:
    with tempfile.NamedTemporaryFile("w", suffix=".c", delete=False) as tu:
        tu.write('#define NAPI_VERSION 10\n#include "js_native_api.h"\n#include "node_api.h"\n')
        tu_path = tu.name
    out = subprocess.run(
        ["gcc", "-E", "-P", "-I", str(HEADERS), tu_path],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    flat = re.sub(r"\s+", " ", out)
    flat = flat.replace('__attribute__((visibility("default")))', " ")
    return flat.replace("__attribute__((noreturn))", " ")


def implemented() -> set[str]:
    names: set[str] = set()
    for path in glob.glob(str(PKG / "src" / "cc" / "*.cc")):
        if Path(path).name == "stubs.cc":
            continue
        names.update(IMPL_RE.findall(Path(path).read_text()))
    return names


def emit_stub(name: str, params: str) -> str:
    parts = [p.strip() for p in params.split(",")] if params.strip() else []
    if not parts or parts == ["void"]:
        raise SystemExit(f"unexpected zero-arg ABI function: {name}")
    has_env = bool(re.search(r"\benv$", parts[0]))
    lines = [f"napi_status NAPI_CDECL {name}({', '.join(parts)}) {{"]
    for p in parts[1:] if has_env else parts:
        pm = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*$", p)
        if not pm:
            raise SystemExit(f"cannot find parameter name in {name}: {p!r}")
        lines.append(f"    (void){pm.group(1)};")
    if has_env:
        lines.append("    GJSIFY_NAPI_STUB(env);")
    else:
        # Env-less (threadsafe-function handle entry points): no last_error
        # slot reachable — just fail loud.
        lines.append("    return napi_generic_failure;")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    flat = preprocess()
    impl = implemented()
    seen: set[str] = set()
    stubs: list[str] = []
    declared: set[str] = set()
    for m in DECL_RE.finditer(flat):
        name = m.group(1)
        declared.add(name)
        if name in seen or name in impl:
            seen.add(name)
            continue
        seen.add(name)
        stubs.append(emit_stub(name, m.group(2)))

    missing = impl - declared
    # Expected: void-returning ABI entries (napi_module_register,
    # napi_fatal_error) are not napi_status declarations, and
    # node_api_post_finalizer is NAPI_EXPERIMENTAL-gated in the headers but a
    # stable exported symbol in Node — we implement + export it regardless.
    missing = {
        n
        for n in missing
        if n
        not in {"napi_module_register", "napi_fatal_error",
                "node_api_post_finalizer"}
    }
    if missing:
        raise SystemExit(f"implemented but not declared by the headers: {sorted(missing)}")

    header = f"""// SPDX-License-Identifier: MIT
// @gjsify/napi — loud stubs for the not-yet-implemented Node-API surface.
//
// GENERATED by scripts/gen-stubs.py (checked in; regenerate after
// implementing a new ABI function — a newly implemented function that stays
// listed here fails the link with a duplicate-symbol error, the guard).
//
// Every declared `napi_*`/`node_api_*` symbol of the vendored headers
// (NAPI_VERSION=10, non-experimental) is DEFINED and exported, so an addon's
// undefined symbols always bind at dlopen (RTLD_NOW) — reaching past the
// implemented surface fails loud with napi_generic_failure + last_error
// (plan section 2 posture), never with an unresolved-symbol load failure and
// never with a crash. {len(stubs)} stubs.

#include "common.h"

// env may be napi_env or node_api_basic_env — identical underlying type in
// the non-experimental configuration (js_native_api_types.h:74-81).
#define GJSIFY_NAPI_STUB(env)                                                 \\
    do {{                                                                      \\
        GJSIFY_NAPI_CHECK_ENV(env);                                           \\
        return gjsify_napi::set_last_error(                                   \\
            const_cast<napi_env>(env), napi_generic_failure);                 \\
    }} while (0)

"""
    OUT.write_text(header + "\n\n".join(stubs) + "\n")
    print(f"wrote {len(stubs)} stubs ({len(impl)} implemented, {len(declared)} declared) to {OUT}")


if __name__ == "__main__":
    sys.exit(main())
