// Iterative multi-pass build orchestrator for `--globals auto`. The "analyse the
// bundled output AFTER tree-shaking" property is bundler-agnostic and load-bearing —
// AGENTS.md § "Tree-shakeability invariants — permanent", plus the rationale block
// atop `detect-free-globals.ts`.
//
// Pass 1: bundle with no globals injection → parsed by acorn for free globals.
// Pass 2: bundle with the detected globals injected → the injected register modules
//         pull in MORE code referencing more globals (a tree-shaking dependency
//         cycle), so the set can still grow.
// Pass N: repeat until it converges, capped at MAX_ITERATIONS.
//
// The analysis builds MUST NOT minify: minification aliases `globalThis` to a short
// variable and defeats MemberExpression detection in detect-free-globals.ts.

import type { InputOptions, RolldownPluginOption, TransformOptions } from 'rolldown';
import type * as Rolldown from 'rolldown';

/**
 * In-memory bundle function returning the per-entry chunk code strings, injected so
 * auto-globals runs under either engine: npm rolldown cannot load under GJS (its Rust
 * prebuild's init code calls `require('node:fs')` synchronously). The default impl
 * dynamically imports npm rolldown; the CLI overrides it from `actions/build.ts` to
 * route via the same engine the final build uses.
 */
export type AnalysisBundler = (input: {
    rolldownInput: InputOptions;
    format: 'esm' | 'cjs' | 'iife';
}) => Promise<string[]>;

const defaultBundler: AnalysisBundler = async ({ rolldownInput, format }) => {
    // Indirect specifier so the GJS bundle doesn't pull npm rolldown in
    // statically. Only reached when the caller doesn't override (Node).
    const specifier = 'rolldown';
    const mod = (await import(/* @vite-ignore */ specifier)) as typeof Rolldown;
    const build = await mod.rolldown(rolldownInput);
    try {
        const result = await build.generate({ format, minify: false, sourcemap: false });
        const codes: string[] = [];
        for (const entry of result.output) {
            if (entry.type === 'chunk') codes.push(entry.code);
        }
        return codes;
    } finally {
        await build.close();
    }
};
import { detectFreeGlobals, detectGjsAmbientGlobals, detectNodeGiModuleImports } from './detect-free-globals.js';
import {
    resolveGlobalsList,
    writeRegisterInjectFile,
    filterResolvableRegisterPaths,
    isRegisterPathResolvable,
} from './scan-globals.js';
import { GJS_GLOBALS_MAP, GJS_GI_BACKED_REGISTERS } from '@gjsify/resolve-npm/globals-map';
import { REGISTER_GLOBALS_CLOSURE } from '@gjsify/resolve-npm/register-globals-closure';
import type { PluginOptions } from '../types/plugin-options.js';

const GLOBALS_MAP: Record<string, string> = GJS_GLOBALS_MAP;
const CLOSURE_MAP: Record<string, readonly string[]> = REGISTER_GLOBALS_CLOSURE;
const GI_BACKED: Record<string, readonly string[]> = GJS_GI_BACKED_REGISTERS;

/** Maximum iterations to prevent runaway loops on pathological inputs. */
const MAX_ITERATIONS = 5;

/**
 * Expand a detected-identifier set with the PRECOMPUTED transitive closure of the
 * register modules those identifiers inject (`register-globals-closure`, generated by
 * `packages/infra/cli/scripts/generate-register-closure.mjs`).
 *
 * Passes 2..N of the plain loop exist only to discover which ADDITIONAL globals the
 * injected registers' own code references — static, per-register information. Seeding
 * pass 2 with the full closure makes the loop converge at the next (verification)
 * pass, collapsing ~3-5 analysis bundles to 2. A stale or missing entry is SAFE: the
 * verification pass sees the unexpected growth and the loop keeps iterating, slower,
 * with a hint to regenerate.
 */
function expandWithClosure(detected: Set<string>, excludeSet: Set<string>): Set<string> {
    const out = new Set(detected);
    const queue = [...detected];
    while (queue.length > 0) {
        const id = queue.pop() as string;
        const registerPath = GLOBALS_MAP[id];
        if (!registerPath) continue;
        const entry = CLOSURE_MAP[registerPath];
        if (!entry) continue; // unknown register — the iterative loop covers it
        for (const cid of entry) {
            if (excludeSet.has(cid)) continue;
            if (!GLOBALS_MAP[cid]) continue;
            if (!out.has(cid)) {
                out.add(cid);
                queue.push(cid);
            }
        }
    }
    return out;
}

function isSubset(a: Set<string>, b: Set<string>): boolean {
    for (const x of a) if (!b.has(x)) return false;
    return true;
}

export interface AutoGlobalsResult {
    detected: Set<string>;
    /** Path to the generated inject stub; undefined when no globals are needed. */
    injectPath: string | undefined;
}

async function applyExcludeGlobals(
    detected: Set<string>,
    currentInject: string | undefined,
    extraRegisterPaths: Set<string>,
    excludeGlobals: string[] | undefined,
    cwd?: string,
): Promise<AutoGlobalsResult> {
    if (excludeGlobals?.length) {
        for (const id of excludeGlobals) detected.delete(id);
    }

    // Computed for BOTH paths so the GI-backed diagnostic fires whether or not
    // excludeGlobals is set.
    const finalPaths = detectedToRegisterPaths(detected);
    for (const p of extraRegisterPaths) finalPaths.add(p);
    emitGiBackedDiagnostic(finalPaths, detected, cwd);

    // No exclude: `currentInject` already reflects `finalPaths`, so reuse it —
    // re-running filterResolvableRegisterPaths would repeat its skip warnings.
    if (!excludeGlobals?.length) return { detected, injectPath: currentInject };

    const filtered = cwd ? filterResolvableRegisterPaths(finalPaths, cwd) : finalPaths;
    const injectPath = filtered.size > 0 ? ((await writeRegisterInjectFile(filtered, cwd)) ?? undefined) : undefined;
    return { detected, injectPath };
}

function detectedToRegisterPaths(detected: Set<string>): Set<string> {
    const paths = new Set<string>();
    for (const name of detected) {
        const path = GLOBALS_MAP[name];
        if (path) paths.add(path);
    }
    return paths;
}

/**
 * GI namespaces a register path pulls at import, or null when it is not
 * GI-backed. Prefix match against `GJS_GI_BACKED_REGISTERS` so one entry per
 * package covers every granular subpath (`…/register/document`, `…/register/canvas`).
 */
function giNamespacesForRegister(registerPath: string): readonly string[] | null {
    for (const prefix of Object.keys(GI_BACKED)) {
        if (registerPath === prefix || registerPath.startsWith(prefix + '/')) {
            return GI_BACKED[prefix];
        }
    }
    return null;
}

/**
 * The build-time note for any GI-backed register modules in a final inject set, or
 * null when none are. Pure so it is unit-testable; `emitGiBackedDiagnostic` is the
 * side-effecting wrapper.
 *
 * Injecting a GI-backed register makes the bundle hard-require a GTK/GNOME runtime at
 * load, so under a GTK-less host (headless type-check container, SSR generator, plain
 * CI) it throws `Typelib … not found`. Naming the triggering globals makes that
 * otherwise-silent runtime crash traceable at build time.
 */
export function describeGiBackedInjection(registerPaths: Set<string>, detected: Set<string>): string | null {
    const giRegisters = new Set<string>();
    const namespaces = new Set<string>();
    for (const path of registerPaths) {
        const gi = giNamespacesForRegister(path);
        if (!gi) continue;
        giRegisters.add(path);
        for (const ns of gi) namespaces.add(ns);
    }
    if (giRegisters.size === 0) return null;

    const triggers = [...detected]
        .filter((id) => {
            const p = GLOBALS_MAP[id];
            return !!p && giRegisters.has(p);
        })
        .sort();
    const giList = [...namespaces]
        .sort()
        .map((n) => `gi://${n}`)
        .join(', ');

    return (
        '[gjsify] note: --globals auto injected GTK/GNOME-backed register(s) — this bundle now requires ' +
        `${giList} at load.` +
        (triggers.length ? ` Triggered by: ${triggers.join(', ')}.` : '') +
        ' If it runs headless / SSR / in a GTK-less container it will throw "Typelib … not found"; drop those ' +
        'globals via excludeGlobals or pin an explicit --globals allowlist (e.g. node).'
    );
}

/** Emitted at most once per process so multi-pass / multi-build runs stay quiet. */
let giNoteEmitted = false;

/**
 * Warn the GI-backed-injection note once per process. Pre-filters `registerPaths` to
 * the ones that will ACTUALLY be injected so the note never mentions a dropped
 * register, via `isRegisterPathResolvable` rather than
 * `filterResolvableRegisterPaths` to avoid duplicating that one's skip warnings.
 */
function emitGiBackedDiagnostic(registerPaths: Set<string>, detected: Set<string>, cwd?: string): void {
    if (giNoteEmitted) return;
    const candidates = new Set<string>();
    for (const path of registerPaths) {
        if (!giNamespacesForRegister(path)) continue;
        if (cwd && !isRegisterPathResolvable(path, cwd)) continue;
        candidates.add(path);
    }
    const note = describeGiBackedInjection(candidates, detected);
    if (!note) return;
    giNoteEmitted = true;
    console.warn(note);
}

export interface DetectAutoGlobalsOptions {
    /**
     * Identifiers or group aliases (`dom`/`web`/`node`) always injected on top of what
     * detection finds — `--globals auto,<extras>`, for globals reached through
     * indirection the detector cannot follow statically (Excalibur's
     * `BrowserComponent.nativeComponent.matchMedia`).
     */
    extraGlobalsList?: string;
    /**
     * Identifiers to remove before writing the inject stub — for false positives from
     * dead browser-compat code in deps whose polyfills need unavailable native libs.
     */
    excludeGlobals?: string[];
    /**
     * Skip the closure-map expansion and run the pure iterative loop. Only the
     * closure-map GENERATOR sets this: computing a register's closure THROUGH the
     * committed map would re-add every identifier the OLD entry contained, so removed
     * globals could never leave it (a ratchet, with transitive pollution into sibling
     * entries) and `--check` would stay green on semantically stale data.
     */
    disableClosureExpansion?: boolean;
    /**
     * Project root, used to locate `node_modules` when checking whether a detected
     * global's polyfill package is installed. Omitting it BYPASSES that resolvability
     * gate (every detected register path is written as-is); the real CLI build passes
     * `process.cwd()`.
     */
    cwd?: string;
}

/**
 * Build options for the analyser: the same input options the caller would use for the
 * final build, with the output-side fields that force a write-to-disk stripped and
 * replaced by in-memory settings.
 */
export interface AnalysisOptions {
    input: InputOptions['input'];
    plugins?: RolldownPluginOption[];
    external?: InputOptions['external'];
    resolve?: InputOptions['resolve'];
    /** Pass-through to Rolldown's Oxc-driven `transform` (`define`, `treeShake`, …). */
    transform?: TransformOptions;
    /** Use 'esm' to match the final build. */
    format?: 'esm' | 'cjs' | 'iife';
}

/**
 * Supplies the gjsify plugin to the analyser; passed in by the caller to break the
 * cyclic dep between this file and `../plugin.ts`. Returns either the plugin array
 * alone or the full orchestrator config `{ options, plugins }` — the latter lets the
 * analysis bundle reuse the orchestrator's `resolve.conditionNames`/`mainFields`/
 * `external`/`treeshake`, without which native-rolldown and npm-rolldown default to
 * different module-resolution conditions and the detected free-global set diverges
 * between engines.
 */
type GjsifyFactoryReturn = RolldownPluginOption | { options: InputOptions; plugins: RolldownPluginOption[] };

type GjsifyPluginFactory = (options: PluginOptions) => GjsifyFactoryReturn | Promise<GjsifyFactoryReturn>;

function isFullConfig(v: GjsifyFactoryReturn): v is { options: InputOptions; plugins: RolldownPluginOption[] } {
    return v !== null && typeof v === 'object' && !Array.isArray(v) && 'plugins' in v && 'options' in v;
}

/**
 * Run the iterative in-memory build with acorn-based global detection, each pass
 * seeded by the previous pass's globals, until the detected set is stable. Returns the
 * inject stub path the caller passes to the final build via
 * `pluginOptions.autoGlobalsInject`.
 */
export async function detectAutoGlobals(
    analysisOptions: AnalysisOptions,
    pluginOptions: Omit<PluginOptions, 'autoGlobalsInject'>,
    gjsifyPluginFactory: GjsifyPluginFactory,
    verbose?: boolean,
    options: DetectAutoGlobalsOptions = {},
    bundler: AnalysisBundler = defaultBundler,
): Promise<AutoGlobalsResult> {
    const extraRegisterPaths = options.extraGlobalsList
        ? resolveGlobalsList(options.extraGlobalsList)
        : new Set<string>();

    const excludeSet = new Set(options.excludeGlobals ?? []);
    const cwd = options.cwd;

    let detected = new Set<string>();
    let currentInject: string | undefined = undefined;

    if (extraRegisterPaths.size > 0) {
        const resolvableExtra = cwd ? filterResolvableRegisterPaths(extraRegisterPaths, cwd) : extraRegisterPaths;
        currentInject = (await writeRegisterInjectFile(resolvableExtra, cwd)) ?? undefined;
    }

    // Caller plugins (e.g. the PnP relay) survive every pass; the gjsify plugin is
    // appended last so its hooks run after any custom resolvers / loaders.
    const callerPlugins = (analysisOptions.plugins ?? []).filter((p) => {
        const name = p && typeof p === 'object' && 'name' in p ? p.name : undefined;
        return name !== 'gjsify' && name !== 'gjsify-orchestrator';
    });

    for (let iteration = 1; iteration <= MAX_ITERATIONS; iteration++) {
        const factoryResult = await gjsifyPluginFactory({
            ...pluginOptions,
            autoGlobalsInject: currentInject,
        } as PluginOptions);

        let gjsifyInstance: RolldownPluginOption;
        let orchestratorOptions: InputOptions | undefined;
        if (isFullConfig(factoryResult)) {
            orchestratorOptions = factoryResult.options;
            gjsifyInstance = factoryResult.plugins as unknown as RolldownPluginOption;
        } else {
            gjsifyInstance = factoryResult;
        }

        // The inject stub is a side-effect-only ESM file importing
        // `<pkg>/register/<feature>` paths, appended as an ADDITIONAL ENTRY so Rolldown
        // bundles its side effects and the detector sees the resulting references.
        // Rolldown's `transform.inject` is the source-AST per-identifier rewrite the
        // tree-shakeability invariants forbid.
        const inputWithInject = currentInject
            ? appendInjectAsEntry(analysisOptions.input, currentInject)
            : analysisOptions.input;

        // Take resolve/external/transform from the orchestrator so the analysis bundle
        // goes through the same module resolution as the final build; explicit
        // analysis-side overrides win.
        const mergedResolve = analysisOptions.resolve ?? orchestratorOptions?.resolve;
        const mergedExternal = analysisOptions.external ?? orchestratorOptions?.external;
        const mergedTransform = analysisOptions.transform ?? orchestratorOptions?.transform;
        const orchTreeshake = (orchestratorOptions as { treeshake?: unknown } | undefined)?.treeshake;

        const gjsifyPluginsArray = Array.isArray(gjsifyInstance) ? gjsifyInstance : [gjsifyInstance];

        const chunkCodes = await bundler({
            rolldownInput: {
                input: inputWithInject,
                external: mergedExternal,
                resolve: mergedResolve,
                transform: mergedTransform,
                plugins: [...callerPlugins, ...gjsifyPluginsArray],
                logLevel: 'silent',
                ...(orchTreeshake !== undefined ? { treeshake: orchTreeshake } : {}),
            } as InputOptions,
            format: analysisOptions.format ?? 'esm',
        });

        if (chunkCodes.length === 0) {
            return { detected: new Set(), injectPath: currentInject };
        }

        // Per-chunk parse, then union: Rolldown emits one chunk per entry, and
        // concatenating them yields duplicate top-level declarations (`File`,
        // `Buffer`, …) that acorn rejects as an invalid program.
        const newDetected = new Set<string>();
        for (let i = 0; i < chunkCodes.length; i++) {
            const code = chunkCodes[i] ?? '';
            try {
                for (const id of detectFreeGlobals(code)) newDetected.add(id);
            } catch (e) {
                if (
                    (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env
                        ?.GJSIFY_DEBUG_AUTO_GLOBALS
                ) {
                    // `tmpdir()`, not a literal `/tmp`: on Windows that wrote to
                    // `<drive>:\tmp\`, and since the `writeFileSync` sits inside a
                    // `catch` the dump silently did not appear where the log line
                    // below says it did.
                    const os = await import('node:os');
                    const nodePath = await import('node:path');
                    const path = nodePath.join(os.tmpdir(), `gjsify-auto-globals-failed-chunk-${i}.mjs`);
                    try {
                        // Dynamic `import()` so this debug-only branch keeps `node:fs`
                        // out of the module graph.
                        const fs = await import('node:fs');
                        fs.writeFileSync(path, code);
                        console.error(
                            `[gjsify-auto-globals] parse failed on chunk #${i} — wrote ${path} for inspection`,
                        );
                    } catch {
                        // Swallowed on purpose: writing the debug dump is best-effort
                        // (permissions, disk), and letting its failure escape would
                        // replace the real parse error `e`, rethrown below.
                    }
                }
                throw e;
            }
        }

        // Before writing the next iteration's inject file: otherwise an excluded
        // identifier still lands in the inject import list and the analysis build fails
        // when its `@gjsify/<pkg>/register/<feature>` is not in the project's dep tree.
        if (excludeSet.size > 0) {
            for (const id of excludeSet) newDetected.delete(id);
        }

        // Fixpoint check: detection is monotonic (injecting registers can only ADD
        // references) and the closure expansion below deliberately over-approximates, so
        // convergence is "this pass found nothing OUTSIDE the injected set", not
        // equality.
        if (isSubset(newDetected, detected)) {
            if (verbose) {
                const sorted = [...detected].sort();
                const extras =
                    extraRegisterPaths.size > 0 ? ` (+ ${extraRegisterPaths.size} extra register module(s))` : '';
                console.debug(
                    `[gjsify] --globals auto: converged after ${iteration - 1} iteration(s), ${detected.size} global(s)${sorted.length ? ': ' + sorted.join(', ') : ''}${extras}`,
                );
            }
            return applyExcludeGlobals(detected, currentInject, extraRegisterPaths, options.excludeGlobals, cwd);
        }

        // Seed the next pass with the precomputed closure. Unioning with the
        // previously-injected set keeps growth monotonic — an over-approximated superset
        // that shrank could make the subset convergence check oscillate.
        const expanded = options.disableClosureExpansion ? newDetected : expandWithClosure(newDetected, excludeSet);
        if (verbose && expanded.size > newDetected.size) {
            console.debug(
                `[gjsify] --globals auto: closure map expanded ${newDetected.size} → ${expanded.size} global(s)`,
            );
        }
        if (iteration > 1 && verbose) {
            // A growth pass after the closure-seeded pass means the committed map no
            // longer covers a register's references: iterating keeps it correct, but
            // builds pay extra passes until the map is regenerated.
            console.debug(
                '[gjsify] --globals auto: detection grew past the closure-map expansion — the committed ' +
                    'register-globals-closure map looks stale. Regenerate via ' +
                    '`node packages/infra/cli/scripts/generate-register-closure.mjs`.',
            );
        }
        detected = new Set([...detected, ...expanded]);
        let registerPaths = detectedToRegisterPaths(detected);
        for (const p of extraRegisterPaths) registerPaths.add(p);

        // Drop register paths whose polyfill package is not installed: an unresolvable
        // import is a HARD Rolldown error, strictly worse than skipping with a warning.
        // The caller adds the dep or acknowledges the gap via --exclude-globals.
        if (cwd) registerPaths = filterResolvableRegisterPaths(registerPaths, cwd);

        if (registerPaths.size === 0) {
            return { detected, injectPath: undefined };
        }

        currentInject = (await writeRegisterInjectFile(registerPaths, cwd)) ?? undefined;

        if (verbose) {
            const sorted = [...detected].sort();
            console.debug(
                `[gjsify] --globals auto: iteration ${iteration}, ${detected.size} global(s)${sorted.length ? ': ' + sorted.join(', ') : ''}`,
            );
        }
    }

    if (verbose) {
        console.debug(`[gjsify] --globals auto: hit max iterations (${MAX_ITERATIONS}), using last detected set`);
    }
    return applyExcludeGlobals(detected, currentInject, extraRegisterPaths, options.excludeGlobals, cwd);
}

/**
 * `--app node` genuine-GJS-source detection (the reverse of `--globals auto`).
 *
 * Runs ONE in-memory node bundle (no injection) and scans each chunk for TWO
 * signals, either of which flips `pluginOptions.nodeGiGlobalsInject` for the
 * final build:
 *
 *  1. a GJS ambient global (`print`/`printerr`/`log`/`logError`/`ARGV`/
 *     `imports`) referenced as a BARE identifier — the legacy GJS-source shape
 *     `@gjsify/node-gi/globals` seeds (`detectGjsAmbientGlobals`);
 *  2. a STATIC import of `@gjsify/node-gi` (root or subpath) — the shape the bare GJS
 *     built-ins are externalised to, i.e. the PORTABLE GJS-source spelling
 *     (`detectNodeGiModuleImports`). A bundle retaining one is already bound to the
 *     bridge at load, so flipping injection cannot cost plain-Node loadability, while
 *     a portable GJS app with no ambient global at all (`system.programArgs` instead
 *     of `ARGV`) would otherwise get its `@girs/*` bodies emptied and its globals shim
 *     dropped (the `gjsify storybook --runtime node` no-`requireGi` regression).
 *
 * A SINGLE pass suffices, unlike the GJS register-injection loop: the shim is EXTERNAL,
 * so injecting it adds no bundled code that could reference more globals — no
 * tree-shaking dependency cycle to converge.
 *
 * Detection is on the bundled output AFTER tree-shaking, so a `print`/`imports`
 * reference behind statically-dead code does not trigger injection — importing the shim
 * eagerly loads the native node-gi addon, which crashes on plain Node without node-gi.
 */
export async function detectNodeGiGlobals(
    analysisOptions: AnalysisOptions,
    pluginOptions: Omit<PluginOptions, 'nodeGiGlobalsInject'>,
    gjsifyPluginFactory: GjsifyPluginFactory,
    bundler: AnalysisBundler = defaultBundler,
): Promise<boolean> {
    const factoryResult = await gjsifyPluginFactory(pluginOptions as PluginOptions);

    let gjsifyInstance: RolldownPluginOption;
    let orchestratorOptions: InputOptions | undefined;
    if (isFullConfig(factoryResult)) {
        orchestratorOptions = factoryResult.options;
        gjsifyInstance = factoryResult.plugins as unknown as RolldownPluginOption;
    } else {
        gjsifyInstance = factoryResult;
    }

    const callerPlugins = (analysisOptions.plugins ?? []).filter((p) => {
        const name = p && typeof p === 'object' && 'name' in p ? p.name : undefined;
        return name !== 'gjsify' && name !== 'gjsify-orchestrator';
    });

    const gjsifyPluginsArray = Array.isArray(gjsifyInstance) ? gjsifyInstance : [gjsifyInstance];

    // The FULL orchestrator options as the base (only `output` stripped, `input`/
    // `plugins` overridden) so the analysis bundle goes through the EXACT SAME module
    // resolution as the real `--app node` build. Most importantly `platform: 'node'`:
    // without it Rolldown does not treat `node:*` as builtins and
    // `@gjsify/rolldown-plugin-pnp` rejects `node:fs` with a `RESOLVE_ERROR`. Carried
    // verbatim rather than cherry-picked, unlike `detectAutoGlobals`.
    const baseOptions: InputOptions = orchestratorOptions ? { ...orchestratorOptions } : {};
    delete (baseOptions as { output?: unknown }).output;

    let chunkCodes: string[];
    try {
        chunkCodes = await bundler({
            rolldownInput: {
                ...baseOptions,
                input: analysisOptions.input,
                external: analysisOptions.external ?? baseOptions.external,
                resolve: analysisOptions.resolve ?? baseOptions.resolve,
                transform: analysisOptions.transform ?? baseOptions.transform,
                plugins: [...callerPlugins, ...gjsifyPluginsArray],
                logLevel: 'silent',
            } as InputOptions,
            format: analysisOptions.format ?? 'esm',
        });
    } catch (e) {
        // Fail SAFE: a detection-pass failure must never break a build that would
        // otherwise succeed. Not injecting costs at worst a `ReferenceError: print is
        // not defined` at runtime, recoverable via `--globals` or an explicit import.
        console.warn(
            '[gjsify] --app node: could not analyse the bundle for GJS ambient globals ' +
                `(${e instanceof Error ? e.message : String(e)}); skipping @gjsify/node-gi/globals ` +
                'injection. If this build uses print/imports/ARGV, add `import ' +
                "'@gjsify/node-gi/globals'` to the entry or pass --globals.",
        );
        return false;
    }

    for (const code of chunkCodes) {
        if (detectGjsAmbientGlobals(code).size > 0) return true;
        if (detectNodeGiModuleImports(code)) return true;
    }
    return false;
}

/**
 * Append an entry path to a Rolldown `input` value, preserving its shape. In the record
 * form the synthetic name `__gjsify_inject` avoids colliding with user-named outputs.
 */
function appendInjectAsEntry(input: InputOptions['input'], injectPath: string): InputOptions['input'] {
    if (input === undefined) return [injectPath];
    if (typeof input === 'string') return [input, injectPath];
    if (Array.isArray(input)) {
        return [...input, injectPath];
    }
    return { ...input, __gjsify_inject: injectPath };
}
