import '@gjsify/node-globals/register/process';
import '@gjsify/node-globals/register/buffer';
import '@gjsify/node-globals/register/timers';
import '@gjsify/node-globals/register/url';
import '@gjsify/node-globals/register/structured-clone';
import { run } from '@gjsify/unit';
import testSuite from './index.spec.js';
import sabSuite from './worker-shared-buffer.gjs.spec.js';
import fileBasedWorkerSuite from './file-based-worker.spec.js';
import orphanSuite from './worker-orphan.gjs.spec.js';
run({ testSuite, sabSuite, fileBasedWorkerSuite, orphanSuite });
