// GENERATED by scripts/generate-adwaita-nativescript-templates.mjs — do not edit.
//
// The module every generated template's `xmlns:adw="~/adw"` resolves to,
// and it holds the `Adw` half of the vocabulary and nothing else.
//
// NativeScript reads the element name off THIS module's exports
// (`component-builder`'s `createComponentInstance`), so a template naming an
// element absent here fails at load with `Module '<name>' not found for element` —
// measured on Android, 2026-08-28. Generated from the templates themselves so the
// two cannot fall out of step.
//
// ONE BARREL PER NAMESPACE is what makes the prefix mean something (ADR 0034
// § Amendment 9): the two modules are disjoint, so `<adw:Button>` — the wrong
// library under this prefix — fails to load instead of quietly building the right
// widget under the wrong name.

export {
    AboutDialog,
    ActionRow,
    Avatar,
    Banner,
    BottomSheet,
    ButtonContent,
    ButtonRow,
    Carousel,
    Clamp,
    EntryRow,
    ExpanderRow,
    HeaderBar,
    NavigationSplitView,
    NavigationView,
    OverlaySplitView,
    PasswordEntryRow,
    PreferencesDialog,
    PreferencesGroup,
    PreferencesPage,
    ShortcutLabel,
    SpinRow,
    Spinner,
    StatusPage,
    SwitchRow,
    ToolbarView,
    WindowTitle,
    WrapBox,
} from '@gjsify/adwaita-nativescript/adw';
