// GENERATED by scripts/generate-adwaita-nativescript-templates.mjs — do not edit.
//
// The module every generated template's `xmlns:adw="~/adwaita"` resolves to.
//
// NativeScript reads the element name off THIS module's exports
// (`component-builder`'s `createComponentInstance`), so a template naming an
// element absent here fails at load with `Module '<name>' not found for element` —
// measured on Android, 2026-08-28. Generated from the templates themselves so the
// two cannot fall out of step.

export {
    AdwAboutDialog,
    AdwActionRow,
    AdwAvatar,
    AdwBanner,
    AdwBottomSheet,
    AdwButton,
    AdwButtonContent,
    AdwButtonRow,
    AdwCarousel,
    AdwClamp,
    AdwEntry,
    AdwEntryRow,
    AdwExpanderRow,
    AdwHeaderBar,
    AdwNavigationSplitView,
    AdwNavigationView,
    AdwOverlaySplitView,
    AdwPasswordEntryRow,
    AdwPreferencesDialog,
    AdwPreferencesGroup,
    AdwPreferencesPage,
    AdwShortcutLabel,
    AdwSpinRow,
    AdwSpinner,
    AdwStatusPage,
    AdwSwitchRow,
    AdwToolbarView,
    AdwWindowTitle,
    AdwWrapBox,
} from '@gjsify/adwaita-nativescript';
