// GENERATED by scripts/generate-adwaita-nativescript-templates.mjs — do not edit.
//
// What each generated view under `app/views/` must have BUILT, as the literal
// `gallery-page.ts` walks. It is the same source the template came from, so what
// the probe asserts and what the website ships cannot describe different trees.
//
// `ELEMENT_CLASSES` maps a template's element name to the class an instance must
// be, and it exists because a bundled class NAME is not a fact: Rolldown may rename
// one, and `constructor.name` would then read as a mismatch that is not one.
// `instanceof` asks the runtime instead.

import { Label, StackLayout, type View } from '@nativescript/core';

import { Adw, Gtk } from '@gjsify/adwaita-nativescript';

/** One node of a declared template tree. */
export interface ExpectNode {
    /** The XML element name as the template writes it, e.g. `adw:Clamp` or `Label`. */
    tag: string;
    /** The parent property this child asked for, when it asked for one. */
    slot?: string;
    /** Attribute name -> the value the widget must READ BACK, typed. */
    props?: Record<string, string | number | boolean>;
    children?: ExpectNode[];
}

/** One template, its view file, and the tree it must build. */
export interface ExpectView {
    widget: string;
    view: string;
    root: ExpectNode;
}

/** Element name -> the class `Builder` must have instantiated for it. */
export const ELEMENT_CLASSES: Record<string, new () => View> = {
    'adw:AboutDialog': Adw.AboutDialog,
    'adw:ActionRow': Adw.ActionRow,
    'adw:Avatar': Adw.Avatar,
    'adw:Banner': Adw.Banner,
    'adw:BottomSheet': Adw.BottomSheet,
    'adw:ButtonContent': Adw.ButtonContent,
    'adw:ButtonRow': Adw.ButtonRow,
    'adw:Carousel': Adw.Carousel,
    'adw:Clamp': Adw.Clamp,
    'adw:EntryRow': Adw.EntryRow,
    'adw:ExpanderRow': Adw.ExpanderRow,
    'adw:HeaderBar': Adw.HeaderBar,
    'adw:NavigationSplitView': Adw.NavigationSplitView,
    'adw:NavigationView': Adw.NavigationView,
    'adw:OverlaySplitView': Adw.OverlaySplitView,
    'adw:PasswordEntryRow': Adw.PasswordEntryRow,
    'adw:PreferencesDialog': Adw.PreferencesDialog,
    'adw:PreferencesGroup': Adw.PreferencesGroup,
    'adw:PreferencesPage': Adw.PreferencesPage,
    'adw:ShortcutLabel': Adw.ShortcutLabel,
    'adw:SpinRow': Adw.SpinRow,
    'adw:Spinner': Adw.Spinner,
    'adw:StatusPage': Adw.StatusPage,
    'adw:SwitchRow': Adw.SwitchRow,
    'adw:ToolbarView': Adw.ToolbarView,
    'adw:WindowTitle': Adw.WindowTitle,
    'adw:WrapBox': Adw.WrapBox,
    'gtk:Button': Gtk.Button,
    'gtk:Entry': Gtk.Entry,
    Label,
    StackLayout,
};

export const EXPECTED: readonly ExpectView[] = [
    { widget: 'Adw.PreferencesGroup', view: 'AdwPreferencesGroup', root:
        { tag: 'adw:PreferencesGroup', props: {"title":"Account","description":"Manage how this device signs in and syncs."}, children: [
                { tag: 'adw:EntryRow', props: {"title":"Display name","text":"Grace Hopper"} },
                { tag: 'adw:SwitchRow', props: {"title":"Sync over Wi-Fi only","subtitle":"Avoid using mobile data for backups","active":true} }
            ] }
    },
    { widget: 'Adw.ActionRow', view: 'AdwActionRow', root:
        { tag: 'adw:PreferencesGroup', children: [
                { tag: 'adw:ActionRow', props: {"title":"Wi-Fi","subtitle":"Connected to Highgarden 5GHz","activatable":true} }
            ] }
    },
    { widget: 'Adw.SwitchRow', view: 'AdwSwitchRow', root:
        { tag: 'adw:PreferencesGroup', children: [
                { tag: 'adw:SwitchRow', props: {"title":"Automatic updates","subtitle":"Download and install updates without asking","active":true} }
            ] }
    },
    { widget: 'Adw.EntryRow', view: 'AdwEntryRow', root:
        { tag: 'adw:PreferencesGroup', children: [
                { tag: 'adw:EntryRow', props: {"title":"Display name","text":"Ada Lovelace"} }
            ] }
    },
    { widget: 'Adw.PasswordEntryRow', view: 'AdwPasswordEntryRow', root:
        { tag: 'adw:PreferencesGroup', children: [
                { tag: 'adw:PasswordEntryRow', props: {"title":"Password","text":"correct-horse-battery","revealed":false} }
            ] }
    },
    { widget: 'Adw.SpinRow', view: 'AdwSpinRow', root:
        { tag: 'adw:PreferencesGroup', children: [
                { tag: 'adw:SpinRow', props: {"title":"Copies","value":3,"adjustment":"{\"lower\":1,\"upper\":20,\"stepIncrement\":1}"} }
            ] }
    },
    { widget: 'Adw.ButtonRow', view: 'AdwButtonRow', root:
        { tag: 'adw:PreferencesGroup', children: [
                { tag: 'adw:ButtonRow', props: {"title":"Add account"} }
            ] }
    },
    { widget: 'Adw.ButtonContent', view: 'AdwButtonContent', root:
        { tag: 'adw:ButtonContent', props: {"id":"download","label":"Download"} }
    },
    { widget: 'Gtk.Button', view: 'GtkButton', root:
        { tag: 'StackLayout', props: {"orientation":"horizontal"}, children: [
                { tag: 'gtk:Button', props: {"text":"Pill","styleClasses":"pill"} },
                { tag: 'gtk:Button', props: {"text":"Suggested","styleClasses":"suggested-action"} },
                { tag: 'gtk:Button', props: {"text":"Delete","styleClasses":"destructive-action"} },
                { tag: 'gtk:Button', props: {"text":"Flat","styleClasses":"flat"} }
            ] }
    },
    { widget: 'Gtk.Entry', view: 'GtkEntry', root:
        { tag: 'gtk:Entry', props: {"placeholderText":"Search files…"} }
    },
    { widget: 'Adw.Clamp', view: 'AdwClamp', root:
        { tag: 'adw:Clamp', props: {"maximumSize":400,"tighteningThreshold":300}, children: [
                { tag: 'Label', props: {"class":"card","textWrap":true,"text":"This content is clamped: it stops growing past the maximum size and stays centred."} }
            ] }
    },
    { widget: 'Adw.HeaderBar', view: 'AdwHeaderBar', root:
        { tag: 'adw:HeaderBar', children: [
                { tag: 'gtk:Button', slot: 'startBox', props: {"text":"‹","styleClasses":"flat"} },
                { tag: 'adw:WindowTitle', slot: 'titleWidget', props: {"title":"Text Editor","subtitle":"notes.md"} },
                { tag: 'gtk:Button', slot: 'endBox', props: {"text":"≡","styleClasses":"flat"} }
            ] }
    },
    { widget: 'Adw.ToolbarView', view: 'AdwToolbarView', root:
        { tag: 'adw:ToolbarView', children: [
                { tag: 'adw:HeaderBar', slot: 'topBar', props: {"title":"Documents","subtitle":"12 items"} },
                { tag: 'adw:StatusPage', slot: 'content', props: {"id":"library","title":"Your library","description":"Content sits between the toolbars and scrolls independently of them."} },
                { tag: 'adw:HeaderBar', slot: 'bottomBar', children: [
                        { tag: 'adw:WindowTitle', slot: 'titleWidget', props: {"title":"Selection: none"} }
                    ] }
            ] }
    },
    { widget: 'Adw.WrapBox', view: 'AdwWrapBox', root:
        { tag: 'adw:WrapBox', props: {"childSpacing":8,"lineSpacing":8}, children: [
                { tag: 'gtk:Button', props: {"text":"Design","styleClasses":"pill"} },
                { tag: 'gtk:Button', props: {"text":"Adwaita","styleClasses":"pill"} },
                { tag: 'gtk:Button', props: {"text":"GNOME","styleClasses":"pill"} },
                { tag: 'gtk:Button', props: {"text":"GTK","styleClasses":"pill"} },
                { tag: 'gtk:Button', props: {"text":"TypeScript","styleClasses":"pill"} },
                { tag: 'gtk:Button', props: {"text":"Storybook","styleClasses":"pill"} }
            ] }
    },
    { widget: 'Adw.Avatar', view: 'AdwAvatar', root:
        { tag: 'adw:Avatar', props: {"text":"Ada Lovelace","size":96,"showInitials":true} }
    },
    { widget: 'Adw.Banner', view: 'AdwBanner', root:
        { tag: 'adw:Banner', props: {"title":"Metered connection: updates paused","buttonLabel":"Resume","revealed":true} }
    },
    { widget: 'Adw.ShortcutLabel', view: 'AdwShortcutLabel', root:
        { tag: 'adw:ShortcutLabel', props: {"accelerator":"<Control>C"} }
    },
    { widget: 'Adw.Spinner', view: 'AdwSpinner', root:
        { tag: 'adw:Spinner', props: {"spinning":true,"size":48} }
    },
    { widget: 'Adw.StatusPage', view: 'AdwStatusPage', root:
        { tag: 'adw:StatusPage', props: {"iconText":"📁","title":"No Documents","description":"Documents you create or open will appear here."} }
    },
    { widget: 'Adw.WindowTitle', view: 'AdwWindowTitle', root:
        { tag: 'adw:WindowTitle', props: {"title":"Inbox","subtitle":"3 unread messages"} }
    },
    { widget: 'Adw.AboutDialog', view: 'AdwAboutDialog', root:
        { tag: 'adw:AboutDialog', props: {"applicationName":"Adwaita Gallery","version":"1.0.0","developerName":"The GNOME Project","comments":"A tour of the Adwaita widgets on NativeScript.","website":"https://gjsify.org","copyright":"© 2026 The GNOME Project","open":false} }
    },
    { widget: 'Adw.ExpanderRow', view: 'AdwExpanderRow', root:
        { tag: 'adw:PreferencesGroup', children: [
                { tag: 'adw:ExpanderRow', props: {"title":"Advanced","subtitle":"Options most people leave alone","expanded":true}, children: [
                        { tag: 'adw:SwitchRow', props: {"title":"Developer mode","active":false} },
                        { tag: 'adw:EntryRow', props: {"title":"Endpoint","text":"https://example.invalid"} }
                    ] }
            ] }
    },
    { widget: 'Adw.Carousel', view: 'AdwCarousel', root:
        { tag: 'adw:Carousel', children: [
                { tag: 'adw:StatusPage', props: {"iconText":"①","title":"Welcome"} },
                { tag: 'adw:StatusPage', props: {"iconText":"②","title":"Sync"} },
                { tag: 'adw:StatusPage', props: {"iconText":"③","title":"Done"} }
            ] }
    },
    { widget: 'Adw.NavigationSplitView', view: 'AdwNavigationSplitView', root:
        { tag: 'adw:NavigationSplitView', children: [
                { tag: 'adw:ToolbarView', slot: 'sidebar', children: [
                        { tag: 'adw:HeaderBar', slot: 'topBar', props: {"title":"Mailboxes"} },
                        { tag: 'adw:StatusPage', slot: 'content', props: {"title":"Mailboxes"} }
                    ] },
                { tag: 'adw:ToolbarView', slot: 'content', children: [
                        { tag: 'adw:HeaderBar', slot: 'topBar', props: {"title":"All Mail"} },
                        { tag: 'adw:StatusPage', slot: 'content', props: {"title":"All Mail","description":"Select a conversation from the list to read it here."} }
                    ] }
            ] }
    },
    { widget: 'Adw.OverlaySplitView', view: 'AdwOverlaySplitView', root:
        { tag: 'adw:OverlaySplitView', children: [
                { tag: 'adw:ToolbarView', slot: 'sidebar', children: [
                        { tag: 'adw:HeaderBar', slot: 'topBar', props: {"title":"Library"} },
                        { tag: 'adw:StatusPage', slot: 'content', props: {"title":"Sections"} }
                    ] },
                { tag: 'adw:ToolbarView', slot: 'content', children: [
                        { tag: 'adw:HeaderBar', slot: 'topBar', props: {"title":"Your Library"} },
                        { tag: 'adw:StatusPage', slot: 'content', props: {"title":"Your Library","description":"Toggle the sidebar to browse sections."} }
                    ] }
            ] }
    },
    { widget: 'Adw.NavigationView', view: 'AdwNavigationView', root:
        { tag: 'adw:NavigationView', children: [
                { tag: 'adw:ToolbarView', children: [
                        { tag: 'adw:HeaderBar', slot: 'topBar', props: {"title":"Contacts"} },
                        { tag: 'adw:StatusPage', slot: 'content', props: {"title":"Contacts","description":"Push a page to see the transition."} }
                    ] },
                { tag: 'adw:ToolbarView', children: [
                        { tag: 'adw:HeaderBar', slot: 'topBar', props: {"title":"Ada Lovelace"} },
                        { tag: 'adw:StatusPage', slot: 'content', props: {"title":"Ada Lovelace","description":"Mathematician and writer, the first computer programmer."} }
                    ] }
            ] }
    },
    { widget: 'Adw.BottomSheet', view: 'AdwBottomSheet', root:
        { tag: 'adw:BottomSheet', props: {"open":true}, children: [
                { tag: 'adw:StatusPage', slot: 'content', props: {"title":"Now Playing","description":"The sheet slides up over this."} },
                { tag: 'adw:PreferencesGroup', slot: 'sheet', props: {"title":"Queue"}, children: [
                        { tag: 'adw:ActionRow', props: {"title":"Blue Monday","subtitle":"New Order"} },
                        { tag: 'adw:ActionRow', props: {"title":"Just Like Heaven","subtitle":"The Cure"} }
                    ] }
            ] }
    },
    { widget: 'Adw.PreferencesDialog', view: 'AdwPreferencesDialog', root:
        { tag: 'adw:PreferencesDialog', props: {"title":"Preferences","open":false}, children: [
                { tag: 'adw:PreferencesPage', props: {"title":"General"}, children: [
                        { tag: 'adw:PreferencesGroup', props: {"title":"Appearance"}, children: [
                                { tag: 'adw:SwitchRow', props: {"title":"Dark mode","active":true} }
                            ] }
                    ] }
            ] }
    },
];
