// Reference: Node.js lib/fs.js
// Reimplemented for GJS using Gio.File

import {
  existsSync,
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmdirSync,
  unlinkSync,
  watch,
  mkdtempSync,
  rmSync,
  statSync,
  openSync,
  realpathSync,
  symlinkSync,
  lstatSync,
  renameSync,
  copyFileSync,
  accessSync,
  appendFileSync,
  readlinkSync,
  linkSync,
  truncateSync,
  chmodSync,
  chownSync,
} from './sync.js';
import {
  open,
  close,
  read,
  write,
  rm,
  realpath,
  readdir,
  symlink,
  lstat,
  stat,
  rename,
  copyFile,
  access,
  appendFile,
  readlink,
  truncate,
  chmod,
  chown,
  mkdir,
  rmdir,
  readFile,
  writeFile,
  unlink,
  link,
} from './callback.js';
import FSWatcher from './fs-watcher.js';
import {
  createReadStream,
  ReadStream
} from './read-stream.js';
import {
  createWriteStream,
  WriteStream
} from './write-stream.js';
import * as promises from './promises.js';
import { cpSync, cp } from './cp.js';
import { Dir, opendir, opendirSync } from './dir.js';
import { Stats, BigIntStats } from './stats.js';
import { Dirent } from './dirent.js';

// --- fs.constants ---
export const constants = {
  // File access constants
  F_OK: 0,
  R_OK: 4,
  W_OK: 2,
  X_OK: 1,
  // File copy constants
  COPYFILE_EXCL: 1,
  COPYFILE_FICLONE: 2,
  COPYFILE_FICLONE_FORCE: 4,
  // File open constants
  O_RDONLY: 0,
  O_WRONLY: 1,
  O_RDWR: 2,
  O_CREAT: 64,
  O_EXCL: 128,
  O_TRUNC: 512,
  O_APPEND: 1024,
  O_SYNC: 1052672,
  O_NONBLOCK: 2048,
  O_DIRECTORY: 65536,
  O_NOFOLLOW: 131072,
  // File type constants
  S_IFMT: 61440,
  S_IFREG: 32768,
  S_IFDIR: 16384,
  S_IFCHR: 8192,
  S_IFBLK: 24576,
  S_IFIFO: 4096,
  S_IFLNK: 40960,
  S_IFSOCK: 49152,
  // File mode constants
  S_IRWXU: 448,
  S_IRUSR: 256,
  S_IWUSR: 128,
  S_IXUSR: 64,
  S_IRWXG: 56,
  S_IRGRP: 32,
  S_IWGRP: 16,
  S_IXGRP: 8,
  S_IRWXO: 7,
  S_IROTH: 4,
  S_IWOTH: 2,
  S_IXOTH: 1,
};

export {
  FSWatcher,
  Stats,
  BigIntStats,
  Dirent,
  Dir,
  // Sync API
  existsSync,
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmdirSync,
  unlinkSync,
  mkdtempSync,
  rmSync,
  statSync,
  openSync,
  realpathSync,
  symlinkSync,
  lstatSync,
  renameSync,
  copyFileSync,
  accessSync,
  appendFileSync,
  readlinkSync,
  linkSync,
  truncateSync,
  chmodSync,
  chownSync,
  cpSync,
  opendirSync,
  watch,
  // Streams
  createReadStream,
  ReadStream,
  createWriteStream,
  WriteStream,
  // Promises
  promises,
  // Callback API
  open,
  close,
  read,
  write,
  rm,
  realpath,
  readdir,
  symlink,
  lstat,
  stat,
  rename,
  copyFile,
  cp,
  access,
  appendFile,
  readlink,
  truncate,
  chmod,
  chown,
  mkdir,
  rmdir,
  readFile,
  writeFile,
  unlink,
  link,
  opendir,
};

export default {
  FSWatcher,
  Stats,
  BigIntStats,
  Dirent,
  Dir,
  constants,
  existsSync,
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmdirSync,
  unlinkSync,
  mkdtempSync,
  rmSync,
  statSync,
  openSync,
  realpathSync,
  symlinkSync,
  lstatSync,
  renameSync,
  copyFileSync,
  accessSync,
  appendFileSync,
  readlinkSync,
  linkSync,
  truncateSync,
  chmodSync,
  chownSync,
  cpSync,
  opendirSync,
  watch,
  createReadStream,
  ReadStream,
  createWriteStream,
  WriteStream,
  promises,
  open,
  close,
  read,
  write,
  rm,
  realpath,
  readdir,
  symlink,
  lstat,
  stat,
  rename,
  copyFile,
  cp,
  access,
  appendFile,
  readlink,
  truncate,
  chmod,
  chown,
  mkdir,
  rmdir,
  readFile,
  writeFile,
  unlink,
  link,
  opendir,
};
