// Reference: Node.js lib/fs.js
// Reimplemented for GJS using Gio.File

import {
    existsSync,
    readdirSync,
    readFileSync,
    writeFileSync,
    mkdirSync,
    rmdirSync,
    unlinkSync,
    watch,
    mkdtempSync,
    rmSync,
    statSync,
    openSync,
    realpathSync,
    symlinkSync,
    lstatSync,
    renameSync,
    copyFileSync,
    accessSync,
    appendFileSync,
    readlinkSync,
    linkSync,
    truncateSync,
    chmodSync,
    chownSync,
} from './sync.js';
import {
    open,
    close,
    read,
    write,
    rm,
    realpath,
    readdir,
    symlink,
    lstat,
    stat,
    rename,
    copyFile,
    access,
    appendFile,
    readlink,
    truncate,
    chmod,
    chown,
    mkdir,
    mkdtemp,
    rmdir,
    readFile,
    writeFile,
    unlink,
    link,
} from './callback.js';
import FSWatcher from './fs-watcher.js';
import { createReadStream, ReadStream } from './read-stream.js';
import { createWriteStream, WriteStream } from './write-stream.js';
import * as promises from './promises.js';
import { cpSync, cp } from './cp.js';
import { Dir, opendir, opendirSync } from './dir.js';
import { glob, globSync } from './glob.js';
import { StatWatcher, watchFile, unwatchFile } from './stat-watcher.js';
import { statfsSync, statfs } from './statfs.js';
import { Stats, BigIntStats } from './stats.js';
import { Dirent } from './dirent.js';
import { utimesSync, utimes, lutimesSync, lutimes, lchownSync, lchown, lchmodSync, lchmod } from './utimes.js';
import {
    fstatSync,
    fstat,
    ftruncateSync,
    ftruncate,
    fdatasyncSync,
    fdatasync,
    fsyncSync,
    fsync,
    fchmodSync,
    fchmod,
    fchownSync,
    fchown,
    futimesSync,
    futimes,
    closeSync,
    readSync,
    writeSync,
    readvSync,
    readv,
    writevSync,
    writev,
    exists,
    openAsBlob,
} from './fd-ops.js';
import { constants } from './constants.js';

export { constants };

export {
    FSWatcher,
    StatWatcher,
    Stats,
    BigIntStats,
    Dirent,
    Dir,
    // Sync API
    existsSync,
    readdirSync,
    readFileSync,
    writeFileSync,
    mkdirSync,
    rmdirSync,
    unlinkSync,
    mkdtemp,
    mkdtempSync,
    rmSync,
    statSync,
    openSync,
    realpathSync,
    symlinkSync,
    lstatSync,
    renameSync,
    copyFileSync,
    accessSync,
    appendFileSync,
    readlinkSync,
    linkSync,
    truncateSync,
    chmodSync,
    chownSync,
    cpSync,
    opendirSync,
    globSync,
    glob,
    watch,
    watchFile,
    unwatchFile,
    statfsSync,
    statfs,
    // utimes / lutimes / lchown / lchmod
    utimesSync,
    utimes,
    lutimesSync,
    lutimes,
    lchownSync,
    lchown,
    lchmodSync,
    lchmod,
    // fd-based ops
    fstatSync,
    fstat,
    ftruncateSync,
    ftruncate,
    fdatasyncSync,
    fdatasync,
    fsyncSync,
    fsync,
    fchmodSync,
    fchmod,
    fchownSync,
    fchown,
    futimesSync,
    futimes,
    closeSync,
    readSync,
    writeSync,
    readvSync,
    readv,
    writevSync,
    writev,
    exists,
    openAsBlob,
    // Streams
    createReadStream,
    ReadStream,
    createWriteStream,
    WriteStream,
    // Promises
    promises,
    // Callback API
    open,
    close,
    read,
    write,
    rm,
    realpath,
    readdir,
    symlink,
    lstat,
    stat,
    rename,
    copyFile,
    cp,
    access,
    appendFile,
    readlink,
    truncate,
    chmod,
    chown,
    mkdir,
    rmdir,
    readFile,
    writeFile,
    unlink,
    link,
    opendir,
};

const _default = {
    FSWatcher,
    StatWatcher,
    Stats,
    BigIntStats,
    Dirent,
    Dir,
    constants,
    existsSync,
    readdirSync,
    readFileSync,
    writeFileSync,
    mkdirSync,
    rmdirSync,
    unlinkSync,
    mkdtemp,
    mkdtempSync,
    rmSync,
    statSync,
    openSync,
    realpathSync,
    symlinkSync,
    lstatSync,
    renameSync,
    copyFileSync,
    accessSync,
    appendFileSync,
    readlinkSync,
    linkSync,
    truncateSync,
    chmodSync,
    chownSync,
    cpSync,
    opendirSync,
    globSync,
    glob,
    watch,
    watchFile,
    unwatchFile,
    statfsSync,
    statfs,
    utimesSync,
    utimes,
    lutimesSync,
    lutimes,
    lchownSync,
    lchown,
    lchmodSync,
    lchmod,
    fstatSync,
    fstat,
    ftruncateSync,
    ftruncate,
    fdatasyncSync,
    fdatasync,
    fsyncSync,
    fsync,
    fchmodSync,
    fchmod,
    fchownSync,
    fchown,
    futimesSync,
    futimes,
    closeSync,
    readSync,
    writeSync,
    readvSync,
    readv,
    writevSync,
    writev,
    exists,
    openAsBlob,
    createReadStream,
    ReadStream,
    createWriteStream,
    WriteStream,
    promises,
    open,
    close,
    read,
    write,
    rm,
    realpath,
    readdir,
    symlink,
    lstat,
    stat,
    rename,
    copyFile,
    cp,
    access,
    appendFile,
    readlink,
    truncate,
    chmod,
    chown,
    mkdir,
    rmdir,
    readFile,
    writeFile,
    unlink,
    link,
    opendir,
};

export default _default;

// CJS-interop for bundled `require('fs')`, the device `@gjsify/stream` and
// `@gjsify/events` already use: Rolldown's `__toCommonJS` returns a `"module.exports"`
// own-property verbatim instead of the ESM namespace. Node's `require('fs')` is a
// MUTABLE object, and graceful-fs — under fs-extra, web-ext and most file-heavy CLIs —
// patches it in place (`fs.close = …`). On the namespace that assignment throws
// `setting getter-only property "close"` at load, which is where web-ext's rebuild for
// `gjsify exec` died. ESM named imports are unaffected, as in Node.
export { _default as 'module.exports' };
