/**
 * Emit the TYPE surfaces: one interface per GIR declaration, four tag maps.
 *
 * WHAT THE DIALECTS FORCED, all of it measured rather than assumed (ADR 0028 § 7,
 * and the numbers live there):
 *
 *  - BOTH PROPERTY SPELLINGS, for opposite reasons in the two dialects. Vue does
 *    not need the kebab key — Volar camelizes an attribute before resolving it, so
 *    `:height-request` finds `heightRequest` and catches a wrong value type there.
 *    JSX does need it: TypeScript exempts every hyphenated attribute from
 *    excess-property checking, so `no-such={1}` on an intrinsic is silently
 *    accepted, and the only checking a kebab attribute can ever get is the value
 *    check that a DECLARED key gives it. Declaring both costs 561 extra members
 *    and buys the one spelling GTK itself uses.
 *  - JSX KEYS ARE KEBAB, VUE KEYS ARE THE GTYPE NAME. A capitalised
 *    `JSX.IntrinsicElements` key is never consulted — TypeScript reads `<GtkBox/>`
 *    as a value reference — while Volar resolves a kebab TAG against a GType key
 *    but not a Pascal tag against a kebab key. So each dialect gets the one
 *    spelling that works, from one shared props interface.
 *  - EXACT HANDLER SIGNATURES, never `(...args: unknown[]) => void`. Measured
 *    twice over: an annotated `(row: AdwActionRow) => void` will not assign to an
 *    `unknown[]` rest (TS2322, contravariance), and an inline arrow's parameter
 *    arrives as `unknown` so using it fails (TS2345). A generated surface that
 *    typed handlers loosely would break every handler that names its parameter.
 */

import type { AriaSlot } from '../types.js';
import type { Declaration, SurfaceModel } from './model.mjs';
import { tagOf } from '../tags.js';

const HEADER = (what: string, provenance: string) => `// GENERATED by src/generator/main.mts — do not edit.
//
// Provenance: ${provenance}
//
// ${what}`;

const jsdoc = (indent: string, doc: string | undefined, deprecated: boolean): string => {
    if (!doc && !deprecated) return '';
    const lines: string[] = [];
    if (doc) lines.push(doc);
    if (deprecated) lines.push('@deprecated');
    if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
    return `${indent}/**\n${lines.map((l) => `${indent} * ${l}`).join('\n')}\n${indent} */\n`;
};

/**
 * Volar's own resolution rule, reproduced so the generator can SEE the gap.
 *
 * A Vue template tag is camelized (`-x` -> `X`) and capitalised before lookup, and
 * that transform has no acronym knowledge: `gtk-gl-area` becomes `GtkGlArea`,
 * which is not `GtkGLArea`. Measured — `<gtk-gl-area>` against a `GtkGLArea` key
 * is TS2339. Exactly one of the 164 concrete widgets is affected today, and the
 * generator finds it rather than leaving it to a bug report: such a widget gets an
 * extra kebab-spelled key, which a kebab tag does resolve against.
 */
export const volarResolves = (tag: string, gtype: string): boolean =>
    tag.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()).replace(/^./, (c) => c.toUpperCase()) === gtype;

function renderBases(decl: Declaration, model: SurfaceModel): string {
    if (decl.bases.length === 0) return '';
    const omissions = model.omissions.get(decl.key);
    const rendered = decl.bases.map((base) => {
        const target = model.declarations.get(base);
        const name = target ? target.iface : base;
        const drop = omissions?.get(base);
        if (!drop || drop.length === 0) return name;
        return `Omit<${name}, ${drop.map((d) => `'${d}'`).join(' | ')}>`;
    });
    return ` extends ${rendered.join(', ')}`;
}

function renderDeclaration(decl: Declaration, model: SurfaceModel): string {
    const body: string[] = [];
    for (const p of decl.props) {
        body.push(jsdoc('    ', p.doc, p.deprecated));
        body.push(`    ${p.camel}?: ${p.ts};\n`);
        // BOTH spellings, and the kebab one is not redundant: measured, TypeScript
        // exempts every hyphen-containing JSX attribute from excess-property
        // checking, so an UNDECLARED `no-such={1}` is silently accepted while a
        // DECLARED `can-focus={'yes'}` is caught (TS2322). Declaring it is the only
        // way to get any checking at all on the spelling GTK itself uses.
        if (p.kebab !== p.camel) body.push(`    '${p.kebab}'?: ${p.ts};\n`);
    }
    for (const s of decl.signals) {
        body.push(jsdoc('    ', s.doc, s.deprecated));
        body.push(`    ${s.prop}?: ${s.ts};\n`);
    }
    // One `notify::` handler per own property. The shape never varies, so it can
    // never conflict across bases — which is why it is not in the member map that
    // computes the `Omit`s.
    for (const p of decl.props) {
        body.push(`    onNotify${p.camel.charAt(0).toUpperCase()}${p.camel.slice(1)}?: NotifyHandler;\n`);
    }
    const doc = jsdoc('', decl.doc, false);
    return `${doc}export interface ${decl.iface}${renderBases(decl, model)} {\n${body.join('')}}\n`;
}

export interface EmittedFile {
    readonly path: string;
    readonly text: string;
}

export function emitProps(model: SurfaceModel, provenance: string): EmittedFile {
    // The widget namespaces are needed for `WidgetClassByTag` even when no property
    // or signal happens to reference them, and `noUnusedLocals` refuses an import
    // that is not — so the set is computed, never assumed.
    const needed = new Set(model.namespacesUsed);
    for (const w of model.widgets) needed.add(w.namespace);
    const namespaces = [...needed].sort();
    const imports = namespaces.map((ns) => {
        const pkg = model.packages[ns];
        if (!pkg) throw new Error(`no @girs package for namespace ${ns}`);
        return `import type ${ns} from '${pkg}';`;
    });

    const unionOf = (members: readonly string[]): string =>
        members.length === 0 ? 'never' : members.map((m) => `'${m}'`).join(' | ');
    const nicks = [...model.enumNicks]
        .sort((a, b) => (a[0] < b[0] ? -1 : 1))
        .map(([gtype, members]) => `export type ${gtype}Nick = ${unionOf(members)};`);
    // TWO aliases per bitfield, because a SET is not a member. The members are a union
    // like an enum's; what a PROPERTY takes is that union or a `|`-joined string, and
    // the join is where TypeScript runs out — checking every member of a set of
    // arbitrary length means enumerating its permutations, n! terms for an n-member
    // bitfield and 26 members on the largest one this surface carries. So the template
    // pins the FIRST member exactly and the host checks the rest, which it can: it
    // resolves the whole set through GTK's own `.ui` parser and names any member that
    // resolves to nothing.
    const flagNicks = [...model.flagNicks]
        .sort((a, b) => (a[0] < b[0] ? -1 : 1))
        .flatMap(([gtype, members]) => [
            `export type ${gtype}Nick = ${unionOf(members)};`,
            `export type ${gtype}NickSet = ${gtype}Nick | \`\${${gtype}Nick}|\${string}\`;`,
        ]);

    const decls = [...model.declarations.values()].sort((a, b) => (a.iface < b.iface ? -1 : 1));
    // `OutParam` is no longer emitted, and the condition that used to decide it was
    // measured dead: `grep -c OutParam src/generated/props.ts` is 0. Signal signatures
    // come from `@girs` as `X.SignalSignatures['name']` now, so how an out parameter is
    // spelled is that package's answer rather than this generator's. The type itself
    // stays exported from `attrs.ts` — it documents why an out parameter must not be
    // typed `number`, which is still true — but nothing here produces one.
    //
    // `noUnusedLocals` is why this was ever conditional: it refuses an import nothing
    // reads, and a namespace whose signals are all `in` produced exactly that file.
    const hostTypes = 'NotifyHandler';
    const byTag: string[] = [];
    const byGType: string[] = [];
    const classByTag: string[] = [];
    const vueAliases: string[] = [];
    for (const w of model.widgets) {
        const iface = `${w.gtype}Props`;
        const tag = tagOf(w.gtype);
        byTag.push(`    '${tag}': ${iface};`);
        byGType.push(`    ${w.gtype}: ${iface};`);
        classByTag.push(`    '${tag}': ${w.namespace}.${w.name};`);
        if (!volarResolves(tag, w.gtype)) vueAliases.push(`    '${tag}': ${iface};`);
    }

    const text = `${HEADER(
        `The type surface: one interface per GIR declaration, mirroring GIR's own
// inheritance, plus the four tag maps the dialect adapters build on.
//
// ${model.declarations.size} interfaces for ${model.widgets.length} widgets — the widgets have ${countSlots(model)} writable
// property slots between them and ${countDistinct(model)} distinct property names, which is the whole
// reason this is a hierarchy and not one flat interface per tag.`,
        provenance,
    )}

${imports.join('\n')}

import type { ${hostTypes} } from '../attrs.js';

// Enum nicks. A property takes the nick OR the enum constant; a signal parameter
// takes the constant only, because GJS hands the marshalled number and a nick
// comparison there would always be false.
${nicks.join('\n')}

// Bitfield nicks. \`…Nick\` is one member, \`…NickSet\` is what a property takes: one
// member, or several joined with "|" as GObject spells a flags value. The set form
// checks its first member and leaves the rest to the host — see the emitter.
${flagNicks.join('\n')}

${decls.map((d) => renderDeclaration(d, model)).join('\n')}
/** Props by JSX tag — kebab, the only spelling \`JSX.IntrinsicElements\` consults. */
export interface WidgetPropsByTag {
${byTag.join('\n')}
}

/** Props by GType name — the Vue \`GlobalComponents\` key, and the registry key. */
export interface WidgetPropsByGType {
${byGType.join('\n')}
}

/**
 * Kebab keys for the widgets Volar's camelize cannot reach from their GType name.
 *
 * ${vueAliases.length === 0 ? 'Empty today.' : `${vueAliases.length} of ${model.widgets.length}.`} Generated, not curated: any future GType with two adjacent
 * capitals lands here by itself instead of becoming a bug report.
 */
export interface WidgetPropsVueAliases {
${vueAliases.join('\n')}
}

/**
 * Tag -> the INSTANCE type of the widget it creates.
 *
 * What this is for: \`ref\`. Measured — \`JSX.IntrinsicAttributes\` is unioned into
 * the attributes of a COMPONENT and not of an intrinsic element, so a \`ref\` that
 * is not a real member of the element's own props is rejected outright. Carrying
 * the class type per tag makes \`ref={(el) => …}\` infer \`el\` as \`Gtk.Box\`, which
 * is strictly better than the \`ref?: unknown\` a DOM renderer settles for.
 */
export interface WidgetClassByTag {
${classByTag.join('\n')}
}

export type WidgetTag = keyof WidgetPropsByTag;
export type WidgetGType = keyof WidgetPropsByGType;
`;
    return { path: 'props.ts', text };
}

/** A key an object literal may carry unquoted. Same rule the props emitter applies to kebab spellings. */
const bareKey = (name: string): string => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : `'${name}'`);

/** The scalar TypeScript spelling of a non-enum, non-reference ARIA value kind. */
const ARIA_SCALAR_TS: Readonly<Record<string, string>> = {
    string: 'string',
    integer: 'number',
    double: 'number',
    boolean: 'boolean',
};

/**
 * `GtkAccessibleTristate` -> `Gtk.AccessibleTristate`, using the namespaces the surface
 * already imports.
 *
 * LONGEST PREFIX FIRST, the same rule and the same reason as `splitGType`: a one-letter
 * namespace examined before `Gtk` would split `GtkOrientation` into a namespace that
 * renders, compiles and is wrong everywhere it appears. A GType no namespace claims is a
 * hard error rather than a guess, because the alternative is an emitted `undefined.`.
 */
function qualifyEnum(gtype: string, namespaces: readonly string[]): { ns: string; ts: string } {
    for (const ns of [...namespaces].sort((a, b) => b.length - a.length)) {
        if (gtype.startsWith(ns) && gtype.length > ns.length) return { ns, ts: `${ns}.${gtype.slice(ns.length)}` };
    }
    throw new Error(`the ARIA enum ${gtype} starts with none of the surface namespaces (${namespaces.join(', ')})`);
}

/**
 * Emit GTK's ARIA surface: the slot table the runtime reads, and the props interface.
 *
 * WHY THIS FILE EXISTS AND `props.ts` COULD NOT CARRY IT. Every other name a renderer can
 * write on a widget is a GObject property, and the host resolves those through the
 * ParamSpec of the INSTALLED class — the table travels with the package, the coercion
 * travels with the user's GTK. An ARIA slot has no ParamSpec. `GtkAccessible` installs
 * exactly one property, `accessible-role`; the other 53 names live in three ENUMS and are
 * written through three calls, and the value type of each is stated only in that enum
 * member's GIR DOCUMENTATION. So the type has to SHIP, and this is the one generated file
 * whose data the runtime cannot re-derive from the object in front of it.
 *
 * WHY THE TABLE AND THE INTERFACE ARE IN ONE FILE. They are the two halves of one answer
 * and they are keyed identically; split, the day a GTK release adds a name is the day the
 * type surface and the runtime refusal disagree about whether it exists.
 *
 * THE FLOOR IS THE LOAD-BEARING GATE, as it is in `emit.mts`: a reader that silently
 * yields three rows and a generator reporting success over it look identical, and here
 * an under-read does not fail loudly downstream — it emits a smaller vocabulary, and
 * every name it dropped becomes `unknown-aria` at a user's call site.
 */
export function emitAccessibility(model: SurfaceModel, provenance: string, floor = 40): EmittedFile {
    const slots = [...model.aria].sort((a, b) => (a[0] < b[0] ? -1 : 1));
    if (slots.length < floor) {
        throw new Error(
            `only ${slots.length} ARIA slot(s) read from the vocabularies, below the floor of ${floor} — ` +
                `the vocabulary's ARIA tables are probably not being read`,
        );
    }

    const namespaces = [...model.namespacesUsed];
    const nickImports = new Set<string>();
    const nsImports = new Set<string>();
    const rows: string[] = [];
    const members: string[] = [];
    for (const [name, slot] of slots) {
        const fields = [`table: '${slot.table}'`, `kind: '${slot.kind}'`];
        if (slot.enumGType) fields.push(`enumGType: '${slot.enumGType}'`);
        rows.push(`    ${bareKey(name)}: { ${fields.join(', ')} },`);
        members.push(renderAriaMember(name, slot, namespaces, nickImports, nsImports));
    }

    const imports = [...nsImports].sort().map((ns) => `import type ${ns} from '${model.packages[ns]}';`);
    const nicks = [...nickImports].sort();

    const text = `${HEADER(
        `GTK's ARIA surface: ${slots.length} slots over three tables, and the props interface
// that types them. The one generated table the runtime CANNOT re-derive from the object
// in front of it — see \`emitAccessibility\` in src/generator/emit-types.mts.`,
        provenance,
    )}

${imports.join('\n')}

import type { AriaSlot } from '../types.js';
import type { ${nicks.join(', ')} } from './props.js';

/**
 * ARIA name -> the table it belongs to and the kind of value GTK collects for it.
 *
 * Keyed by the NAME alone: across the three tables of this GTK the names are distinct,
 * and \`girs-vocabulary.mts\` fails the generation rather than emit a map that silently
 * kept one of two. The table name is what the runtime derives its GTK call from.
 */
export const ARIA_SLOTS: Readonly<Record<string, AriaSlot>> = {
${rows.join('\n')}
};

/**
 * What \`accessibility={{ … }}\` accepts.
 *
 * ONE OBJECT PROP, NOT ${slots.length} FLAT ONES, and the decision is measured rather than
 * stylistic. Measured in this repo's own type surface: TypeScript exempts every
 * hyphen-containing JSX attribute from excess-property checking, so a flat \`aria-labell\`
 * would be accepted in silence, while a key inside a FRESH object literal is checked —
 * \`accessibility={{ labell: 'x' }}\` is TS2561, naming the key and suggesting \`label\`. A grouped
 * prop is also the spelling the other surface over this same vocabulary has: a \`.blp\` author
 * writes \`accessibility { label: "…"; }\`, and ADR 0034 exists so two surfaces over one
 * vocabulary do not invent two spellings for one name.
 *
 * KEBAB, THE SPELLING GTK ITSELF USES. A second camelCase spelling would double the
 * surface for nothing: unlike a JSX attribute, a quoted key in an object literal IS
 * excess-property checked, so the one spelling already catches the typo.
 *
 * \`null\` clears a slot, as it does for every property on this host — \`gtk_accessible_reset_*\`
 * is what GTK offers and what the host calls.
 */
export interface AccessibilityAttributes {
${members.join('\n')}
}
`;
    return { path: 'accessibility.ts', text };
}

/**
 * One member of {@link emitAccessibility}'s interface.
 *
 * A `reference` slot is declared `never` ON PURPOSE rather than omitted. Omitting it
 * makes the excess-property check say the name is unknown, which is false — GTK has it,
 * this host cannot yet express it. Declared, the name is in the surface where a reader
 * looks it up, hover carries the reason, and writing anything at all is still an error.
 */
function renderAriaMember(
    name: string,
    slot: AriaSlot,
    namespaces: readonly string[],
    nickImports: Set<string>,
    nsImports: Set<string>,
): string {
    const key = bareKey(name);
    if (slot.kind === 'reference') {
        return (
            `    /**\n` +
            `     * \`${slot.table}.${name}\` — a REFERENCE to another widget, and this host has no way\n` +
            `     * to name one. There is no \`id\` prop and \`ref\` is resolved by the framework after the\n` +
            `     * props are applied, so the value would be \`null\` on the render that authors it. Declared\n` +
            `     * and unwritable rather than absent: GTK has this name, the gap is ours.\n` +
            `     */\n` +
            `    ${key}?: never;\n`
        );
    }
    if (slot.kind === 'enum') {
        const gtype = slot.enumGType as string;
        const { ns, ts } = qualifyEnum(gtype, namespaces);
        nickImports.add(`${gtype}Nick`);
        nsImports.add(ns);
        return (
            `    /** \`${slot.table}.${name}\` — a ${gtype}, which GTK collects as an int: the nick or the constant. */\n` +
            `    ${key}?: ${gtype}Nick | ${ts} | null;\n`
        );
    }
    const ts = ARIA_SCALAR_TS[slot.kind];
    if (!ts) throw new Error(`no TypeScript spelling for the ARIA value kind ${slot.kind} (${name})`);
    const article = 'aeiou'.includes(slot.kind[0] as string) ? 'an' : 'a';
    return (
        `    /** \`${slot.table}.${name}\` — GTK collects it as ${article} ${slot.kind}. */\n` +
        `    ${key}?: ${ts} | null;\n`
    );
}

/**
 * Distinct (widget, property) PAIRS — not declaration sites.
 *
 * The two differ, and the header said so with the wrong one: three properties are
 * declared on both a class and one of its own interfaces, so a naive sum reports
 * 6771 where a reader counting what they can write reports 6768. `orientation`
 * twice, `name` once. Harmless for the emitted TYPES — all three carry identical
 * text, which is why no `Omit` was needed — but the number is quoted in the ADR
 * and the README, where a silent three-slot disagreement reads as a bug in one of
 * the three.
 */
const countSlots = (model: SurfaceModel): number => {
    const own = new Map<string, readonly string[]>();
    for (const d of model.declarations.values())
        own.set(
            d.gtype,
            d.props.map((p) => p.camel),
        );
    let n = 0;
    for (const [, chain] of model.closure) {
        const seen = new Set<string>();
        for (const gtype of chain) for (const name of own.get(gtype) ?? []) seen.add(name);
        n += seen.size;
    }
    return n;
};

const countDistinct = (model: SurfaceModel): number => {
    const names = new Set<string>();
    for (const d of model.declarations.values()) for (const p of d.props) names.add(p.kebab);
    return names.size;
};

/**
 * Emit the data the runtime cross-check reads.
 *
 * `.mts`, so it is EXCLUDED from the library build (`src/**​/*.{ts,js}`) and never
 * ships — the same trick `testing/gate.mts` uses. It exists to let a spec ask the
 * installed GTK whether the generated surface is true: every property present as a
 * writable ParamSpec, every signal resolvable by `GObject.signal_lookup`, every
 * enum nick resolvable through the host's own enum lookup. Shipping this as
 * runtime data would make it a second source for what `paramSpecs()` already
 * answers from the class that is actually installed.
 */
export function emitSurfaceData(model: SurfaceModel, provenance: string): EmittedFile {
    const record = (rows: string[]): string => (rows.length === 0 ? '{}' : `{\n${rows.join('\n')}\n}`);
    const ownProps: string[] = [];
    const ownSignals: string[] = [];
    for (const d of [...model.declarations.values()].sort((a, b) => (a.gtype < b.gtype ? -1 : 1))) {
        if (d.props.length > 0) ownProps.push(`    ${d.gtype}: [${d.props.map((p) => `'${p.kebab}'`).join(', ')}],`);
        if (d.signals.length > 0)
            ownSignals.push(`    ${d.gtype}: [${d.signals.map((s) => `'${s.signal}'`).join(', ')}],`);
    }
    // FROM `closure`, NOT FROM `widgets`. These two were the same list until @girs 5.2.0:
    // `DECLS` was the widget vocabulary, so every declaration was also a mountable tag.
    // ts-for-gir #474 widened it to every declaration a UI file can instantiate, and the
    // two questions came apart — `widgets` is now the MOUNTABLE set (a widget, or a
    // non-widget that holds one), while this map is the vocabulary carried VERBATIM, which
    // is what `generator.spec.ts` compares field by field against `@girs`. Reading it off
    // `widgets` silently dropped 175 declarations from the artefact while every tag stayed
    // correct.
    const decls = [...model.closure]
        .sort((a, b) => (a[0] < b[0] ? -1 : 1))
        .map(([gtype, chain]) => `    ${gtype}: [${chain.map((c) => `'${c}'`).join(', ')}],`);
    const nicks = [...model.enumNicks]
        .sort((a, b) => (a[0] < b[0] ? -1 : 1))
        .map(([gtype, members]) => `    ${gtype}: [${members.map((m) => `'${m}'`).join(', ')}],`);
    const flagNicks = [...model.flagNicks]
        .sort((a, b) => (a[0] < b[0] ? -1 : 1))
        .map(([gtype, members]) => `    ${gtype}: [${members.map((m) => `'${m}'`).join(', ')}],`);
    const tags = model.widgets.map((w) => `    ${w.gtype}: '${tagOf(w.gtype)}',`);
    const since: string[] = [];
    for (const d of [...model.declarations.values()].sort((a, b) => (a.gtype < b.gtype ? -1 : 1))) {
        if (d.since) since.push(`    ${d.gtype}: '${d.since}',`);
        for (const p of d.props) if (p.since) since.push(`    '${d.gtype}.${p.kebab}': '${p.since}',`);
        for (const sig of d.signals) if (sig.since) since.push(`    '${d.gtype}::${sig.signal}': '${sig.since}',`);
    }

    const text = `${HEADER(
        `Test-only mirror of the generated surface — NOT shipped (a \`.mts\` file is
// outside the library build glob). Read by \`generated.spec.ts\`, which asks the
// INSTALLED GTK whether every name here is real.`,
        provenance,
    )}

/** Declaration GType -> its OWN writable properties, kebab-spelled as GObject knows them. */
export const OWN_PROPS: Readonly<Record<string, readonly string[]>> = ${record(ownProps)};

/** Declaration GType -> its OWN signals. */
export const OWN_SIGNALS: Readonly<Record<string, readonly string[]>> = ${record(ownSignals)};

/** Widget GType -> every declaration its members come from, self first. */
export const DECLS: Readonly<Record<string, readonly string[]>> = ${record(decls)};

/** Enum GType -> the nicks the surface offers. */
export const ENUM_NICKS: Readonly<Record<string, readonly string[]>> = ${record(nicks)};

/**
 * Bitfield GType -> the member nicks the surface offers, for the bitfields a property
 * of this surface carries.
 *
 * Derived from \`FLAG_VALUES\`' KEYS rather than from a nick list, because \`@girs\`
 * publishes none for a bitfield — GObject resolves no nick SET, so the vocabulary says
 * nothing about sets and the members keep their names in the value table. Held against
 * the installed library the same way \`ENUM_NICKS\` is.
 */
export const FLAG_NICKS: Readonly<Record<string, readonly string[]>> = ${record(flagNicks)};

/** Widget GType -> its kebab tag. */
export const TAGS: Readonly<Record<string, string>> = ${record(tags)};

/**
 * \`Type.property\` / \`Type::signal\` -> the release that introduced it.
 *
 * This is what keeps the runtime cross-check honest across a version gap instead
 * of needing an allowlist. Measured on the pinned GIR against gtk 4.22.4:
 * \`GtkApplicationWindow::save-state\` is in the surface and NOT in the installed
 * library, because it arrived in 4.24. Without a since-map the only options are to
 * stop checking signals or to hard-code two names; with it, the rule is exact —
 * a member the installed library lacks must be explained by a version newer than
 * the one running, and anything else is a real defect.
 */
export const SINCE: Readonly<Record<string, string>> = ${record(since)};
`;
    return { path: 'surface-data.mts', text };
}
