// Type declaration for `@gjsify/adwaita-web/style.css` (the compiled stylesheet
// at dist/adwaita-web.css, generated by `build:scss`).
//
// NOTE: `import '@gjsify/adwaita-web'` already self-applies this stylesheet, so a
// separate style.css import is usually unnecessary — and under a CSS-pipeline
// bundler (e.g. Vite) it injects the same rules a SECOND time. Reach for it only
// when you want the stylesheet WITHOUT the JS auto-injection (e.g. a static
// <link>, or SSR-extracted CSS).
//
// Two consumption modes are supported:
//  - side-effect import (`import '@gjsify/adwaita-web/style.css'`) under a real
//    CSS pipeline (e.g. Vite injects/extracts the stylesheet);
//  - default import (`import css from '@gjsify/adwaita-web/style.css'`) under a
//    gjsify `--app browser` build, where the css-as-string plugin turns it into
//    a string the app injects into a <style> element.
declare const css: string;
export default css;
