// Applying an Adwaita accent at runtime on NativeScript.
//
// The stylesheet is generated by the pure `accent-theme.ts`; this file is the one
// call that cannot be tested off-device, because `Application` is a bare
// `@nativescript/core` import.
//
// APPEND-ONLY IS THE WHOLE CONSTRAINT. `Application.addCss` adds rules; it cannot
// remove them. So switching accents leaves the previous override in the sheet, and
// the newest one wins only because it comes last — which it does. Going BACK to the
// desktop's accent is therefore not "remove the override" but "append the default
// one again", which is what {@link clearAdwaitaNsAccent} does.
//
// Reference: refs/libadwaita/src/adw-accent-color.c
// Copyright (c) GNOME contributors (libadwaita). LGPLv2.1+.

import { Application } from '@nativescript/core';
import { ADW_DEFAULT_ACCENT_COLOR, type AdwAccentColorName } from '@gjsify/adwaita-core';
import { adwaitaNsAccentCss } from './accent-theme.js';

/** Repaint every accent-coloured rule in the theme for `accent`. */
export function applyAdwaitaNsAccent(accent: AdwAccentColorName): void {
    Application.addCss(adwaitaNsAccentCss(accent));
}

/**
 * Go back to libadwaita's default blue.
 *
 * NOT a removal: `addCss` is append-only, so the earlier override is still in the
 * sheet and the only way to beat it is to append a later one. That also means this
 * cannot restore a DESKTOP accent the way the GTK renderer can — Android has no
 * system accent for the theme to follow, so the default IS the fallback here.
 */
export function clearAdwaitaNsAccent(): void {
    Application.addCss(adwaitaNsAccentCss(ADW_DEFAULT_ACCENT_COLOR));
}
