// The `bin/<name>` entry a package installs.
//
// It derives its own prefix at runtime instead of having one baked in. That is
// what lets ONE staged payload become a `.deb` under `/usr`, an `.rpm` under
// `/usr` and a Flatpak under `/app` (ADR 0024 § 3) — a baked path would force a
// payload per format and collapse the whole design back into N packagers.
//
// `XDG_DATA_DIRS` is prepended for the same reason. Under `/usr` it is already
// on the list and the line is a no-op; installed anywhere else (`/opt`, a
// `--prefix=$HOME/.local` tree, a relocated Flatpak) it is what makes the
// staged icons, the desktop entry and the compiled GSettings schemas findable.
// Getting that from the launcher rather than from the app keeps the app free of
// install-layout knowledge.

import type { ShipSettings } from './types.js';

/** POSIX-shell single-quote: the only escape inside `'…'` is `'\''`. */
function shellQuote(value: string): string {
    return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Render the launcher for a GJS application.
 *
 * `bundleRelPath` is the bundle's path inside `lib/<binaryName>/`.
 */
export function renderLauncher(settings: ShipSettings, bundleRelPath: string): string {
    const lib = `"$prefix"/lib/${settings.binaryName}`;
    const args = settings.execArgs.map(shellQuote).join(' ');
    return [
        '#!/bin/sh',
        '# Generated by `gjsify ship` — do not edit.',
        'set -e',
        'self=$(readlink -f "$0")',
        'prefix=$(dirname "$(dirname "$self")")',
        'XDG_DATA_DIRS="$prefix/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"',
        'export XDG_DATA_DIRS',
        `exec gjs -m ${lib}/${bundleRelPath}${args ? ` ${args}` : ''} "$@"`,
        '',
    ].join('\n');
}
