// The `bin/<name>` entry a package installs.
//
// It execs ONE interpreter, named by `settings.app`, and `deriveDepends` seeds
// the dependency from that same field. That coupling is the point rather than a
// convenience: the first cut of the Node half derived "this payload needs Node"
// from a FILENAME (`*.node.mjs` anywhere in the staged tree) while this function
// still execed gjs unconditionally, and the two disagreed in both directions —
// a `--app gjs` project that merely built a Node bundle beside its GJS one got
// `Depends: gjs (>= 1.86), nodejs (>= 24)` and a launcher running the GJS
// bundle, and `>= 24` is unsatisfiable on every current DEB stable, so a working
// package became uninstallable for a reason its author never opted into.
// `assertLauncherMatchesInterpreter` in `utils/ship/payload.ts` re-reads this
// line off the STAGED file and is the gate that keeps the two from drifting
// apart again.
//
// It derives its own prefix at runtime instead of having one baked in. That is
// what lets ONE staged payload become a `.deb` under `/usr`, an `.rpm` under
// `/usr` and a Flatpak under `/app` (ADR 0024 § 3) — a baked path would force a
// payload per format and collapse the whole design back into N packagers.
//
// `XDG_DATA_DIRS` is prepended for the same reason. Under `/usr` it is already
// on the list and the line is a no-op; installed anywhere else (`/opt`, a
// `--prefix=$HOME/.local` tree, a relocated Flatpak) it is what makes the
// staged icons, the desktop entry and the compiled GSettings schemas findable.
// Getting that from the launcher rather than from the app keeps the app free of
// install-layout knowledge.

import type { ShipSettings } from './types.js';

/** POSIX-shell single-quote: the only escape inside `'…'` is `'\''`. */
function shellQuote(value: string): string {
    return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Render the launcher.
 *
 * `bundleRelPath` is the bundle's path inside `lib/<binaryName>/`.
 */
export function renderLauncher(settings: ShipSettings, bundleRelPath: string): string {
    const lib = `"$prefix"/lib/${settings.binaryName}`;
    const args = settings.execArgs.map(shellQuote).join(' ');
    const lines = [
        '#!/bin/sh',
        '# Generated by `gjsify ship` — do not edit.',
        'set -e',
        'self=$(readlink -f "$0")',
        'prefix=$(dirname "$(dirname "$self")")',
        'XDG_DATA_DIRS="$prefix/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"',
        'export XDG_DATA_DIRS',
    ];

    // Typelibs the package carries itself (see `gjsify.ship.bundledTypelibs`). PREPENDED, not
    // replacing: an app that ships `Gwebgl` still needs the system `Gtk`, and clobbering the path
    // would trade one missing namespace for all the others. Only emitted when something was
    // actually staged — an empty `GI_TYPELIB_PATH` entry makes GI search a directory that is not
    // there, on every import, forever.
    if (settings.typelibFiles.length > 0) {
        const giDir = '"$prefix"/lib/' + settings.binaryName + '/gi';
        for (const variable of ['GI_TYPELIB_PATH', 'LD_LIBRARY_PATH']) {
            // `${VAR:+:$VAR}` appends the existing value with a separator ONLY when it is set —
            // a plain `:$VAR` leaves a trailing colon, which both loaders read as "and the current
            // directory", and a package that silently adds `.` to a library path is a bad package.
            lines.push(`${variable}=${giDir}\${${variable}:+:$${variable}}`, `export ${variable}`);
        }
    }

    // Where the app's gettext catalogues landed. `bindtextdomain` takes a DIRECTORY and there is no
    // standard environment variable it reads on its own (`TEXTDOMAINDIR` is honoured by the gettext
    // command-line tools, not by the library), so the prefix has to reach the app somehow. Passing
    // it from the launcher keeps the app free of install-layout knowledge, exactly as XDG_DATA_DIRS
    // above does for icons and schemas — a baked `/usr/share/locale` would be wrong in a Flatpak
    // and in any `--prefix` tree.
    if (settings.localeFiles.length > 0) {
        lines.push('GJSIFY_LOCALE_DIR="$prefix"/share/locale', 'export GJSIFY_LOCALE_DIR');
    }

    // `gjs` needs `-m` to treat the bundle as an ES module; `node` decides from
    // the extension and rejects the flag. The interpreter NAME, not a path: both
    // are found on `PATH`, which is what the emitted dependency guarantees is
    // there — and on Fedora `/usr/bin/node` is an alternatives symlink whose
    // target is whichever stream package won, so hardcoding a path would pin the
    // launcher to a layout the dependency does not promise.
    const interpreter = settings.app === 'node' ? 'node' : 'gjs -m';
    lines.push(`exec ${interpreter} ${lib}/${bundleRelPath}${args ? ` ${args}` : ''} "$@"`, '');
    return lines.join('\n');
}
