// SPDX-License-Identifier: MIT
// What a non-Linux layout carries that only a Linux package makes work.
//
// `linuxInstallDependent` had one caller, zero tests, and a comment claiming its
// rules "cannot drift" from `cacheRefreshCommands`. That claim was measured false:
// pointing one rule at a directory matching nothing silently dropped a file from
// the warning `gjsify ship` prints, and the e2e suite stayed green at exit 0 —
// because it re-derived the expected set from its own regular expression and never
// called this function. The prose was the mechanism, which is to say there was
// none.
//
// Two things replace it. `SHARE` is one constant the four call sites import, so
// the compiler holds them together; and the rule is EXHAUSTIVE rather than an
// allow-list, so a directory nobody classified is reported instead of passing.
// These tests are the second half of that: they call the function.

import { describe, expect, it } from '@gjsify/unit';

import { LAYOUTS } from './layout.js';
import {
    assertLauncherMatchesInterpreter,
    linuxInstallDependent,
    readBinaryArch,
    readLauncherInterpreters,
} from './payload.js';
import { SHARE } from './share-dirs.js';

const at = (...paths: string[]) => paths.map((path) => ({ path }));
const paths = (entries: readonly { path: string }[]) => entries.map((entry) => entry.path);

const APP = { binaryName: 'hello', name: 'Hello' };

/** The exec line `gjsify ship windows` writes once the directory carries an interpreter. */
const WINDOWS_EXEC = '"%HERE%node.exe" "%HERE%app\\app.node.mjs" %*';

/**
 * One `.cmd` launcher, as a payload of exactly the file the reader looks for.
 *
 * CRLF, because that is what `renderLauncher` writes and because a reader that
 * split on `\n` alone would leave a `\r` on every token — which basenames to
 * `node.exe\r` and is vacuous in the same silent way the missing `exec` was.
 */
function cmdLauncher(...commands: string[]) {
    const text = ['@echo off', 'rem Generated by "gjsify ship" - do not edit.', 'setlocal', 'set "HERE=%~dp0"']
        .concat(commands)
        .join('\r\n');
    return [{ path: 'hello.cmd', mode: 0o644, data: new TextEncoder().encode(`${text}\r\n`) }];
}

/** A minimal PE32+ image with one machine constant — the two fields `readBinaryArch` reads. */
function pe(arch: 'x64' | 'arm64' | 'ia32', machine?: number): Uint8Array {
    const machines: Record<string, number> = { ia32: 0x014c, x64: 0x8664, arm64: 0xaa64 };
    const bytes = new Uint8Array(0x80);
    const view = new DataView(bytes.buffer);
    view.setUint16(0, 0x5a4d, true);
    view.setUint32(0x3c, 0x40, true);
    view.setUint32(0x40, 0x00004550, true);
    view.setUint16(0x44, machine ?? (machines[arch] as number), true);
    return bytes;
}

/** One `.app` launcher, as a payload of exactly the file the reader looks for. */
function appLauncher(execLine: string) {
    return [
        {
            path: 'Hello.app/Contents/MacOS/hello',
            mode: 0o755,
            data: new TextEncoder().encode(`#!/bin/sh\nset -e\n${execLine}\n`),
        },
    ];
}

export default async () => {
    await describe('readLauncherInterpreters: the launcher a `.app` carries', async () => {
        await it('reads a QUOTED, layout-relative interpreter back to its bare name', () => {
            // #1354 M2b's launcher execs `"$here/node"` — the interpreter the
            // bundle carries, named by a path because macOS has no system Node to
            // find on `PATH`. This reader used to split that token on `/` with the
            // quotes still attached and answer `node"`, which is neither known
            // interpreter, so `assertLauncherMatchesInterpreter` took its "a
            // program that is neither" branch and PASSED. Not a wrong answer — a
            // vacuous one, on exactly the layout that made the check matter.
            expect(
                readLauncherInterpreters(
                    appLauncher('exec "$here/node" "$contents/Resources/lib/app.node.mjs" "$@"'),
                    LAYOUTS.darwin,
                    APP,
                ),
            ).toStrictEqual(['node']);
            // The unquoted and single-quoted spellings of the same thing.
            expect(readLauncherInterpreters(appLauncher('exec $here/node "$b"'), LAYOUTS.darwin, APP)).toStrictEqual([
                'node',
            ]);
            expect(
                readLauncherInterpreters(appLauncher('exec \'/opt/x/gjs\' -m "$b"'), LAYOUTS.darwin, APP),
            ).toStrictEqual(['gjs']);
        });

        await it('still refuses the mismatch it exists to catch, through a carried interpreter', () => {
            // The check is only worth having if it fires. A bundle whose launcher
            // execs the carried `node` while the package declares `gjs` installs
            // cleanly and fails at first launch — and the quoting fix above is
            // what keeps this reachable at all.
            expect(() =>
                assertLauncherMatchesInterpreter(
                    appLauncher('exec "$here/node" "$contents/Resources/lib/app.node.mjs" "$@"'),
                    LAYOUTS.darwin,
                    APP,
                    'gjs',
                ),
            ).toThrow('execs `node`');
            assertLauncherMatchesInterpreter(
                appLauncher('exec "$here/node" "$contents/Resources/lib/app.node.mjs" "$@"'),
                LAYOUTS.darwin,
                APP,
                'node',
            );
        });

        await it('strips only a SURROUNDING pair, never a quote inside a word', () => {
            // A shell token is `"…"`, `'…'` or bare. Removing a lone quote from
            // the middle of a word would be this reader guessing at a syntax it
            // does not parse, and the guess would name a program nobody execs.
            expect(readLauncherInterpreters(appLauncher('exec no"de "$b"'), LAYOUTS.darwin, APP)).toStrictEqual([
                'no"de',
            ]);
        });
    });

    await describe('readLauncherInterpreters: the `.cmd` a program directory carries', async () => {
        await it('reads the cmd dialect back, where the POSIX rules read NOTHING', () => {
            // THREE ways the POSIX path is vacuous on a `.cmd`, and each on its own
            // is enough to make `assertLauncherMatchesInterpreter` pass over a
            // launcher that runs the wrong interpreter:
            //
            //   1. batch has no `exec`, so the `\nexec ` scan matches nothing at all
            //      and the reader returns `[]` — the value the assertion treats as
            //      "nothing to check";
            //   2. `%~dp0` ALREADY ENDS IN A SEPARATOR, so `%HERE%node.exe` has no
            //      `/` or `\` to take a basename at;
            //   3. the file is `node.exe` and the declared vocabulary is `node`.
            expect(readLauncherInterpreters(cmdLauncher(WINDOWS_EXEC), LAYOUTS.windows, APP)).toStrictEqual(['node']);
            // A `--app gjs` program directory, and the unquoted spelling.
            expect(
                readLauncherInterpreters(cmdLauncher('gjs -m "%HERE%app\\app.gjs.js" %*'), LAYOUTS.windows, APP),
            ).toStrictEqual(['gjs']);
            // An absolute path with a space in it — `C:\Program Files\…` is the
            // case a naive whitespace split gets wrong, and it is where a Windows
            // program actually lives.
            expect(
                readLauncherInterpreters(
                    cmdLauncher('"C:\\Program Files\\nodejs\\node.exe" "%HERE%app\\a.mjs" %*'),
                    LAYOUTS.windows,
                    APP,
                ),
            ).toStrictEqual(['node']);
        });

        await it('refuses a `.cmd` that runs the interpreter the package does not declare', () => {
            // The whole point of the three rules above. Without them this call
            // returns without throwing — green, having read nothing.
            expect(() =>
                assertLauncherMatchesInterpreter(
                    cmdLauncher('gjs -m "%HERE%app\\app.gjs.js" %*'),
                    LAYOUTS.windows,
                    APP,
                    'node',
                ),
            ).toThrow('execs `gjs`');
            // …and accepts the one `gjsify ship windows` actually writes.
            assertLauncherMatchesInterpreter(cmdLauncher(WINDOWS_EXEC), LAYOUTS.windows, APP, 'node');
        });

        await it('reads no program out of a batch built-in, or out of a comment', () => {
            // `batchCommands` rules lines OUT rather than anchoring on a keyword,
            // because batch has none to anchor on. A `rem` or a `set` naming an
            // interpreter must not become an answer — `set "GJS=..."` is a variable,
            // not an exec — and `@echo` has its `@` stripped before the test.
            expect(
                readLauncherInterpreters(
                    cmdLauncher('@echo node', 'rem gjs -m x', 'set "NODE_OPTIONS=--x"', 'if defined gjs (echo y)'),
                    LAYOUTS.windows,
                    APP,
                ),
            ).toStrictEqual([]);
        });

        await it('leaves `.cmd` and `.bat` unresolved, and an expansion-only token too', () => {
            // Only `.exe` comes off: PATHEXT makes `node` and `node.exe` the same
            // program, while a `.cmd` is a batch file whose contents this reader has
            // not read — resolving `node.cmd` to `node` would be a claim about a
            // script. And a token that is nothing but `%NODE%` strips to empty,
            // which is `null` rather than a guess.
            expect(readLauncherInterpreters(cmdLauncher('"%HERE%node.cmd" x'), LAYOUTS.windows, APP)).toStrictEqual([
                'node.cmd',
            ]);
            expect(readLauncherInterpreters(cmdLauncher('%NODE% x'), LAYOUTS.windows, APP)).toStrictEqual([]);
        });
    });

    await describe('readBinaryArch: PE', async () => {
        await it('reads the COFF machine of a PE image, which used to be silent', () => {
            // The one layout whose native format IS PE is the one this check could
            // not fire for: `readBinaryArch` recognised `MZ` and stopped, so
            // `assertPayloadMatchesArch` was VACUOUS over a Windows program
            // directory carrying `node.exe` and a gvsbuild DLL closure — the exact
            // shape #1354 M2b made non-vacuous for darwin.
            expect(readBinaryArch(pe('x64'))).toBe('x64');
            expect(readBinaryArch(pe('arm64'))).toBe('arm64');
            expect(readBinaryArch(pe('ia32'))).toBe('ia32');
        });

        await it('stays silent on an MZ it cannot follow, and on a machine it has no name for', () => {
            // `null` is SILENT — it means "cannot tell", never "mismatch" — so the
            // truncated stub and the unknown constant must not become refusals.
            // `packers.spec.ts` has asserted the first of these since before PE was
            // parsed at all, and it still holds.
            expect(readBinaryArch(Uint8Array.from([0x4d, 0x5a, ...Array.from({ length: 18 }, () => 0)]))).toBe(null);
            expect(readBinaryArch(pe('x64', 0x0166))).toBe(null);
            // An `MZ` whose `e_lfanew` points past the end of the file — `e_lfanew`
            // is 0x40 here, so cutting at 0x44 leaves the offset readable and the
            // header it names unreachable.
            expect(readBinaryArch(pe('x64').subarray(0, 0x44))).toBe(null);
        });
    });

    await describe('linuxInstallDependent', async () => {
        await it('names every share/ directory whose Linux correctness is an install step', () => {
            const carried = linuxInstallDependent(
                at(
                    `${SHARE.schemas}/org.example.App.gschema.xml`,
                    `${SHARE.mime}/org.example.App.xml`,
                    `${SHARE.icons}/scalable/apps/org.example.App.svg`,
                    `${SHARE.applications}/org.example.App.desktop`,
                    `${SHARE.metainfo}/org.example.App.metainfo.xml`,
                ),
            );
            expect(carried.length).toBe(5);
            // The schema comes FIRST and is the only `aborts`: every launcher
            // exports XDG_DATA_DIRS at the staged `share/`, so a schema directory
            // with no `gschemas.compiled` makes `g_settings_new()` abort. The
            // other four merely do nothing, and ranking all five alike buried it.
            expect(carried[0]?.path).toBe(`${SHARE.schemas}/org.example.App.gschema.xml`);
            expect(carried[0]?.verdict).toBe('aborts');
            expect(carried.filter((entry) => entry.verdict === 'aborts').length).toBe(1);
            expect(carried.filter((entry) => entry.verdict === 'inert').length).toBe(4);
        });

        await it('reports a share/ directory nothing classifies, instead of passing it', () => {
            // The direction the allow-list version got wrong. A D-Bus service file
            // added through `gjsify.ship.extraFiles` is meaningful on Linux only
            // because the package installs it into a system prefix; the closed
            // list said "carries 5 file(s)" for a payload carrying six.
            const carried = linuxInstallDependent(at('share/dbus-1/services/org.example.App.service'));
            expect(carried.length).toBe(1);
            expect(carried[0]?.verdict).toBe('unknown');
            expect(carried[0]?.why).toContain('nothing here classifies');
        });

        await it('lets the one genuinely portable directory through', () => {
            // A `.mo` is read straight off disk by `bindtextdomain`, with no
            // install step anywhere, and every layout's launcher hands over its
            // directory. That is what makes the inverse rule usable rather than
            // a warning on every file.
            expect(linuxInstallDependent(at(`${SHARE.locale}/de/LC_MESSAGES/app.mo`))).toStrictEqual([]);
        });

        await it('ignores everything outside share/', () => {
            expect(linuxInstallDependent(at('bin/app', 'lib/app/gjs.js', 'lib/app/gi/x.typelib'))).toStrictEqual([]);
        });

        await it('respects directory boundaries', () => {
            // `share/mimetypes/` is not inside `share/mime/`, and a `startsWith`
            // on the bare name would say it is — then classify it with the wrong
            // rule and print the wrong reason.
            const carried = linuxInstallDependent(at('share/mimetypes/x.xml'));
            expect(paths(carried)).toStrictEqual(['share/mimetypes/x.xml']);
            expect(carried[0]?.verdict).toBe('unknown');
        });
    });
};
