// Build script for @gjsify/adwaita-web stylesheet.
// 1. Resolve symbolic icons from @gjsify/adwaita-icons and write _icons.generated.scss.
// 2. Compile scss/adwaita-skin.scss to dist/adwaita-web.css using the sass npm package.

import { compile } from 'sass';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
    contactNewSymbolic,
    documentEditSymbolic,
    editPasteSymbolic,
    goDownSymbolic,
    goHomeSymbolic,
    goNextSymbolic,
    goPreviousSymbolic,
    listAddSymbolic,
    openMenuSymbolic,
    sidebarShowSymbolic,
    systemSearchSymbolic,
    viewConcealSymbolic,
    viewRefreshSymbolic,
    viewRevealSymbolic,
} from '@gjsify/adwaita-icons/actions';
import { cameraPhotoSymbolic, networkWirelessSymbolic } from '@gjsify/adwaita-icons/devices';
import { folderSymbolic, userTrashSymbolic } from '@gjsify/adwaita-icons/places';
import { avatarDefaultSymbolic, mailUnreadSymbolic, starredSymbolic } from '@gjsify/adwaita-icons/status';
import { toDataUri } from '@gjsify/adwaita-icons/utils';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
const scssDir = resolve(pkgRoot, 'scss');
const distDir = resolve(pkgRoot, 'dist');

// --- 1. Generate _icons.generated.scss -------------------------------------
// Single source of truth: a CSS `--icon-<name>` custom property AND the matching
// `.adw-icon--<name>` mask class are both generated from this map, so adding an
// icon used by a component or story is one entry here. Names are the libadwaita
// symbolic names with the `-symbolic` suffix dropped.
const ICONS = {
    'edit-paste': editPasteSymbolic,
    'go-down': goDownSymbolic,
    'sidebar-show': sidebarShowSymbolic,
    'go-previous': goPreviousSymbolic,
    'go-next': goNextSymbolic,
    'view-refresh': viewRefreshSymbolic,
    'open-menu': openMenuSymbolic,
    'go-home': goHomeSymbolic,
    'list-add': listAddSymbolic,
    'network-wireless': networkWirelessSymbolic,
    folder: folderSymbolic,
    starred: starredSymbolic,
    'system-search': systemSearchSymbolic,
    'contact-new': contactNewSymbolic,
    'mail-unread': mailUnreadSymbolic,
    'avatar-default': avatarDefaultSymbolic,
    'camera-photo': cameraPhotoSymbolic,
    'user-trash': userTrashSymbolic,
    'view-reveal': viewRevealSymbolic,
    'view-conceal': viewConcealSymbolic,
    'document-edit': documentEditSymbolic,
};

const iconVars = Object.entries(ICONS)
    .map(([name, svg]) => `  --icon-${name}: ${toDataUri(svg)};`)
    .join('\n');
const iconClasses = Object.keys(ICONS)
    .map(
        (name) =>
            `.adw-icon--${name} {\n  mask-image: var(--icon-${name});\n  -webkit-mask-image: var(--icon-${name});\n}`,
    )
    .join('\n\n');

const iconPartial = `// _icons.generated.scss — auto-generated by scripts/build-scss.mjs
// DO NOT EDIT — regenerated on every build from @gjsify/adwaita-icons.

:root {
${iconVars}
}

${iconClasses}
`;

writeFileSync(resolve(scssDir, '_icons.generated.scss'), iconPartial);
console.log(`✓ Generated scss/_icons.generated.scss (${Object.keys(ICONS).length} icons)`);

// --- 2. Compile SCSS -------------------------------------------------------
const entryPoint = resolve(scssDir, 'adwaita-skin.scss');
const result = compile(entryPoint, {
    style: 'expanded',
    sourceMap: true,
    sourceMapIncludeSources: true,
});

mkdirSync(distDir, { recursive: true });

const cssOut = resolve(distDir, 'adwaita-web.css');
const mapOut = resolve(distDir, 'adwaita-web.css.map');

writeFileSync(cssOut, `${result.css}\n/*# sourceMappingURL=adwaita-web.css.map */\n`);
writeFileSync(mapOut, JSON.stringify(result.sourceMap));

console.log(`✓ Compiled ${entryPoint} → ${cssOut}`);

// --- 3. Inline the compiled CSS as a JS string ----------------------------
// `src/styles.generated.ts` lets the JS entry self-apply the stylesheet via a
// <style> element (see src/index.ts). This is bundler-independent — unlike a
// `.css` import, which a gjsify `--app browser` build turns into a string that
// a side-effect import would silently discard (leaving the app unstyled).
const stylesModule = `// styles.generated.ts — auto-generated by scripts/build-scss.mjs.
// DO NOT EDIT — the compiled adwaita-web stylesheet, inlined so the JS entry can
// self-apply it on import regardless of the consumer's bundler.
export const ADWAITA_WEB_CSS = ${JSON.stringify(result.css)};
`;
writeFileSync(resolve(pkgRoot, 'src', 'styles.generated.ts'), stylesModule);
console.log('✓ Generated src/styles.generated.ts');
