// Build script for @gjsify/adwaita-web stylesheet.
// 1. Resolve symbolic icons from @gjsify/adwaita-icons and write _icons.generated.scss.
// 2. Compile scss/adwaita-skin.scss to dist/adwaita-web.css using the sass npm package.

import { compile } from 'sass';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { editPasteSymbolic, goDownSymbolic, sidebarShowSymbolic } from '@gjsify/adwaita-icons/actions';
import { toDataUri } from '@gjsify/adwaita-icons/utils';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
const scssDir = resolve(pkgRoot, 'scss');
const distDir = resolve(pkgRoot, 'dist');

// --- 1. Generate _icons.generated.scss -------------------------------------
const iconPartial = `// _icons.generated.scss — auto-generated by scripts/build-scss.mjs
// DO NOT EDIT — regenerated on every build from @gjsify/adwaita-icons.

:root {
  --icon-edit-paste: ${toDataUri(editPasteSymbolic)};
  --icon-go-down: ${toDataUri(goDownSymbolic)};
  --icon-sidebar-show: ${toDataUri(sidebarShowSymbolic)};
}
`;

writeFileSync(resolve(scssDir, '_icons.generated.scss'), iconPartial);
console.log('✓ Generated scss/_icons.generated.scss');

// --- 2. Compile SCSS -------------------------------------------------------
const entryPoint = resolve(scssDir, 'adwaita-skin.scss');
const result = compile(entryPoint, {
    style: 'expanded',
    sourceMap: true,
    sourceMapIncludeSources: true,
});

mkdirSync(distDir, { recursive: true });

const cssOut = resolve(distDir, 'adwaita-web.css');
const mapOut = resolve(distDir, 'adwaita-web.css.map');

writeFileSync(cssOut, `${result.css}\n/*# sourceMappingURL=adwaita-web.css.map */\n`);
writeFileSync(mapOut, JSON.stringify(result.sourceMap));

console.log(`✓ Compiled ${entryPoint} → ${cssOut}`);
