#!/usr/bin/env node
// Emit one refusing export per React Native name this layer does not answer yet.
//
// GENERATED AND COMMITTED, like the widget table (ADR 0028's reasoning applies
// unchanged): a bundler needs static export names to resolve an import at all, so
// these cannot be produced by a loop at runtime. Committing the output is what makes
// `import { FlatList } from 'react-native'` resolve to something that can explain
// itself, instead of to a `MISSING_EXPORT` that can only say the name is absent.
//
// Run: `gjsify workspace @gjsify/react-native run generate`
// The spec asserts the file on disk matches what this would emit, so a stale
// generated file fails a test rather than shipping.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = dirname(dirname(fileURLToPath(import.meta.url)));
const TABLE = join(PKG, 'src/support-table.ts');
const OUT = join(PKG, 'src/generated/unsupported-exports.ts');
const ROUTER_OUT = join(PKG, 'src/generated/unsupported-router-exports.ts');
const README = join(PKG, 'README.md');
export const README_BEGIN = '<!-- BEGIN generated support table -->';
export const README_END = '<!-- END generated support table -->';
export const ROUTER_BEGIN = '<!-- BEGIN generated router support table -->';
export const ROUTER_END = '<!-- END generated router support table -->';

/**
 * The two tables this file generates from, and where each one's output goes.
 *
 * TWO, because `expo-router`'s names are a different package's surface and
 * `check-rn-surface.mjs` holds the first table's key set against react-native's own
 * exports — a `router` row in there would fail that gate for being real. Everything
 * downstream (the refusing exports, the README section) is the same machinery
 * pointed at a second declaration, which is why this is a parameter and not a copy.
 */
export const TABLES = [
    {
        declaration: 'SUPPORT_TABLE',
        out: OUT,
        module: '../unsupported.js',
        begin: README_BEGIN,
        end: README_END,
        label: 'React Native',
    },
    {
        declaration: 'ROUTER_SUPPORT_TABLE',
        out: ROUTER_OUT,
        module: '../unsupported.js',
        begin: ROUTER_BEGIN,
        end: ROUTER_END,
        label: 'expo-router',
    },
];

/**
 * The source slice one table literal occupies.
 *
 * Anchored on `export const <NAME>: Readonly`, not on `<NAME>: Readonly`: the router
 * table's name ENDS with the first one's, so a bare substring search finds the wrong
 * declaration for whichever table is asked for second.
 */
function tableBody(source, declaration) {
    const start = source.indexOf(`export const ${declaration}: Readonly`);
    if (start === -1) throw new Error(`${declaration} declaration not found`);
    const end = source.indexOf('\n};', start);
    if (end === -1) throw new Error(`${declaration} literal is not terminated`);
    return source.slice(start, end);
}

/** Names and statuses, from the table's source. Same parse as `check-rn-surface.mjs`. */
export function readEntries(source, declaration = 'SUPPORT_TABLE') {
    const body = tableBody(source, declaration);
    const entries = [];
    const lines = body.split('\n');
    for (let i = 0; i < lines.length; i++) {
        const key = /^ {4}([A-Za-z_$][A-Za-z0-9_$]*):\s*\{/.exec(lines[i]);
        if (!key) continue;
        // The status is on the same line for a one-liner, or within the entry's
        // own block for a multi-line one. Bounded by the next four-space key.
        let status = null;
        for (let j = i; j < lines.length; j++) {
            if (j > i && /^ {4}[A-Za-z_$][A-Za-z0-9_$]*:\s*\{/.test(lines[j])) break;
            const found = /status:\s*'([a-z-]+)'/.exec(lines[j]);
            if (found) {
                status = found[1];
                break;
            }
        }
        if (status === null) throw new Error(`no status found for ${key[1]}`);
        entries.push({ name: key[1], status });
    }
    return entries;
}

export function render(entries, label = 'React Native') {
    const refused = entries.filter((e) => e.status !== 'supported' && e.status !== 'partial');
    const lines = [
        '// GENERATED by scripts/generate-exports.mjs — do not edit.',
        '//',
        `// One export per ${label} name this layer does not answer yet, each a value`,
        '// that refuses with the support table’s own sentence. Why these exist at all, and',
        '// why they are generated rather than looped: see the generator and `unsupported.ts`.',
        '',
        "import { unsupported } from '../unsupported.js';",
        '',
    ];
    for (const { name } of refused) {
        lines.push(`export const ${name} = unsupported('${name}');`);
    }
    lines.push('');
    return lines.join('\n');
}

/** Statuses in the order a reader wants to see them, with a heading each. */
const SECTIONS = [
    ['supported', 'Supported'],
    ['partial', 'Supported, with named limits'],
    ['planned', 'Planned'],
    ['no-desktop-meaning', 'No meaning on a desktop window'],
    ['refused', 'Refused'],
    ['not-reachable', 'Not reachable in this build chain'],
];

/**
 * The README's support section — the THIRD reader of the table the ADR promises.
 *
 * Generated between markers rather than written, for the reason the whole mechanism
 * exists: a hand-kept copy of this is the one that drifts, and the drifted one is
 * what a consumer reads before they file an issue.
 */
export function renderReadmeTable(entries, table, begin = README_BEGIN, end = README_END) {
    const out = [begin, ''];
    for (const [status, heading] of SECTIONS) {
        const rows = entries.filter((e) => e.status === status);
        if (rows.length === 0) continue;
        out.push(`### ${heading} (${rows.length})`, '', '| export | tier | GTK | why |', '|---|---|---|---|');
        for (const { name } of rows) {
            const entry = table[name];
            // A `|` in a cell ENDS the cell. `Platform`'s reason is
            // `OS is "linux" | "macos" | "windows"`, which silently split one row
            // into four columns and pushed the reason out of the table — visible
            // only to a reader, which is the audience this section has.
            const cell = (text) => String(text).replaceAll('|', '\\|');
            out.push(
                `| \`${name}\` | ${cell(entry.tier ?? '—')} | ${cell(entry.gtk ?? '—')} | ${cell(entry.reason)} |`,
            );
        }
        out.push('');
    }
    out.push(end);
    return out.join('\n');
}

/** The table as data, from source — statuses, tiers, gtk and reasons. */
export function readTable(source, declaration = 'SUPPORT_TABLE') {
    const body = tableBody(source, declaration);
    const table = {};
    const lines = body.split('\n');
    for (let i = 0; i < lines.length; i++) {
        const key = /^ {4}([A-Za-z_$][A-Za-z0-9_$]*):\s*\{/.exec(lines[i]);
        if (!key) continue;
        let block = lines[i];
        for (let j = i + 1; j < lines.length; j++) {
            if (/^ {4}[A-Za-z_$][A-Za-z0-9_$]*:\s*\{/.test(lines[j])) break;
            block += '\n' + lines[j];
        }
        const pick = (field) => {
            const m = new RegExp(`${field}:\\s*'((?:[^'\\\\]|\\\\.)*)'`).exec(block);
            return m ? m[1].replace(/\\'/g, "'").replace(/\\n/g, ' ') : undefined;
        };
        table[key[1]] = { status: pick('status'), tier: pick('tier'), gtk: pick('gtk'), reason: pick('reason') };
    }
    return table;
}

export function spliceReadme(readme, block, begin = README_BEGIN, end = README_END) {
    const from = readme.indexOf(begin);
    const to = readme.indexOf(end);
    if (from === -1 || to === -1) throw new Error(`README is missing the ${begin} markers`);
    return readme.slice(0, from) + block + readme.slice(to + end.length);
}

if (import.meta.url === `file://${process.argv[1]}`) {
    const source = readFileSync(TABLE, 'utf8');
    let readme = readFileSync(README, 'utf8');
    for (const spec of TABLES) {
        const entries = readEntries(source, spec.declaration);
        const output = render(entries, spec.label);
        mkdirSync(dirname(spec.out), { recursive: true });
        writeFileSync(spec.out, output);
        const refused = output.split('\n').filter((l) => l.startsWith('export const')).length;
        const table = readTable(source, spec.declaration);
        readme = spliceReadme(readme, renderReadmeTable(entries, table, spec.begin, spec.end), spec.begin, spec.end);
        console.log(
            `generate-exports: ${refused} refusing export(s) of ${entries.length} ${spec.label} name(s) → ${spec.out.slice(spec.out.indexOf('src/'))}`,
        );
    }
    writeFileSync(README, readme);
    console.log(`generate-exports: ${TABLES.length} support section(s) → README.md`);
}
