#!/usr/bin/env node
// Emit one refusing export per React Native name this layer does not answer yet.
//
// GENERATED AND COMMITTED, like the widget table (ADR 0028's reasoning applies
// unchanged): a bundler needs static export names to resolve an import at all, so
// these cannot be produced by a loop at runtime. Committing the output is what makes
// `import { FlatList } from 'react-native'` resolve to something that can explain
// itself, instead of to a `MISSING_EXPORT` that can only say the name is absent.
//
// Run: `gjsify workspace @gjsify/react-native run generate`
// The spec asserts the file on disk matches what this would emit, so a stale
// generated file fails a test rather than shipping.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = dirname(dirname(fileURLToPath(import.meta.url)));
const TABLE = join(PKG, 'src/support-table.ts');
const OUT = join(PKG, 'src/generated/unsupported-exports.ts');
const README = join(PKG, 'README.md');
export const README_BEGIN = '<!-- BEGIN generated support table -->';
export const README_END = '<!-- END generated support table -->';

/** Names and statuses, from the table's source. Same parse as `check-rn-surface.mjs`. */
export function readEntries(source) {
    const start = source.indexOf('SUPPORT_TABLE: Readonly');
    const end = source.indexOf('\n};', start);
    const body = source.slice(start, end);
    const entries = [];
    const lines = body.split('\n');
    for (let i = 0; i < lines.length; i++) {
        const key = /^ {4}([A-Za-z_$][A-Za-z0-9_$]*):\s*\{/.exec(lines[i]);
        if (!key) continue;
        // The status is on the same line for a one-liner, or within the entry's
        // own block for a multi-line one. Bounded by the next four-space key.
        let status = null;
        for (let j = i; j < lines.length; j++) {
            if (j > i && /^ {4}[A-Za-z_$][A-Za-z0-9_$]*:\s*\{/.test(lines[j])) break;
            const found = /status:\s*'([a-z-]+)'/.exec(lines[j]);
            if (found) {
                status = found[1];
                break;
            }
        }
        if (status === null) throw new Error(`no status found for ${key[1]}`);
        entries.push({ name: key[1], status });
    }
    return entries;
}

export function render(entries) {
    const refused = entries.filter((e) => e.status !== 'supported' && e.status !== 'partial');
    const lines = [
        '// GENERATED by scripts/generate-exports.mjs — do not edit.',
        '//',
        '// One export per React Native name this layer does not answer yet, each a value',
        '// that refuses with the support table’s own sentence. Why these exist at all, and',
        '// why they are generated rather than looped: see the generator and `unsupported.ts`.',
        '',
        "import { unsupported } from '../unsupported.js';",
        '',
    ];
    for (const { name } of refused) {
        lines.push(`export const ${name} = unsupported('${name}');`);
    }
    lines.push('');
    return lines.join('\n');
}

/** Statuses in the order a reader wants to see them, with a heading each. */
const SECTIONS = [
    ['supported', 'Supported'],
    ['partial', 'Supported, with named limits'],
    ['planned', 'Planned'],
    ['no-desktop-meaning', 'No meaning on a desktop window'],
    ['refused', 'Refused'],
    ['not-reachable', 'Not reachable in this build chain'],
];

/**
 * The README's support section — the THIRD reader of the table the ADR promises.
 *
 * Generated between markers rather than written, for the reason the whole mechanism
 * exists: a hand-kept copy of this is the one that drifts, and the drifted one is
 * what a consumer reads before they file an issue.
 */
export function renderReadmeTable(entries, table) {
    const out = [README_BEGIN, ''];
    for (const [status, heading] of SECTIONS) {
        const rows = entries.filter((e) => e.status === status);
        if (rows.length === 0) continue;
        out.push(`### ${heading} (${rows.length})`, '', '| export | tier | GTK | why |', '|---|---|---|---|');
        for (const { name } of rows) {
            const entry = table[name];
            out.push(`| \`${name}\` | ${entry.tier ?? '—'} | ${entry.gtk ?? '—'} | ${entry.reason} |`);
        }
        out.push('');
    }
    out.push(README_END);
    return out.join('\n');
}

/** The table as data, from source — statuses, tiers, gtk and reasons. */
export function readTable(source) {
    const start = source.indexOf('SUPPORT_TABLE: Readonly');
    const body = source.slice(start, source.indexOf('\n};', start));
    const table = {};
    const lines = body.split('\n');
    for (let i = 0; i < lines.length; i++) {
        const key = /^ {4}([A-Za-z_$][A-Za-z0-9_$]*):\s*\{/.exec(lines[i]);
        if (!key) continue;
        let block = lines[i];
        for (let j = i + 1; j < lines.length; j++) {
            if (/^ {4}[A-Za-z_$][A-Za-z0-9_$]*:\s*\{/.test(lines[j])) break;
            block += '\n' + lines[j];
        }
        const pick = (field) => {
            const m = new RegExp(`${field}:\\s*'((?:[^'\\\\]|\\\\.)*)'`).exec(block);
            return m ? m[1].replace(/\\'/g, "'").replace(/\\n/g, ' ') : undefined;
        };
        table[key[1]] = { status: pick('status'), tier: pick('tier'), gtk: pick('gtk'), reason: pick('reason') };
    }
    return table;
}

export function spliceReadme(readme, block) {
    const begin = readme.indexOf(README_BEGIN);
    const end = readme.indexOf(README_END);
    if (begin === -1 || end === -1) throw new Error('README is missing the generated-support-table markers');
    return readme.slice(0, begin) + block + readme.slice(end + README_END.length);
}

if (import.meta.url === `file://${process.argv[1]}`) {
    const entries = readEntries(readFileSync(TABLE, 'utf8'));
    const output = render(entries);
    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, output);
    const refused = output.split('\n').filter((l) => l.startsWith('export const')).length;
    const table = readTable(readFileSync(TABLE, 'utf8'));
    writeFileSync(README, spliceReadme(readFileSync(README, 'utf8'), renderReadmeTable(entries, table)));
    console.log(
        `generate-exports: ${refused} refusing export(s) of ${entries.length} name(s) → src/generated/unsupported-exports.ts`,
    );
    console.log(`generate-exports: support section for ${entries.length} name(s) → README.md`);
}
