// `gjsify browse [url]` — launch the Adwaita web browser from
// @gjsify/devtools-browser, optionally at a URL. Generates a tiny entry that
// calls runBrowserDevtools(), builds it (`--app gjs --globals auto,dom`), and
// launches it. Dispatch is IN-PROCESS (runCli + runGjsBundle), like
// `gjsify storybook`. `--devtools` sets GJSIFY_DEVTOOLS=1 so @gjsify/devtools
// wires the org.gjsify.Devtools control plane (driveable via `gjsify debug`).

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { Command } from '../types/index.js';

interface BrowseCliOptions {
    url?: string;
    appId?: string;
    title?: string;
    globals?: string;
    out?: string;
    devtools: boolean;
    inspectorPort?: number;
    buildOnly: boolean;
}

interface BrowseConfig {
    applicationId?: string;
    title?: string;
    globals?: string;
    inspectorPort?: number;
}

interface ProjectPackage {
    name?: string;
    gjsify?: { browse?: BrowseConfig };
}

function readPackage(cwd: string): ProjectPackage {
    try {
        return JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8')) as ProjectPackage;
    } catch {
        return {};
    }
}

/** Derive a DBus app id from the package name (mirrored by `gjsify debug`). */
export function deriveBrowserAppId(name?: string): string {
    if (!name) return 'org.gjsify.Browser';
    const slug = name
        .replace(/^@/, '')
        .replace(/[^a-zA-Z0-9]+/g, '.')
        .replace(/^\.+|\.+$/g, '');
    return `org.gjsify.browser.${slug}`;
}

function generateEntry(applicationId: string, url?: string, title?: string, inspectorPort?: number): string {
    const titleLine = title ? `\n    title: ${JSON.stringify(title)},` : '';
    const urlLine = url ? `\n    homeUrl: ${JSON.stringify(url)},` : '';
    const inspectorLine = inspectorPort !== undefined ? `\n    inspectorPort: ${inspectorPort},` : '';
    return `// Auto-generated by \`gjsify browse\` — do not edit by hand.
import { runBrowserDevtools } from '@gjsify/devtools-browser';

await runBrowserDevtools({
    applicationId: ${JSON.stringify(applicationId)},${titleLine}${urlLine}${inspectorLine}
});
`;
}

export const browseCommand: Command<unknown, BrowseCliOptions> = {
    command: 'browse [url]',
    description: 'Launch the Adwaita web browser, optionally pointed at a URL.',
    builder: (yargs) =>
        yargs
            .positional('url', { description: 'Initial URL to load (default: page:welcome)', type: 'string' })
            .option('app-id', {
                description: 'GApplication id (default: gjsify.browse.applicationId or derived from the package name)',
                type: 'string',
            })
            .option('title', { description: 'Window title', type: 'string' })
            .option('globals', {
                description: 'Value for `gjsify build --globals` (default: auto,dom — WebKit/iframe need DOM globals)',
                type: 'string',
            })
            .option('out', {
                description: 'Output bundle path (default: node_modules/.cache/gjsify-browse)',
                type: 'string',
            })
            .option('devtools', {
                description: 'Enable the MCP devtools control plane (sets GJSIFY_DEVTOOLS=1)',
                type: 'boolean',
                default: false,
            })
            .option('inspector-port', {
                description:
                    "Enable WebKit's remote inspector protocol on this port + the Cdp* methods (implies --devtools)",
                type: 'number',
            })
            .option('build-only', {
                description: 'Build the bundle but do not launch it',
                type: 'boolean',
                default: false,
            }),
    handler: async (args) => {
        const cwd = process.cwd();
        const pkg = readPackage(cwd);
        const config = pkg.gjsify?.browse ?? {};

        const applicationId = args.appId ?? config.applicationId ?? deriveBrowserAppId(pkg.name);
        const title = args.title ?? config.title;
        const globals = args.globals ?? config.globals ?? 'auto,dom';
        const url = args.url;
        const inspectorPort = args.inspectorPort ?? config.inspectorPort;
        // CDP-over-MCP needs the control plane, so --inspector-port implies --devtools.
        const devtools = args.devtools || inspectorPort !== undefined;

        const cacheDir = join(cwd, 'node_modules', '.cache', 'gjsify-browse');
        mkdirSync(cacheDir, { recursive: true });
        const entryPath = join(cacheDir, 'entry.ts');
        const outPath = args.out ? resolve(cwd, args.out) : join(cacheDir, 'browse.gjs.mjs');

        writeFileSync(entryPath, generateEntry(applicationId, url, title, inspectorPort));
        console.log(
            `[gjsify browse] app=${applicationId}${url ? ` url=${url}` : ''}${devtools ? ' devtools=1' : ''}${
                inspectorPort !== undefined ? ` inspector-port=${inspectorPort}` : ''
            }`,
        );

        const { runCli } = await import('../cli-app.js');
        await runCli(['build', entryPath, '--app', 'gjs', '--globals', globals, '--outfile', outPath]);

        if (args.buildOnly) {
            console.log(`[gjsify browse] built ${outPath}`);
            return;
        }

        // runGjsBundle spreads process.env into the child, so set the devtools
        // gate here (RunGjsBundleOptions has no env field).
        if (devtools) process.env.GJSIFY_DEVTOOLS = '1';
        // Set the inspector env in the LAUNCHER so the spawned gjs has it from
        // process start. WebKit reads WEBKIT_INSPECTOR_HTTP_SERVER once, at
        // WebKitInitialize (triggered as the first WebView type initializes —
        // before the app's own constructor runs), so setting it only inside the
        // app is too late to bind the server. This is the authoritative place;
        // the BrowserApplication constructor keeps a best-effort fallback for
        // direct runBrowserDevtools() callers.
        if (inspectorPort !== undefined) {
            process.env.WEBKIT_INSPECTOR_HTTP_SERVER = `127.0.0.1:${inspectorPort}`;
        }
        const { runGjsBundle } = await import('../utils/run-gjs.js');
        await runGjsBundle(outPath, [], { exitOnSuccess: true });
    },
};
