// `gjsify debug` — launch an MCP↔devtools bridge for a running, devtools-enabled
// gjsify app (its `org.gjsify.Devtools` DBus control plane). An MCP client (e.g.
// Claude Code) uses this as its server command; the bridge speaks JSON-RPC on
// stdio and translates tool calls to the app's DBus interface.
//
// Dispatch is IN-PROCESS (runCli + runGjsBundle), like `gjsify storybook`. The
// generated entry resolves `@gjsify/devtools-mcp` from the CONSUMER's
// node_modules (so it stays out of the CLI's own deps). The bridge is built
// `--app gjs --shebang` and launched with stdio inherited, so its JSON-RPC
// stdout reaches the client untouched.
//
// CRITICAL: this command logs ONLY to stderr — stdout is the MCP channel.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { Command } from '../types/index.js';

interface DebugCliOptions {
    busName?: string;
    profile?: string;
    globals?: string;
    out?: string;
    buildOnly: boolean;
}

interface DevtoolsConfig {
    busNameBase?: string;
    /** `generic` | `storybook` | `browser` | `cdp` (default: auto-detected). */
    profile?: string;
    globals?: string;
}

interface ProjectPackage {
    name?: string;
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
    gjsify?: {
        devtools?: DevtoolsConfig;
        storybook?: { applicationId?: string };
        browse?: { applicationId?: string };
    };
}

function readPackage(cwd: string): ProjectPackage {
    try {
        return JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8')) as ProjectPackage;
    } catch {
        return {};
    }
}

/** Mirror of `commands/storybook.ts` deriveAppId — the storybook app's DBus id. */
function deriveStorybookAppId(name?: string): string {
    if (!name) return 'org.gjsify.Storybook';
    const slug = name
        .replace(/^@/, '')
        .replace(/[^a-zA-Z0-9]+/g, '.')
        .replace(/^\.+|\.+$/g, '');
    return `org.gjsify.storybook.${slug}`;
}

/** Mirror of `commands/browse.ts` deriveBrowserAppId — the browser app's DBus id. */
function deriveBrowserAppId(name?: string): string {
    if (!name) return 'org.gjsify.Browser';
    const slug = name
        .replace(/^@/, '')
        .replace(/[^a-zA-Z0-9]+/g, '.')
        .replace(/^\.+|\.+$/g, '');
    return `org.gjsify.browser.${slug}`;
}

function hasDep(pkg: ProjectPackage, name: string): boolean {
    return Boolean(pkg.dependencies?.[name] || pkg.devDependencies?.[name]);
}

function generateEntry(profile: string, busNameBase: string, name: string, version: string): string {
    if (profile === 'storybook') {
        return `// Auto-generated by \`gjsify debug\` — do not edit by hand.
import { runDevtoolsMcp, storybookProfile } from '@gjsify/devtools-mcp';

await runDevtoolsMcp(storybookProfile(${JSON.stringify(busNameBase)}));
`;
    }
    if (profile === 'browser') {
        return `// Auto-generated by \`gjsify debug\` — do not edit by hand.
import { runDevtoolsMcp, browserProfile } from '@gjsify/devtools-mcp';

await runDevtoolsMcp(browserProfile(${JSON.stringify(busNameBase)}));
`;
    }
    if (profile === 'cdp') {
        return `// Auto-generated by \`gjsify debug\` — do not edit by hand.
import { runDevtoolsMcp, cdpProfile } from '@gjsify/devtools-mcp';

await runDevtoolsMcp(cdpProfile(${JSON.stringify(busNameBase)}));
`;
    }
    return `// Auto-generated by \`gjsify debug\` — do not edit by hand.
import { runDevtoolsMcp } from '@gjsify/devtools-mcp';

await runDevtoolsMcp({
    name: ${JSON.stringify(name)},
    version: ${JSON.stringify(version)},
    busNameBase: ${JSON.stringify(busNameBase)},
});
`;
}

export const debugCommand: Command<unknown, DebugCliOptions> = {
    command: 'debug',
    description: 'Launch an MCP bridge for a devtools-enabled gjsify app (org.gjsify.Devtools).',
    builder: (yargs) =>
        yargs
            .option('bus-name', {
                description: 'App DBus base name (default: gjsify.devtools.busNameBase, or the storybook app-id)',
                type: 'string',
            })
            .option('profile', {
                description:
                    'Tool profile: generic | storybook | browser | cdp (default: auto — storybook if @gjsify/storybook is a dep, browser if @gjsify/devtools-browser is, cdp if @gjsify/devtools-cdp is, else generic)',
                type: 'string',
            })
            .option('globals', {
                description: 'Value for `gjsify build --globals` (default: auto)',
                type: 'string',
            })
            .option('out', {
                description: 'Output bundle path (default: node_modules/.cache/gjsify-debug)',
                type: 'string',
            })
            .option('build-only', {
                description:
                    'Build the bridge bundle but do not launch it (for a .mcp.json command pointing at the bundle)',
                type: 'boolean',
                default: false,
            }),
    handler: async (args) => {
        const cwd = process.cwd();
        const pkg = readPackage(cwd);
        const config = pkg.gjsify?.devtools ?? {};

        const profile =
            args.profile ??
            config.profile ??
            (hasDep(pkg, '@gjsify/storybook')
                ? 'storybook'
                : hasDep(pkg, '@gjsify/devtools-browser')
                  ? 'browser'
                  : hasDep(pkg, '@gjsify/devtools-cdp')
                    ? 'cdp'
                    : 'generic');

        const busNameBase =
            args.busName ??
            config.busNameBase ??
            (profile === 'storybook'
                ? (pkg.gjsify?.storybook?.applicationId ?? deriveStorybookAppId(pkg.name))
                : profile === 'browser' || profile === 'cdp'
                  ? (pkg.gjsify?.browse?.applicationId ?? deriveBrowserAppId(pkg.name))
                  : undefined);

        if (!busNameBase) {
            console.error(
                'gjsify debug: no bus name — set package.json#gjsify.devtools.busNameBase or pass --bus-name <org.example.App>',
            );
            // `return` — a bare `process.exit()` is deferred under GJS and the
            // handler would continue without a bus name.
            return process.exit(1);
        }

        const globals = args.globals ?? config.globals ?? 'auto';
        const name = pkg.name ? `${pkg.name}-devtools` : 'gjsify-devtools';
        const version = '0.8.0';

        const cacheDir = join(cwd, 'node_modules', '.cache', 'gjsify-debug');
        mkdirSync(cacheDir, { recursive: true });
        const entryPath = join(cacheDir, 'entry.ts');
        const outPath = args.out ? resolve(cwd, args.out) : join(cacheDir, 'bridge.gjs.mjs');

        writeFileSync(entryPath, generateEntry(profile, busNameBase, name, version));
        // stderr only — stdout is the MCP JSON-RPC channel.
        console.error(`[gjsify debug] profile=${profile} bus=${busNameBase}`);

        // In-process build (runtime-agnostic), then launch with stdio inherited
        // so the bridge's JSON-RPC stdin/stdout are the client's pipes.
        const { runCli } = await import('../cli-app.js');
        await runCli(['build', entryPath, '--app', 'gjs', '--shebang', '--globals', globals, '--outfile', outPath]);

        if (args.buildOnly) {
            console.error(`[gjsify debug] built ${outPath}`);
            return;
        }

        const { runGjsBundle } = await import('../utils/run-gjs.js');
        await runGjsBundle(outPath, [], { exitOnSuccess: true });
    },
};
