// `gjsify devtools` — drive a running, devtools-enabled gjsify app from a SCRIPT.
//
// The peer of `gjsify debug`, not a replacement for it. `debug` speaks MCP over stdio, which
// is the right shape for an AI agent and the wrong one for a shell script, a Makefile, or a CI
// step: there is no way to pipe `Screenshot` into a file, because MCP's answer is base64 inside
// a JSON-RPC frame. So every consumer that wanted a screenshot on disk wrote its own GJS
// caller to unpack the `ay` variant — and every one of them had to re-decide the same two
// things this command decides once:
//
//   · EMPTY BYTES ARE A FAILURE. `Screenshot` answers `ay[0]` when there is no active window
//     or the window was never realised (the deliberate `CaptureBlocker` contract). Writing
//     that produces a 0-byte file named `.png` and a success message.
//   · THE SIZE COMES FROM THE PNG. `ResizeWindow` answers with the size it was ASKED for, so a
//     window that ignored the resize still reports success — measured in a consumer: 1280
//     requested, 1100 in the file, four checks green.
//
// Both live in `@gjsify/devtools` (`captureShot`), so a consumer driving the control plane from
// its own code gets them by importing one function rather than by copying a script.
//
// Dispatch is IN-PROCESS like `debug`/`storybook`: the generated entry imports
// `@gjsify/devtools` + `@gjsify/devtools-mcp` from the CONSUMER's node_modules (so the CLI keeps
// no dependency on either), is built `--app gjs`, and the RESULT is printed on stdout.
//
// WHY A GENERATED BUNDLE AND NOT `gdbus`: the peer transport (macOS/Windows, which have no
// session bus) is `Gio.DBusServer` + an address file, and `gdbus` cannot speak it. A command
// that reached the app only over the session bus would be the Linux-only half of a capability
// the package deliberately made OS-agnostic.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { Command } from '../types/index.js';

interface DevtoolsCliOptions {
    /** Positional 1: the control-plane operation, e.g. `shot`. */
    operation: string;
    /** Positional 2+: its arguments — the output path for `shot`, the selector for `find`. */
    operands?: string[];
    busName?: string;
    address?: string;
    instance?: string;
    globals?: string;
    out?: string;
    timeout: number;
}

interface DevtoolsConfig {
    busNameBase?: string;
    address?: string;
    instance?: string;
}

interface ProjectPackage {
    name?: string;
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
    gjsify?: { devtools?: DevtoolsConfig; storybook?: { applicationId?: string }; browse?: { applicationId?: string } };
}

function readPackage(cwd: string): ProjectPackage {
    try {
        return JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8')) as ProjectPackage;
    } catch {
        return {};
    }
}

/**
 * The generated entry. It takes its options as ARGV rather than baking them in, so one cached
 * bundle serves every invocation — the command-line flags of a rig change far more often than
 * the code does, and a rebuild per flag would make `--timeout` cost a full bundle build.
 *
 * `system.exit(await …)` is load-bearing rather than decorative: 0 done / 1 the app said no /
 * 2 the request itself was wrong is the whole contract a shell rig reads out of `$?`, and an
 * awaited value cannot become a process exit status under GJS. `system.programArgs` are the
 * user arguments — under `gjs -m bundle.js …` the `-m` and the path are `programInvocationName`,
 * not args, so nothing has to be sliced off.
 */
function generateEntry(): string {
    return `// Auto-generated by \`gjsify devtools\` — do not edit by hand.
import system from 'system';

import { runDevtoolsCli } from '@gjsify/devtools-mcp';

system.exit(await runDevtoolsCli(system.programArgs));
`;
}

/**
 * `gjsify devtools` builds and runs a tiny client over the `org.gjsify.Devtools` control
 * plane. Subcommands mirror the control-plane methods — `shot`, `find`, `activate`, `key`,
 * `tree`, `property`, `resize`, `status`, `actions`, `toplevels`, `css`, `gsettings`,
 * `instances` — so anything a rig does by hand over `gdbus` has a scriptable spelling.
 */
export const devtoolsCommand: Command<unknown, DevtoolsCliOptions> = {
    command: 'devtools',
    description:
        'Drive a running devtools-enabled app from a script: capture a screenshot to a file, find a widget, ' +
        'activate it, send a key. Peer of `gjsify debug`, which speaks MCP for an AI agent.',
    builder: (yargs) =>
        yargs
            .positional('operation', {
                description: 'Control-plane operation: shot | find | activate | key | tree | property | …',
                type: 'string',
                demandOption: true,
            })
            .positional('operands', {
                description: 'Subcommand arguments — e.g. the output path for `shot`, the selector for `find`.',
                type: 'string',
                array: true,
            })
            .option('bus-name', {
                description:
                    "App DBus base name — the app's Gtk application id (default: gjsify.devtools.busNameBase, " +
                    'then the storybook app-id). Unlike `gjsify debug` there is no derived fallback: the bus name ' +
                    'IS the application id, and guessing it produces a name nothing answers to',
                type: 'string',
            })
            .option('address', {
                description:
                    'Peer D-Bus address of the app (unix:path=… / nonce-tcp:…) instead of the session bus — for ' +
                    'macOS/Windows, which have no session bus. Default: GJSIFY_DEVTOOLS_ADDRESS, then the address ' +
                    'file the app publishes, then the session bus',
                type: 'string',
            })
            .option('instance', {
                description: 'App instance label for a multi-instance app (default: GJSIFY_DEVTOOLS_INSTANCE)',
                type: 'string',
            })
            .option('globals', {
                description: 'Value for `gjsify build --globals` (default: auto)',
                type: 'string',
            })
            .option('out', {
                description: 'Output bundle path (default: node_modules/.cache/gjsify-devtools)',
                type: 'string',
            })
            .option('timeout', {
                description:
                    'Seconds to keep polling GetStatus for the control plane to answer (default: 30). 0 = do not wait',
                type: 'number',
                default: 30,
            }),
    handler: async (args) => {
        const cwd = process.cwd();
        const pkg = readPackage(cwd);
        const config = pkg.gjsify?.devtools ?? {};

        const busNameBase =
            args.busName ??
            config.busNameBase ??
            pkg.gjsify?.storybook?.applicationId ??
            pkg.gjsify?.browse?.applicationId;

        // Asked for BEFORE a bundle is built: without a bus name the build succeeds and the
        // client then exits 2 having done nothing, which reads like a broken app.
        if (!busNameBase) {
            console.error(
                "gjsify devtools: no bus name — the bus name IS the app's Gtk application id, so it cannot be " +
                    'derived from the package name. Pass --bus-name <org.example.App> (the app prints it when it ' +
                    'exports the control plane) or set package.json#gjsify.devtools.busNameBase.',
            );
            return process.exit(1);
        }

        const cacheDir = join(cwd, 'node_modules', '.cache', 'gjsify-devtools');
        mkdirSync(cacheDir, { recursive: true });
        const entryPath = join(cacheDir, 'entry.ts');
        const outPath = args.out ? resolve(cwd, args.out) : join(cacheDir, 'cli.gjs.mjs');

        const globals = args.globals ?? 'auto';
        writeFileSync(entryPath, generateEntry());

        // stderr for progress — stdout is the RESULT the caller captures.
        console.error(
            `[gjsify devtools] bus=${busNameBase}${args.address ? ` address=${args.address}` : ''}${args.instance ? ` instance=${args.instance}` : ''}`,
        );

        const { runCli } = await import('../cli-app.js');
        await runCli(['build', entryPath, '--app', 'gjs', '--globals', globals, '--outfile', outPath]);

        // The RESOLVED values are forwarded, never the raw argv: the child parses its own flags
        // and knows nothing about package.json, so forwarding only what was typed would drop the
        // configured bus name on the floor.
        const forwarded: string[] = [args.operation, ...(args.operands ?? []), '--bus-name', busNameBase];
        if (args.address) forwarded.push('--address', args.address);
        if (args.instance) forwarded.push('--instance', args.instance);
        forwarded.push('--timeout', String(args.timeout));

        const { runGjsBundle } = await import('../utils/run-gjs.js');
        await runGjsBundle(outPath, forwarded, { completion: 'exit', exitOnSuccess: true });
    },
};
