// `gjsify storybook` — discover every *.story.ts in a project, generate a tiny
// entry that registers them, then build and launch the generic
// @gjsify/storybook component browser. No per-project storybook app needed.
//
// `--runtime gjs` (default) builds `--app gjs` and runs it with `gjs -m`.
// `--runtime node` builds `--app node` (gi:// → @gjsify/node-gi reverse bridge)
// and runs it with `node` — the SAME storybook source rendering on Node.js. The
// node path wires GI_TYPELIB_PATH/LD_LIBRARY_PATH like `gjsify run` (so any
// native @gjsify bridge a story uses resolves) and requires `@gjsify/node-gi`
// installed in the project (kept external by the bundler, a native addon).
//
// Dispatch is IN-PROCESS (runCli + runGjsBundle), not a re-spawn of the CLI:
// the showcase-style `spawn(process.execPath, [cliBin, …])` pattern assumes
// Node, but under the committed GJS bundle `process.execPath` is `gjs` and the
// `../index.js` path is not a runnable entry. In-process dispatch works
// identically under Node and GJS. @gjsify/storybook is resolved from the
// CONSUMER's node_modules by the generated entry, so it stays out of the CLI's
// own dependencies.

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import type { Command } from '../types/index.js';
import { hostRuntime } from '@gjsify/rolldown-plugin-gjsify/runtime';

/**
 * Runtime the storybook bundle is built for and launched on. `gjs` builds an
 * `--app gjs` bundle; `node`/`bun`/`deno` build the SAME `--app node` bundle
 * (gi:// → `@gjsify/node-gi` reverse bridge; Node-API is their common ABI).
 */
type StorybookRuntime = 'gjs' | 'node' | 'bun' | 'deno';

interface StorybookCliOptions {
    stories?: string;
    appId?: string;
    title?: string;
    globals?: string;
    out?: string;
    runtime?: string;
    watch: boolean;
    buildOnly: boolean;
}

interface StorybookConfig {
    applicationId?: string;
    title?: string;
    /** Directory scanned recursively for `*.story.ts` (default `src`). */
    stories?: string;
    /** `--globals` value passed to `gjsify build` (default `auto`). */
    globals?: string;
    /** Runtime the storybook is built for and launched on (`gjs` | `node`, default `gjs`). */
    runtime?: StorybookRuntime;
}

interface ProjectPackage {
    name?: string;
    gjsify?: { storybook?: StorybookConfig };
}

function readPackage(cwd: string): ProjectPackage {
    try {
        return JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8')) as ProjectPackage;
    } catch {
        return {};
    }
}

/** Derive a stable GApplication id from the package name when none is configured. */
function deriveAppId(name?: string): string {
    if (!name) return 'org.gjsify.Storybook';
    const slug = name
        .replace(/^@/, '')
        .replace(/[^a-zA-Z0-9]+/g, '.')
        .replace(/^\.+|\.+$/g, '');
    return `org.gjsify.storybook.${slug}`;
}

/** Recursively collect `*.story.{ts,js,mts,mjs}` files under a directory. */
function findStoryFiles(dir: string): string[] {
    const out: string[] = [];
    if (!existsSync(dir)) return out;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
        const full = join(dir, entry.name);
        if (entry.isDirectory()) {
            out.push(...findStoryFiles(full));
        } else if (/\.story\.(ts|js|mts|mjs)$/.test(entry.name)) {
            out.push(full);
        }
    }
    return out;
}

function generateEntry(files: string[], applicationId: string, title?: string): string {
    const imports = files.map((file, i) => `import * as m${i} from ${JSON.stringify(file)};`).join('\n');
    const namespaces = files.map((_, i) => `m${i}`).join(', ');
    const titleLine = title ? `\n    title: ${JSON.stringify(title)},` : '';
    return `// Auto-generated by \`gjsify storybook\` — do not edit by hand.
import { collectStoryModules, runStorybook } from '@gjsify/storybook';
${imports}

await runStorybook({
    applicationId: ${JSON.stringify(applicationId)},${titleLine}
    stories: collectStoryModules([${namespaces}]),
});
`;
}

export const storybookCommand: Command<unknown, StorybookCliOptions> = {
    command: 'storybook',
    description: 'Discover *.story.ts in this project and launch the GTK storybook browser.',
    builder: (yargs) =>
        yargs
            .option('stories', {
                description: 'Directory scanned recursively for *.story.ts (default: src, or gjsify.storybook.stories)',
                type: 'string',
            })
            .option('app-id', {
                description:
                    'GApplication id (default: gjsify.storybook.applicationId or derived from the package name)',
                type: 'string',
            })
            .option('title', { description: 'Window title', type: 'string' })
            .option('globals', {
                description: 'Value for `gjsify build --globals` (default: auto; use auto,dom for canvas/DOM stories)',
                type: 'string',
            })
            .option('out', {
                description: 'Output bundle path (default: node_modules/.cache/gjsify-storybook)',
                type: 'string',
            })
            .option('runtime', {
                description:
                    'Runtime to build for and launch on: gjs | node | bun | deno (default: the host runtime). ' +
                    'node/bun/deno build the same `--app node` bundle (gi:// → @gjsify/node-gi) and require ' +
                    '@gjsify/node-gi installed in the project.',
                type: 'string',
                choices: ['gjs', 'node', 'bun', 'deno'],
                // No yargs `default: 'gjs'` — a yargs default clobbers the
                // config-file value (`gjsify.storybook.runtime`). The host
                // default is applied in the handler: flag > config > host.
                defaultDescription: 'host runtime (gjs on gjs, else node/bun/deno)',
            })
            .option('watch', {
                description: 'Rebuild and relaunch when a story file changes',
                type: 'boolean',
                default: false,
            })
            .option('build-only', {
                description: 'Build the bundle but do not launch it',
                type: 'boolean',
                default: false,
            }),
    handler: async (args) => {
        const cwd = process.cwd();
        const pkg = readPackage(cwd);
        const config = pkg.gjsify?.storybook ?? {};

        const storiesDir = resolve(cwd, args.stories ?? config.stories ?? 'src');
        const applicationId = args.appId ?? config.applicationId ?? deriveAppId(pkg.name);
        const title = args.title ?? config.title;
        const globals = args.globals ?? config.globals ?? 'auto';
        // Default FOLLOWS the host runtime the CLI executes in. Precedence: CLI
        // flag > `gjsify.storybook.runtime` config > host default (`hostRuntime()`).
        const runtime: StorybookRuntime = (args.runtime ?? config.runtime ?? hostRuntime()) as StorybookRuntime;
        // The runtime drives BOTH the build target (`gjsify build --app <app>`)
        // and the launcher: `gjs` builds an `--app gjs` bundle run by `gjs -m`;
        // `node`/`bun`/`deno` build the SAME `--app node` bundle (gi:// →
        // @gjsify/node-gi) run on that runtime. Same generated entry +
        // `--globals auto` for all.
        const app = runtime === 'gjs' ? 'gjs' : 'node';

        const cacheDir = join(cwd, 'node_modules', '.cache', 'gjsify-storybook');
        mkdirSync(cacheDir, { recursive: true });
        const entryPath = join(cacheDir, 'entry.ts');
        const outPath = args.out ? resolve(cwd, args.out) : join(cacheDir, `storybook.${app}.mjs`);

        const writeEntry = (): number => {
            const files = findStoryFiles(storiesDir).sort();
            writeFileSync(entryPath, generateEntry(files, applicationId, title));
            return files.length;
        };

        const initialCount = writeEntry();
        if (initialCount === 0) {
            // `return process.exit()`: a bare `process.exit()` does NOT halt
            // synchronously under GJS (no atexit, the GLib loop is still
            // armed), so execution fell through to the "Found 0 story file(s)"
            // log and on into the build — and the deferred exit never carried
            // its code, so `gjsify storybook` in a directory with no stories
            // printed BOTH messages and exited 0. Measured: exit 1 under bun,
            // exit 0 under gjs, same command. Same trap as `showcase.ts`.
            console.error(
                `No *.story.ts files found under ${relative(cwd, storiesDir) || storiesDir}\n\n` +
                    `  \`gjsify storybook\` renders the stories of the CURRENT project: it discovers\n` +
                    `  \`*.story.ts\` files and launches a component browser over them. Point it at a\n` +
                    `  different directory with --stories <dir> (or \`gjsify.storybook.stories\` in\n` +
                    `  package.json) if yours live elsewhere.\n\n` +
                    `  To SEE a storybook without authoring one first, run the curated Libadwaita\n` +
                    `  component browser — it is a showcase, so it needs no project at all:\n\n` +
                    `      gjsify showcase adwaita-storybook`,
            );
            return process.exit(1);
        }
        console.log(
            `Found ${initialCount} story file(s) under ${relative(cwd, storiesDir) || '.'} (runtime: ${runtime})`,
        );

        // In-process build — runtime-agnostic (Node uses npm rolldown, GJS uses
        // the @gjsify/rolldown-native facade), no re-spawn of the CLI binary.
        const { runCli } = await import('../cli-app.js');
        const buildBundle = (): Promise<void> =>
            runCli(['build', entryPath, '--app', app, '--globals', globals, '--outfile', outPath]);

        const launch = async (): Promise<void> => {
            if (runtime === 'gjs') {
                const { runGjsBundle } = await import('../utils/run-gjs.js');
                await runGjsBundle(outPath, [], { completion: 'exit', exitOnSuccess: true });
            } else if (runtime === 'node') {
                const { runNodeBundle } = await import('../utils/run-node.js');
                await runNodeBundle(outPath, [], { completion: 'exit', exitOnSuccess: true });
            } else {
                // bun / deno — run the SAME `--app node` bundle via the shared
                // runner (Node-API is their common ABI). node-gi is required
                // because the storybook uses gi:// (checked in runRuntimeBundle).
                const { runRuntimeBundle } = await import('../utils/run-node.js');
                await runRuntimeBundle(runtime, outPath, [], { completion: 'exit', exitOnSuccess: true });
            }
        };

        if (!args.watch) {
            await buildBundle();
            if (args.buildOnly) return;
            await launch();
            return;
        }

        // Watch mode: rebuild + relaunch on any change under the stories dir,
        // through the loop shared with `gjsify dev` (`utils/watch-loop.ts`).
        const { runWatchLoop, spawnBundleSupervised } = await import('../utils/watch-loop.js');
        await runWatchLoop({
            dir: storiesDir,
            dirLabel: relative(cwd, storiesDir) || '.',
            label: 'storybook',
            // Stories are DISCOVERED, so the generated entry is re-derived on
            // every pass — a new `*.story.ts` must show up without a restart.
            prepare: () => {
                writeEntry();
            },
            build: buildBundle,
            spawnChild: args.buildOnly ? null : () => spawnBundleSupervised(runtime, outPath, cwd, 'the storybook'),
            output: outPath,
        });
    },
};
