// `gjsify storybook` — discover every *.story.ts in a project, generate a tiny
// entry that registers them, then build (`--app gjs`) and launch the generic
// @gjsify/storybook component browser. No per-project storybook app needed.
//
// Dispatch is IN-PROCESS (runCli + runGjsBundle), not a re-spawn of the CLI:
// the showcase-style `spawn(process.execPath, [cliBin, …])` pattern assumes
// Node, but under the committed GJS bundle `process.execPath` is `gjs` and the
// `../index.js` path is not a runnable entry. In-process dispatch works
// identically under Node and GJS. @gjsify/storybook is resolved from the
// CONSUMER's node_modules by the generated entry, so it stays out of the CLI's
// own dependencies.

import { spawn, type ChildProcess } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import type { Command } from '../types/index.js';

interface StorybookCliOptions {
    stories?: string;
    appId?: string;
    title?: string;
    globals?: string;
    out?: string;
    watch: boolean;
    buildOnly: boolean;
}

interface StorybookConfig {
    applicationId?: string;
    title?: string;
    /** Directory scanned recursively for `*.story.ts` (default `src`). */
    stories?: string;
    /** `--globals` value passed to `gjsify build` (default `auto`). */
    globals?: string;
}

interface ProjectPackage {
    name?: string;
    gjsify?: { storybook?: StorybookConfig };
}

function readPackage(cwd: string): ProjectPackage {
    try {
        return JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8')) as ProjectPackage;
    } catch {
        return {};
    }
}

/** Derive a stable GApplication id from the package name when none is configured. */
function deriveAppId(name?: string): string {
    if (!name) return 'org.gjsify.Storybook';
    const slug = name
        .replace(/^@/, '')
        .replace(/[^a-zA-Z0-9]+/g, '.')
        .replace(/^\.+|\.+$/g, '');
    return `org.gjsify.storybook.${slug}`;
}

/** Recursively collect `*.story.{ts,js,mts,mjs}` files under a directory. */
function findStoryFiles(dir: string): string[] {
    const out: string[] = [];
    if (!existsSync(dir)) return out;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
        const full = join(dir, entry.name);
        if (entry.isDirectory()) {
            out.push(...findStoryFiles(full));
        } else if (/\.story\.(ts|js|mts|mjs)$/.test(entry.name)) {
            out.push(full);
        }
    }
    return out;
}

function generateEntry(files: string[], applicationId: string, title?: string): string {
    const imports = files.map((file, i) => `import * as m${i} from ${JSON.stringify(file)};`).join('\n');
    const namespaces = files.map((_, i) => `m${i}`).join(', ');
    const titleLine = title ? `\n    title: ${JSON.stringify(title)},` : '';
    return `// Auto-generated by \`gjsify storybook\` — do not edit by hand.
import { collectStoryModules, runStorybook } from '@gjsify/storybook';
${imports}

await runStorybook({
    applicationId: ${JSON.stringify(applicationId)},${titleLine}
    stories: collectStoryModules([${namespaces}]),
});
`;
}

export const storybookCommand: Command<unknown, StorybookCliOptions> = {
    command: 'storybook',
    description: 'Discover *.story.ts in this project and launch the GTK storybook browser.',
    builder: (yargs) =>
        yargs
            .option('stories', {
                description: 'Directory scanned recursively for *.story.ts (default: src, or gjsify.storybook.stories)',
                type: 'string',
            })
            .option('app-id', {
                description: 'GApplication id (default: gjsify.storybook.applicationId or derived from the package name)',
                type: 'string',
            })
            .option('title', { description: 'Window title', type: 'string' })
            .option('globals', {
                description: 'Value for `gjsify build --globals` (default: auto; use auto,dom for canvas/DOM stories)',
                type: 'string',
            })
            .option('out', {
                description: 'Output bundle path (default: node_modules/.cache/gjsify-storybook)',
                type: 'string',
            })
            .option('watch', {
                description: 'Rebuild and relaunch when a story file changes',
                type: 'boolean',
                default: false,
            })
            .option('build-only', { description: 'Build the bundle but do not launch it', type: 'boolean', default: false }),
    handler: async (args) => {
        const cwd = process.cwd();
        const pkg = readPackage(cwd);
        const config = pkg.gjsify?.storybook ?? {};

        const storiesDir = resolve(cwd, args.stories ?? config.stories ?? 'src');
        const applicationId = args.appId ?? config.applicationId ?? deriveAppId(pkg.name);
        const title = args.title ?? config.title;
        const globals = args.globals ?? config.globals ?? 'auto';

        const cacheDir = join(cwd, 'node_modules', '.cache', 'gjsify-storybook');
        mkdirSync(cacheDir, { recursive: true });
        const entryPath = join(cacheDir, 'entry.ts');
        const outPath = args.out ? resolve(cwd, args.out) : join(cacheDir, 'storybook.gjs.mjs');

        const writeEntry = (): number => {
            const files = findStoryFiles(storiesDir).sort();
            writeFileSync(entryPath, generateEntry(files, applicationId, title));
            return files.length;
        };

        const initialCount = writeEntry();
        if (initialCount === 0) {
            console.error(`No *.story.ts files found under ${relative(cwd, storiesDir) || storiesDir}`);
            process.exit(1);
        }
        console.log(`Found ${initialCount} story file(s) under ${relative(cwd, storiesDir) || '.'}`);

        // In-process build — runtime-agnostic (Node uses npm rolldown, GJS uses
        // the @gjsify/rolldown-native facade), no re-spawn of the CLI binary.
        const { runCli } = await import('../cli-app.js');
        const buildBundle = (): Promise<void> =>
            runCli(['build', entryPath, '--app', 'gjs', '--globals', globals, '--outfile', outPath]);

        if (!args.watch) {
            await buildBundle();
            if (args.buildOnly) return;
            const { runGjsBundle } = await import('../utils/run-gjs.js');
            await runGjsBundle(outPath, [], { exitOnSuccess: true });
            return;
        }

        // Watch mode: rebuild + relaunch on any change under the stories dir.
        // The storybook bundle only needs system Gtk/Adw typelibs at runtime
        // (no @gjsify native bridges), so a plain `gjs -m` child is enough and
        // stays killable for relaunch.
        const { watch } = await import('node:fs');
        let child: ChildProcess | null = null;
        let rebuilding = false;
        let pending = false;

        const rebuild = async (): Promise<void> => {
            if (rebuilding) {
                pending = true;
                return;
            }
            rebuilding = true;
            try {
                writeEntry();
                if (child) {
                    child.kill();
                    child = null;
                }
                await buildBundle();
                if (!args.buildOnly) {
                    child = spawn('gjs', ['-m', outPath], { stdio: 'inherit' });
                }
            } catch (err) {
                console.error(`[storybook] rebuild failed: ${(err as Error).message}`);
            } finally {
                rebuilding = false;
                if (pending) {
                    pending = false;
                    void rebuild();
                }
            }
        };

        await rebuild();

        let debounce: ReturnType<typeof setTimeout> | null = null;
        watch(storiesDir, { recursive: true }, () => {
            if (debounce) clearTimeout(debounce);
            debounce = setTimeout(() => void rebuild(), 200);
        });
        console.log(`[storybook] watching ${relative(cwd, storiesDir) || '.'} — press Ctrl+C to stop`);
    },
};
