// Reference: Node.js lib/dns.js
// Barrel: the callback API from `callback.ts` plus `dns.promises`.

import {
    lookup,
    resolve,
    resolve4,
    resolve6,
    reverse,
    setDefaultResultOrder,
    getDefaultResultOrder,
    NODATA,
    FORMERR,
    SERVFAIL,
    NOTFOUND,
    NOTIMP,
    REFUSED,
    BADQUERY,
    BADNAME,
    BADFAMILY,
    BADRESP,
    CONNREFUSED,
    TIMEOUT,
    EOF,
    FILE,
    NOMEM,
    DESTRUCTION,
    BADSTR,
    BADFLAGS,
    NONAME,
    BADHINTS,
    NOTINITIALIZED,
    CANCELLED,
} from './callback.js';
import * as promises from './promises.js';

export * from './callback.js';
export { promises };

export default {
    lookup,
    resolve,
    resolve4,
    resolve6,
    reverse,
    setDefaultResultOrder,
    getDefaultResultOrder,
    NODATA,
    FORMERR,
    SERVFAIL,
    NOTFOUND,
    NOTIMP,
    REFUSED,
    BADQUERY,
    BADNAME,
    BADFAMILY,
    BADRESP,
    CONNREFUSED,
    TIMEOUT,
    EOF,
    FILE,
    NOMEM,
    DESTRUCTION,
    BADSTR,
    BADFLAGS,
    NONAME,
    BADHINTS,
    NOTINITIALIZED,
    CANCELLED,
    promises,
};
