// The emoji a `<gtk-emoji-chooser>` shows, and the words it searches.
//
// WHY THIS TABLE IS SMALL, AND WHAT IT IS NOT
//
// `GtkEmojiChooser` loads its emoji from `/org/gtk/libgtk/emoji/<lang>.data`, a
// COMPILED GVariant resource of about 1.2 MB per language, read at runtime through
// `g_resources_lookup_data` (gtkemojichooser.c:648-680). It carries, per emoji, the code
// points (a 0 stands for the variation selector or the skin-tone modifier), the English
// name, the localised name and two keyword lists — and the search matches the NAMES AND
// KEYWORDS, never the glyph (gtkemojichooser.c:896-958). Nothing in a browser can read
// that blob: it is a GVariant serialisation, and shipping it would mean shipping GTK's
// compiled resource.
//
// So the replica carries a curated table with the same SHAPE — code points, name,
// keywords — in GTK's own ten sections with GTK's own headings, and says so where it is
// visible: the `emoji-picked` signal carries the same Unicode sequence, the search
// matches the same token lists with the same prefix rule, and the sections are the
// struct order of `GtkEmojiChooser`. Every derivation that READS this file lives in the
// element; nothing here decides anything.
//
// SECTION ORDER is the struct order (gtkemojichooser.c:216-228) and the order
// `setup_section` registers them in (gtkemojichooser.c:1075-1085): recent first, then
// the nine categories by ascending group (people 0, body 1, nature 3, food 4, travel 5,
// activities 6, objects 7, symbols 8, flags 9 — group 2 is absent upstream). The
// HEADINGS are the `.ui` labels with their `emoji category` context, mnemonics absent
// because the `.ui` headings have none: "Smileys & People", "Body & Clothing",
// "Animals & Nature", "Food & Drink", "Travel & Places", "Activities", "Objects",
// "Symbols", "Flags".

/** One emoji entry: the code points and the words the search reads. */
export interface EmojiEntry {
    /** The code points, as one string — a ZWJ sequence is already spelled out. */
    readonly text: string;
    /** The English name — `filter_func`'s second list. */
    readonly name: string;
    /** Search keywords, one word each — `filter_func`'s third list. */
    readonly keywords: readonly string[];
}

/** One `EmojiSection`, with the heading and the toolbar button's own label. */
export interface EmojiCategory {
    /** The section key: `recent`, `people`, … */
    readonly id: string;
    /** The heading above the section, `''` for the one without (recent). */
    readonly heading: string;
    /** The `.ui` tooltip of the toolbar button, which for every section but recent is its heading. */
    readonly tooltip: string;
    /** The emoji, in the order GTK appends them. */
    readonly entries: readonly EmojiEntry[];
}

/** One table row. Keywords are space-separated because `match_tokens` prefixes per WORD. */
function row(text: string, name: string, keywords = ''): EmojiEntry {
    return { text, name, keywords: keywords === '' ? [] : keywords.split(' ') };
}

/** `MAX_RECENT` — 7 columns by 3 rows (gtkemojichooser.c:363). */
export const EMOJI_MAX_RECENT = 7 * 3;

/** `EMOJI_SKIN_TONES` — `1F3FB`…`1F3FF`, the five modifiers (gtkemojichooser.c:530). */
export const EMOJI_SKIN_TONES: readonly string[] = ['\u{1F3FB}', '\u{1F3FC}', '\u{1F3FD}', '\u{1F3FE}', '\u{1F3FF}'];

/** `has_variations` (gtkemojichooser.c:489-508) — whether an entry carries a skin slot. */
export function hasVariations(entry: EmojiEntry): boolean {
    return [...entry.text].some((character) => EMOJI_SKIN_TONES.includes(character));
}

const PEOPLE: readonly EmojiEntry[] = [
    row('\u{1F600}', 'grinning face', 'smile happy joy grin'),
    row('\u{1F603}', 'grinning face with big eyes', 'smile happy joy'),
    row('\u{1F604}', 'grinning face with smiling eyes', 'smile happy joy'),
    row('\u{1F601}', 'beaming face with smiling eyes', 'smile happy'),
    row('\u{1F602}', 'face with tears of joy', 'laugh joy cry'),
    row('\u{1F923}', 'rolling on the floor laughing', 'laugh rofl joy'),
    row('\u{1F642}', 'slightly smiling face', 'smile'),
    row('\u{1F609}', 'winking face', 'wink joke flirt'),
    row('\u{1F60A}', 'smiling face with smiling eyes', 'blush happy'),
    row('\u{1F607}', 'smiling face with halo', 'angel innocent'),
    row('\u{1F970}', 'smiling face with hearts', 'love affection'),
    row('\u{1F60D}', 'smiling face with heart-eyes', 'love crush'),
    row('\u{1F618}', 'face blowing a kiss', 'kiss love'),
    row('\u{1F617}', 'kissing face', 'kiss love'),
    row('\u{263A}\uFE0F', 'smiling face', 'smile happy'),
    row('\u{1F60B}', 'face savoring food', 'yum delicious tasty'),
    row('\u{1F61B}', 'face with tongue', 'tongue silly'),
    row('\u{1F92A}', 'zany face', 'crazy goofy wild'),
    row('\u{1F61F}', 'worried face', 'worried sad'),
    row('\u{1F641}', 'slightly frowning face', 'sad frown'),
    row('\u{2639}\uFE0F', 'frowning face', 'sad frown'),
    row('\u{1F62E}', 'face with open mouth', 'surprised wow'),
    row('\u{1F632}', 'astonished face', 'surprised wow'),
    row('\u{1F633}', 'flushed face', 'blush embarrassed'),
    row('\u{1F97A}', 'pleading face', 'please puppy'),
    row('\u{1F626}', 'frowning face with open mouth', 'frown disappointed'),
    row('\u{1F628}', 'fearful face', 'fear scared'),
    row('\u{1F630}', 'anxious face with sweat', 'nervous anxious'),
    row('\u{1F622}', 'crying face', 'cry sad tear'),
    row('\u{1F62D}', 'loudly crying face', 'cry sad sob'),
    row('\u{1F636}', 'face without mouth', 'silent speechless'),
    row('\u{1F60F}', 'smirking face', 'smirk'),
    row('\u{1F612}', 'unamused face', 'meh unhappy'),
    row('\u{1F644}', 'face with rolling eyes', 'eyeroll annoyed'),
    row('\u{1F62C}', 'grimacing face', 'grimace awkward'),
    row('\u{1F925}', 'lying face', 'liar pinocchio'),
    row('\u{1F60E}', 'smiling face with sunglasses', 'cool sunglasses'),
    row('\u{1F913}', 'nerd face', 'nerd geek glasses'),
    row('\u{1F9D0}', 'face with monocle', 'fancy monocle'),
    row('\u{1F9D1}', 'person', 'adult human'),
    row('\u{1F468}', 'man', 'adult male'),
    row('\u{1F469}', 'woman', 'adult female'),
    row('\u{1F467}', 'girl', 'child female'),
    row('\u{1F466}', 'boy', 'child male'),
    row('\u{1F476}', 'baby', 'child infant'),
    // The one entry whose codes carry a `1F3FB` slot, which is what
    // `has_variations` looks for and what a long press opens a popover over.
    row('\u{1F476}\u{1F3FB}', 'child: light skin tone', 'child skin tone'),
    row('\u{1F9D1}\u200D\u{1F4BB}', 'technologist', 'coder computer'),
    row('\u{1F477}', 'construction worker', 'builder work'),
    row('\u{1F575}\uFE0F', 'detective', 'spy sleuth'),
    row('\u{1F934}', 'prince', 'crown royal'),
    row('\u{1F478}', 'princess', 'crown royal'),
    row('\u{1F470}', 'person with veil', 'bride wedding'),
    row('\u{1F935}', 'person in tuxedo', 'formal groom'),
    row('\u{1F385}', 'Santa Claus', 'christmas santa'),
    row('\u{1F936}', 'Mrs. Claus', 'christmas santa'),
    row('\u{1F9B8}', 'superhero', 'hero power'),
    row('\u{1F9B9}', 'supervillain', 'villain power'),
    row('\u{1F9D9}', 'mage', 'wizard magic'),
    row('\u{1F9DA}', 'fairy', 'magic wings'),
    row('\u{1F9DB}', 'vampire', 'dracula horror'),
    row('\u{1F9DC}', 'merperson', 'mermaid merman'),
    row('\u{1F9DD}', 'elf', 'fantasy pointy'),
    row('\u{1F9DF}', 'zombie', 'undead horror'),
    row('\u{1F486}', 'person getting massage', 'spa head'),
    row('\u{1F487}', 'person getting haircut', 'barber salon'),
    row('\u{1F6B6}', 'person walking', 'walk pedestrian'),
    row('\u{1F3C3}', 'person running', 'run marathon'),
    row('\u{1F483}', 'woman dancing', 'dance ballet'),
    row('\u{1F46A}', 'family', 'parents child'),
    row('\u{1F9D1}\u200D\u{1F91D}\u200D\u{1F9D1}', 'people holding hands', 'family couple'),
];

const BODY: readonly EmojiEntry[] = [
    row('\u{1F44B}', 'waving hand', 'wave hello goodbye'),
    row('\u{270B}\uFE0F', 'raised hand', 'stop highfive'),
    row('\u{1F44D}', 'thumbs up', 'like yes approve'),
    row('\u{1F44E}', 'thumbs down', 'dislike no'),
    row('\u{1F44C}', 'OK hand', 'ok perfect'),
    row('\u{1F44F}', 'clapping hands', 'applause praise'),
    row('\u{1F450}', 'open hands', 'hug open'),
    row('\u{1F64C}', 'raising hands', 'celebrate praise'),
    row('\u{1F64F}', 'folded hands', 'pray thanks'),
    row('\u{1F91D}', 'handshake', 'deal agreement'),
    row('\u{1F918}', 'sign of the horns', 'rock metal'),
    row('\u{1F448}', 'backhand index pointing left', 'point direction'),
    row('\u{1F449}', 'backhand index pointing right', 'point direction'),
    row('\u{261D}\uFE0F', 'index pointing up', 'point one'),
    row('\u{270D}\uFE0F', 'writing hand', 'write pen'),
    row('\u{1F91E}', 'crossed fingers', 'luck hope'),
    row('\u{1F4AA}', 'flexed biceps', 'muscle strong'),
    row('\u{1F9E0}', 'brain', 'mind smart'),
    row('\u{1F440}', 'eyes', 'look see watch'),
    row('\u{1F9E3}', 'ear', 'hear listen'),
    row('\u{1F443}', 'nose', 'smell'),
    row('\u{1F9B0}', 'red hair', 'ginger hair'),
    row('\u{1F6C0}', 'bathing', 'bath shower'),
    row('\u{1F6CD}', 'shower', 'bath clean'),
    row('\u{1F9BD}', 'probing cane', 'blind accessibility'),
    row('\u{1F9BC}', 'motorized wheelchair', 'accessibility'),
    row('\u{1F9AF}', 'person with white cane', 'blind accessibility'),
    row('\u{1F3CB}\uFE0F', 'weight lifting', 'gym sport'),
    row('\u{1F46B}', 'woman and man holding hands', 'couple family'),
    row('\u{1F46C}', 'men holding hands', 'couple'),
    row('\u{1F46D}', 'women holding hands', 'couple'),
    row('\u{1F48F}', 'kiss', 'love couple'),
    row('\u{1F491}', 'couple with heart', 'love wedding'),
    row('\u{1F46E}', 'police officer', 'cop law'),
    row('\u{1F477}', 'person with skullcap', 'worker'),
    row('\u{1F977}', 'ninja', 'martialarts'),
    row('\u{1F9D7}', 'person climbing', 'sport'),
    row('\u{1F938}', 'person cartwheeling', 'gymnastics'),
    row('\u{1F93C}', 'people wrestling', 'sport wrestle'),
    row('\u{1F46F}', 'people with bunny ears', 'costume'),
    row('\u{1F9D5}', 'woman with headscarf', 'hijab clothing'),
    row('\u{1F45E}', 'man’s shoe', 'clothing'),
    row('\u{1F455}', 't-shirt', 'clothing shirt'),
    row('\u{1F456}', 'jeans', 'clothing trousers'),
    row('\u{1F454}', 'necktie', 'clothing formal'),
    row('\u{1F457}', 'dress', 'clothing'),
    row('\u{1F458}', 'kimono', 'clothing'),
    row('\u{1F97B}', 'sari', 'clothing'),
    row('\u{1F459}', 'bikini', 'clothing swimsuit'),
    row('\u{1F45A}', 'woman’s clothes', 'clothing dress'),
    row('\u{1FA71}', 'one-piece swimsuit', 'clothing swimsuit'),
    row('\u{1F451}', 'woman’s hat', 'clothing'),
    row('\u{1F452}', 'glasses', 'clothing eyewear'),
    row('\u{1F3A9}', 'top hat', 'clothing'),
    row('\u{1F393}', 'graduation cap', 'clothing education'),
    row('\u{1F9E2}', 'billed cap', 'clothing hat'),
    row('\u{1F45C}', 'running shoe', 'clothing sneaker'),
    row('\u{1F461}', 'woman’s heel', 'clothing shoe'),
    row('\u{1F6E0}\uFE0F', 'hammer and wrench', 'tool repair'),
];

const NATURE: readonly EmojiEntry[] = [
    row('\u{1F412}', 'monkey', 'animal primate'),
    row('\u{1F98D}', 'gorilla', 'animal ape'),
    row('\u{1F415}', 'dog', 'animal pet'),
    row('\u{1F436}', 'dog face', 'animal pet'),
    row('\u{1F429}', 'poodle', 'dog animal'),
    row('\u{1F43A}', 'wolf', 'animal'),
    row('\u{1F98A}', 'fox', 'animal'),
    row('\u{1F431}', 'cat face', 'animal pet'),
    row('\u{1F981}', 'lion', 'animal cat'),
    row('\u{1F42F}', 'tiger face', 'animal cat'),
    row('\u{1F405}', 'tiger', 'animal'),
    row('\u{1F406}', 'leopard', 'animal cat'),
    row('\u{1F434}', 'horse face', 'animal'),
    row('\u{1F984}', 'unicorn', 'animal fantasy'),
    row('\u{1FAC}', 'unicorn face', 'animal fantasy'),
    row('\u{1F993}', 'zebra', 'animal'),
    row('\u{1F98C}', 'deer', 'animal'),
    row('\u{1F42E}', 'cow face', 'animal'),
    row('\u{1F437}', 'pig face', 'animal'),
    row('\u{1F42A}', 'camel', 'animal desert'),
    row('\u{1F992}', 'giraffe', 'animal'),
    row('\u{1F418}', 'elephant', 'animal'),
    row('\u{1F99B}', 'rhinoceros', 'animal'),
    row('\u{1F430}', 'rabbit face', 'animal pet'),
    row('\u{1F43B}', 'bear', 'animal'),
    row('\u{1F428}', 'koala', 'animal'),
    row('\u{1F43C}', 'panda', 'animal'),
    row('\u{1F9A5}', 'sloth', 'animal'),
    row('\u{1F9A6}', 'otter', 'animal'),
    row('\u{1F998}', 'kangaroo', 'animal'),
    row('\u{1F414}', 'chicken', 'bird animal'),
    row('\u{1F427}', 'penguin', 'bird animal'),
    row('\u{1F986}', 'duck', 'bird animal'),
    row('\u{1F989}', 'owl', 'bird animal'),
    row('\u{1F438}', 'frog', 'animal'),
    row('\u{1F422}', 'turtle', 'animal reptile'),
    row('\u{1F40D}', 'snake', 'animal reptile'),
    row('\u{1F433}', 'dragon face', 'animal fantasy'),
    row('\u{1F996}', 'T-Rex', 'animal dinosaur'),
    row('\u{1F42C}', 'dolphin', 'animal sea'),
    row('\u{1F988}', 'shark', 'animal sea'),
    row('\u{1F419}', 'octopus', 'animal sea'),
    row('\u{1F41B}', 'bug', 'animal insect'),
    row('\u{1F98B}', 'butterfly', 'animal insect'),
    row('\u{1F577}\uFE0F', 'spider', 'animal insect'),
    row('\u{1F338}', 'cherry blossom', 'flower spring'),
    row('\u{1F33A}', 'hibiscus', 'flower'),
    row('\u{1F33B}', 'sunflower', 'flower sun'),
    row('\u{1F337}', 'tulip', 'flower'),
    row('\u{1F331}', 'seedling', 'plant nature'),
    row('\u{1F332}', 'evergreen tree', 'plant nature'),
    row('\u{1F333}', 'deciduous tree', 'plant nature'),
    row('\u{1F334}', 'palm tree', 'plant nature'),
    row('\u{1F335}', 'cactus', 'plant'),
    row('\u{1F340}', 'four leaf clover', 'plant luck'),
    row('\u{1F341}', 'maple leaf', 'plant autumn'),
    row('\u{1F342}', 'fallen leaf', 'plant autumn'),
    row('\u{1F343}', 'leaf fluttering in wind', 'plant wind'),
];

const FOOD: readonly EmojiEntry[] = [
    row('\u{1F347}', 'grapes', 'fruit'),
    row('\u{1F348}', 'melon', 'fruit'),
    row('\u{1F349}', 'watermelon', 'fruit'),
    row('\u{1F34A}', 'tangerine', 'fruit citrus'),
    row('\u{1F34B}', 'lemon', 'fruit citrus'),
    row('\u{1F34C}', 'banana', 'fruit'),
    row('\u{1F34D}', 'pineapple', 'fruit'),
    row('\u{1F34E}', 'red apple', 'fruit'),
    row('\u{1F350}', 'pear', 'fruit'),
    row('\u{1F351}', 'peach', 'fruit'),
    row('\u{1F352}', 'cherries', 'fruit'),
    row('\u{1F353}', 'strawberry', 'fruit'),
    row('\u{1F95D}', 'kiwi fruit', 'fruit'),
    row('\u{1F34F}', 'tomato', 'fruit vegetable'),
    row('\u{1F950}', 'croissant', 'food bread'),
    row('\u{1F956}', 'flatbread', 'food bread'),
    row('\u{1F968}', 'pretzel', 'food'),
    row('\u{1F96F}', 'bagel', 'food bread'),
    row('\u{1F95E}', 'pancakes', 'food breakfast'),
    row('\u{1F9C0}', 'cheese wedge', 'food dairy'),
    row('\u{1F356}', 'meat on bone', 'food'),
    row('\u{1F357}', 'poultry leg', 'food chicken'),
    row('\u{1F969}', 'cut of meat', 'food'),
    row('\u{1F953}', 'bacon', 'food'),
    row('\u{1F354}', 'hamburger', 'food'),
    row('\u{1F35F}', 'french fries', 'food'),
    row('\u{1F355}', 'pizza', 'food'),
    row('\u{1F32D}', 'hot dog', 'food'),
    row('\u{1F96A}', 'sandwich', 'food lunch'),
    row('\u{1F32E}', 'taco', 'food'),
    row('\u{1F32F}', 'burrito', 'food'),
    row('\u{1F957}', 'green salad', 'food vegetable'),
    row('\u{1F37F}', 'popcorn', 'food snack'),
    row('\u{1F363}', 'sushi', 'food japanese'),
    row('\u{1F364}', 'fish cake with swirl', 'food'),
    row('\u{1F365}', 'soft ice cream', 'food dessert'),
    row('\u{1F366}', 'soft serve', 'food dessert'),
    row('\u{1F368}', 'ice cream', 'food dessert'),
    row('\u{1F382}', 'birthday cake', 'food dessert'),
    row('\u{1F9C1}', 'cupcake', 'food dessert'),
    row('\u{1F967}', 'pie', 'food dessert'),
    row('\u{1F36B}', 'chocolate bar', 'food dessert'),
    row('\u{1F36C}', 'candy', 'food sweet'),
    row('\u{1F36D}', 'lollipop', 'food sweet'),
    row('\u{2615}', 'hot beverage', 'drink coffee tea'),
    row('\u{1FAD6}', 'teapot', 'drink tea'),
    row('\u{1F376}', 'teacup without handle', 'drink tea'),
    row('\u{1F377}', 'wine glass', 'drink'),
    row('\u{1F378}', 'cocktail glass', 'drink'),
    row('\u{1F37A}', 'beer mug', 'drink'),
    row('\u{1F942}', 'clinking glasses', 'drink cheers'),
    row('\u{1F962}', 'chopsticks', 'food utensil'),
    row('\u{1F374}', 'fork and knife', 'food utensil'),
    row('\u{1F944}', 'spoon', 'food utensil'),
];

const TRAVEL: readonly EmojiEntry[] = [
    row('\u{1F30D}', 'globe showing Europe-Africa', 'world earth'),
    row('\u{1F30E}', 'globe showing Americas', 'world earth'),
    row('\u{1F30F}', 'globe showing Asia-Australia', 'world earth'),
    row('\u{1F5FA}\uFE0F', 'world map', 'map'),
    row('\u{26F0}\uFE0F', 'mountain', 'travel nature'),
    row('\u{1F30B}', 'volcano', 'travel nature'),
    row('\u{1F3D5}\uFE0F', 'camping', 'travel nature'),
    row('\u{1F3D6}\uFE0F', 'beach with umbrella', 'travel sea'),
    row('\u{1F3DC}', 'desert', 'travel nature'),
    row('\u{1F3DD}\uFE0F', 'desert island', 'travel sea'),
    row('\u{1F3DE}\uFE0F', 'national park', 'travel nature'),
    row('\u{1F3DF}\uFE0F', 'stadium', 'travel sport'),
    row('\u{1F3DB}\uFE0F', 'classical building', 'travel'),
    row('\u{1F3D7}\uFE0F', 'buildings', 'travel'),
    row('\u{1F3E0}', 'house', 'home building'),
    row('\u{1F3E1}', 'house with garden', 'home'),
    row('\u{1F3E2}', 'office building', 'work'),
    row('\u{1F3E4}', 'post office', 'building'),
    row('\u{1F3E5}', 'hospital', 'building health'),
    row('\u{1F3E8}', 'hotel', 'travel building'),
    row('\u{1F3EA}', 'convenience store', 'building shop'),
    row('\u{1F3EB}', 'school', 'building education'),
    row('\u{1F3EF}', 'castle', 'building'),
    row('\u{26EA}', 'church', 'building religion'),
    row('\u{26E9}\uFE0F', 'shinto torii gate', 'japan'),
    row('\u{1F6D1}', 'fountain', 'building'),
    row('\u{1F5FC}\uFE0F', 'tower', 'building'),
    row('\u{1F5FD}', 'Statue of Liberty', 'travel usa'),
    row('\u{1F5DB}\uFE0F', 'Mount Rushmore', 'travel usa'),
    row('\u{1F9F2}', 'carousel horse', 'travel fair'),
    row('\u{1F680}', 'rocket', 'travel space'),
    row('\u{1F6F8}', 'flying saucer', 'travel space'),
    row('\u{1F6CE}\uFE0F', 'bellhop bell', 'travel hotel'),
    row('\u{1F9F3}', 'luggage', 'travel'),
    row('\u{1F9ED}', 'compass', 'travel navigate'),
    row('\u{231B}\uFE0F', 'hourglass done', 'time'),
    row('\u{23F0}', 'alarm clock', 'time'),
    row('\u{1F682}', 'locomotive', 'travel train'),
    row('\u{1F686}', 'train', 'travel'),
    row('\u{1F687}', 'metro', 'travel subway'),
    row('\u{1F689}', 'station', 'travel'),
    row('\u{1F68C}', 'bus', 'travel'),
    row('\u{1F691}', 'ambulance', 'emergency'),
    row('\u{1F693}', 'police car', 'emergency'),
    row('\u{1F695}', 'taxi', 'travel'),
    row('\u{1F697}', 'automobile', 'travel car'),
    row('\u{1F699}', 'sport utility vehicle', 'car'),
    row('\u{1F6B2}', 'bicycle', 'vehicle'),
    row('\u{1F6F4}', 'kick scooter', 'vehicle'),
    row('\u{26FA}', 'tent', 'travel camping'),
];

const ACTIVITIES: readonly EmojiEntry[] = [
    row('\u{1F383}', 'jack-o-lantern', 'halloween pumpkin'),
    row('\u{1F384}', 'Christmas tree', 'christmas'),
    row('\u{1F386}', 'fireworks', 'celebration'),
    row('\u{2728}', 'sparkles', 'celebration magic'),
    row('\u{1F388}', 'balloon', 'party'),
    row('\u{1F389}', 'party popper', 'party celebration'),
    row('\u{1F38A}', 'confetti ball', 'party'),
    row('\u{1F381}', 'wrapped gift', 'present birthday'),
    row('\u{1F397}\uFE0F', 'reminder ribbon', 'awareness'),
    row('\u{1F3AB}', 'ticket', 'event'),
    row('\u{1F3C6}', 'trophy', 'award win'),
    row('\u{1F947}', '1st place medal', 'award win'),
    row('\u{1F3BE}', 'tennis', 'sport'),
    row('\u{1F3C8}', 'American football', 'sport'),
    row('\u{1F3D1}', 'field hockey', 'sport'),
    row('\u{1F3D2}', 'ice hockey', 'sport'),
    row('\u{1F3B3}', 'bowling', 'sport'),
    row('\u{1F3D0}', 'volleyball', 'sport'),
    row('\u{1F94E}', 'lacrosse', 'sport'),
    row('\u{26BD}', 'soccer ball', 'sport football'),
    row('\u{26BE}', 'baseball', 'sport'),
    row('\u{1F3CA}', 'swimming', 'sport'),
    row('\u{1F3BF}', 'skis', 'sport winter'),
    row('\u{26F7}\uFE0F', 'skier', 'sport winter'),
    row('\u{1F6F9}', 'skateboard', 'sport'),
    row('\u{1F3BD}', 'running shirt', 'sport'),
    row('\u{1F3AF}', 'bullseye', 'sport game target'),
    row('\u{1F3B1}', 'pool 8 ball', 'game'),
    row('\u{1F3B2}', 'game die', 'game dice'),
    row('\u{1F0CF}', 'joker', 'game cards'),
    row('\u{1F579}\uFE0F', 'joystick', 'game'),
    row('\u{1F3AE}', 'video game', 'game'),
    row('\u{1F9E9}', 'puzzle piece', 'game'),
    row('\u{1F9F8}', 'teddy bear', 'toy'),
    row('\u{1FA85}', 'pinata', 'toy party'),
    row('\u{1FA86}', 'nesting dolls', 'toy'),
    row('\u{1F3AD}', 'performing arts', 'theatre'),
    row('\u{1F3BC}', 'musical score', 'music'),
    row('\u{1F3A4}', 'microphone', 'music sing'),
    row('\u{1F3A7}', 'headphones', 'music listen'),
    row('\u{1F3B8}', 'guitar', 'music'),
    row('\u{1F941}', 'drum', 'music'),
    row('\u{1F3A8}', 'artist palette', 'art paint'),
    row('\u{1F58C}\uFE0F', 'paintbrush', 'art paint'),
    row('\u{1F9F5}', 'thread', 'sew'),
    row('\u{1FAA1}', 'sewing needle', 'sew'),
];

const OBJECTS: readonly EmojiEntry[] = [
    row('\u{1F9F1}', 'brick', 'object build'),
    row('\u{1FA91}', 'shovel', 'object tool'),
    row('\u{1FAA9}', 'mirror ball', 'object'),
    row('\u{1F9EF}', 'fire extinguisher', 'object safety'),
    row('\u{1F6E0}\uFE0F', 'hammer and wrench', 'tool'),
    row('\u{2692}\uFE0F', 'hammer and pick', 'tool'),
    row('\u{1F527}', 'wrench', 'tool'),
    row('\u{1FA9B}', 'screwdriver', 'tool'),
    row('\u{2699}\uFE0F', 'gear', 'tool cog'),
    row('\u{1F5DC}\uFE0F', 'clamp', 'tool'),
    row('\u{1F512}', 'locked with key', 'object security'),
    row('\u{1F513}', 'unlocked', 'object security'),
    row('\u{1F511}', 'key', 'object'),
    row('\u{1F5DD}\uFE0F', 'old key', 'object'),
    row('\u{1F528}', 'hammer', 'tool'),
    row('\u{1F52B}', 'water pistol', 'object toy'),
    row('\u{1FA93}', 'carpentry saw', 'tool'),
    row('\u{1F4A1}', 'light bulb', 'object idea'),
    row('\u{1F526}', 'flashlight', 'object'),
    row('\u{1F52C}', 'microscope', 'object lab'),
    row('\u{1F52D}', 'telescope', 'object'),
    row('\u{1F4BB}', 'laptop', 'object computer'),
    row('\u{1F5A5}\uFE0F', 'desktop computer', 'object computer'),
    row('\u{1F5A8}\uFE0F', 'printer', 'object office'),
    row('\u{2328}\uFE0F', 'keyboard', 'object computer'),
    row('\u{1F5B1}\uFE0F', 'computer mouse', 'object computer'),
    row('\u{1F4BE}', 'floppy disk', 'object'),
    row('\u{1F4DA}', 'books', 'object reading'),
    row('\u{1F4D3}', 'notebook', 'object writing'),
    row('\u{1F4CA}', 'bar chart', 'object data'),
    row('\u{1F4CB}', 'clipboard', 'object office'),
    row('\u{1F4CC}', 'pushpin', 'object office'),
    row('\u{1F4CE}', 'paperclip', 'object office'),
    row('\u{1F4CF}', 'straight ruler', 'object office'),
    row('\u{2702}\uFE0F', 'scissors', 'object office'),
    row('\u{1F5D1}\uFE0F', 'card file box', 'object office'),
    row('\u{1F5D2}\uFE0F', 'file cabinet', 'object office'),
    row('\u{1F5D3}\uFE0F', 'wastebasket', 'object office'),
    row('\u{1F9FC}', 'window', 'object house'),
    row('\u{1F6D9}', 'elevator', 'object building'),
    row('\u{1F6DD}', 'radio', 'object'),
    row('\u{1F6DE}', 'video camera', 'object record'),
    row('\u{26AF}', 'white flag', 'object surrender'),
];

const SYMBOLS: readonly EmojiEntry[] = [
    row('\u{1F520}', 'input latin letters', 'symbol text'),
    row('\u{1F521}', 'lowercase', 'symbol text'),
    row('\u{1F522}', 'uppercase', 'symbol text'),
    row('\u{1F170}\uFE0F', 'A button', 'symbol letter'),
    row('\u{1F18E}', 'AB button', 'symbol letters'),
    row('\u{1F191}\uFE0F', 'CL button', 'symbol'),
    row('\u{1F192}\uFE0F', 'COOL button', 'symbol'),
    row('\u{1F193}\uFE0F', 'FREE button', 'symbol'),
    row('\u{1F194}\uFE0F', 'ID button', 'symbol'),
    row('\u{1F195}\uFE0F', 'NEW button', 'symbol'),
    row('\u{1F196}\uFE0F', 'OK button', 'symbol'),
    row('\u{1F197}\uFE0F', 'SOS button', 'symbol'),
    row('\u{1F198}\uFE0F', 'VS button', 'symbol'),
    row('\u{1F199}\uFE0F', 'UP button', 'symbol'),
    row('\u{1F534}', 'red circle', 'symbol shape'),
    row('\u{1F7E0}', 'orange circle', 'symbol shape'),
    row('\u{1F7E1}', 'yellow circle', 'symbol shape'),
    row('\u{1F7E2}', 'green circle', 'symbol shape'),
    row('\u{1F535}', 'blue circle', 'symbol shape'),
    row('\u{1F7E3}', 'purple circle', 'symbol shape'),
    row('\u{26AA}', 'black circle', 'symbol shape'),
    row('\u{26AB}', 'white circle', 'symbol shape'),
    row('\u{1F7E7}', 'red square', 'symbol shape'),
    row('\u{1F7E8}', 'yellow square', 'symbol shape'),
    row('\u{1F7E9}', 'green square', 'symbol shape'),
    row('\u{1F7E6}', 'blue square', 'symbol shape'),
    row('\u{1F7EA}', 'purple square', 'symbol shape'),
    row('\u{2B1B}', 'black large square', 'symbol shape'),
    row('\u{2B1C}', 'white large square', 'symbol shape'),
    row('\u{1F536}', 'large orange diamond', 'symbol shape'),
    row('\u{1F537}', 'large blue diamond', 'symbol shape'),
    row('\u{1F53A}', 'red triangle pointed up', 'symbol shape'),
    row('\u{1F53B}', 'red triangle pointed down', 'symbol shape'),
    row('\u{25B6}\uFE0F', 'black right-pointing triangle', 'symbol shape'),
    row('\u{25C0}\uFE0F', 'black left-pointing triangle', 'symbol shape'),
    row('\u{25B2}\uFE0F', 'black up-pointing triangle', 'symbol shape'),
    row('\u{25BC}\uFE0F', 'black down-pointing triangle', 'symbol shape'),
    row('\u{2753}', 'red question mark', 'symbol'),
    row('\u{2757}', 'red exclamation mark', 'symbol'),
    row('\u{2049}\uFE0F', 'red exclamation question mark', 'symbol'),
    row('\u{1F4A4}', 'zzz', 'symbol sleep'),
    row('\u{267B}', 'recycling symbol', 'symbol green'),
    row('\u{262E}', 'information', 'symbol info'),
    row('\u{26A0}\uFE0F', 'warning', 'symbol caution'),
    row('\u{2714}\uFE0F', 'check mark button', 'symbol done yes'),
    row('\u{2716}\uFE0F', 'multiply', 'symbol no'),
    row('\u{2795}', 'plus', 'symbol math'),
    row('\u{2796}', 'minus', 'symbol math'),
    row('\u{2797}', 'divide', 'symbol math'),
    row('\u{1F6AB}', 'prohibited', 'symbol no'),
    row('\u{1F6B3}', 'no bicycles', 'symbol no'),
    row('\u{1F6AD}', 'no smoking', 'symbol no'),
    row('\u{1F6AF}', 'no littering', 'symbol no'),
    row('\u{1F6B1}', 'non-potable water', 'symbol no'),
    row('\u{1F51E}', 'no one under eighteen', 'symbol age'),
    row('\u{1F3C1}', 'chequered flag', 'symbol sport'),
    row('\u{1F6A9}', 'triangular flag', 'symbol'),
    row('\u{1F38C}', 'crossed flags', 'symbol'),
    row('\u{1F3F4}', 'black flag', 'symbol'),
    row('\u{1F3F3}\uFE0F', 'white flag', 'symbol surrender'),
    row('\u{1F3F3}\u200D\u{1F308}', 'rainbow flag', 'symbol pride'),
];

const FLAGS: readonly EmojiEntry[] = [
    row('\u{1F1E6}\u{1F1E8}', 'flag: Bolivia', 'flag country'),
    row('\u{1F1E7}\u{1F1F7}', 'flag: Brazil', 'flag country'),
    row('\u{1F1E9}\u{1F1EA}', 'flag: Germany', 'flag country deutschland'),
    row('\u{1F1EB}\u{1F1F7}', 'flag: France', 'flag country'),
    row('\u{1F1EE}\u{1F1F3}', 'flag: United Kingdom', 'flag country britain uk'),
    row('\u{1F1EF}\u{1F1F5}', 'flag: Japan', 'flag country japan'),
    row('\u{1F1F3}\u{1F1F1}', 'flag: United States', 'flag country usa'),
    row('\u{1F1F8}\u{1F1EA}', 'flag: Sweden', 'flag country'),
    row('\u{1F1F8}\u{1F1F0}', 'flag: Denmark', 'flag country'),
    row('\u{1F1F9}\u{1F1F7}', 'flag: Turkey', 'flag country'),
    row('\u{1F1FA}\u{1F1F8}', 'flag: Spain', 'flag country'),
];

/**
 * The nine category sections, in `setup_section`'s registration order. `recent` is NOT
 * here: its emoji come from `GSettings` (`recently-used-emoji`), so the element owns
 * that list and this table does not know about it.
 */
export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
    { id: 'people', heading: 'Smileys & People', tooltip: 'Smileys & People', entries: PEOPLE },
    { id: 'body', heading: 'Body & Clothing', tooltip: 'Body & Clothing', entries: BODY },
    { id: 'nature', heading: 'Animals & Nature', tooltip: 'Animals & Nature', entries: NATURE },
    { id: 'food', heading: 'Food & Drink', tooltip: 'Food & Drink', entries: FOOD },
    { id: 'travel', heading: 'Travel & Places', tooltip: 'Travel & Places', entries: TRAVEL },
    { id: 'activities', heading: 'Activities', tooltip: 'Activities', entries: ACTIVITIES },
    { id: 'objects', heading: 'Objects', tooltip: 'Objects', entries: OBJECTS },
    { id: 'symbols', heading: 'Symbols', tooltip: 'Symbols', entries: SYMBOLS },
    { id: 'flags', heading: 'Flags', tooltip: 'Flags', entries: FLAGS },
];

/** The section ids in order, `recent` FIRST — the struct order of `GtkEmojiChooser`. */
export const EMOJI_SECTION_IDS: readonly string[] = ['recent', ...EMOJI_CATEGORIES.map((c) => c.id)];

/** The heading of a section, `''` for `recent` — the one with no heading widget at all. */
export function emojiHeading(id: string): string {
    return EMOJI_CATEGORIES.find((category) => category.id === id)?.heading ?? '';
}

/** The toolbar button's tooltip for a section: its heading, or `Recent` for the first. */
export function emojiTooltip(id: string): string {
    return id === 'recent' ? 'Recent' : (EMOJI_CATEGORIES.find((category) => category.id === id)?.tooltip ?? '');
}
