<!-- GENERATED by scripts/generate-adwaita-framework-snippets.mjs — do not edit.

     Every gallery block that carries a Vue snippet, in ONE single-file component,
     compiled by `@gjsify/rolldown-plugin-vue` and asserted against the real GTK
     widget tree. The markup is the SAME TEXT the website ships. -->
<template>
    <gtk-box orientation="vertical" :spacing="24">
        <adw-preferences-group
            title="Account"
            description="Manage how this device signs in and syncs."
        >
            <adw-entry-row
                title="Display name"
                text="Grace Hopper"
            />
            <adw-switch-row
                title="Sync over Wi-Fi only"
                subtitle="Avoid using mobile data for backups"
                :active="true"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-action-row
                title="Wi-Fi"
                subtitle="Connected to Highgarden 5GHz"
                :activatable="true"
            >
                <gtk-image
                    slot="prefix"
                    icon-name="network-wireless-symbolic"
                />
                <gtk-button
                    slot="suffix"
                    icon-name="go-next-symbolic"
                    :css-classes="['flat']"
                    valign="center"
                />
            </adw-action-row>
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-preferences-row
                title="A plain preferences row"
                :use-markup="true"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-switch-row
                title="Automatic updates"
                subtitle="Download and install updates without asking"
                :active="true"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-entry-row
                title="Display name"
                text="Ada Lovelace"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-password-entry-row
                title="Password"
                text="correct-horse-battery"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-expander-row
                title="Proxy settings"
                subtitle="Route traffic through a custom proxy"
                :expanded="true"
            >
                <gtk-button
                    slot="prefix"
                    label="Test"
                />
                <adw-entry-row
                    title="Host"
                    text="proxy.example.com"
                />
                <adw-switch-row title="Use authentication" />
            </adw-expander-row>
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-button-row
                title="Add account"
                start-icon-name="list-add-symbolic"
                :css-classes="['suggested-action']"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-combo-row
                title="Accent colour"
                subtitle="Used to highlight selected items"
                :model="['Blue', 'Teal', 'Green', 'Orange', 'Purple']"
                :selected="1"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-spin-row
                title="Font size"
                :adjustment="{ lower: 0, upper: 100, value: 16, stepIncrement: 1 }"
            />
        </adw-preferences-group>
        <gtk-button :css-classes="['suggested-action', 'pill']">
            <adw-button-content
                label="Download"
                icon-name="folder-download-symbolic"
            />
        </gtk-button>
        <gtk-box
            orientation="horizontal"
            :spacing="12"
            halign="center"
        >
            <gtk-button
                label="Pill"
                :css-classes="['pill']"
            />
            <gtk-button
                icon-name="list-add-symbolic"
                :css-classes="['circular']"
            />
            <gtk-button
                label="Suggested"
                :css-classes="['suggested-action']"
            />
            <gtk-button
                label="Delete"
                :css-classes="['destructive-action']"
            />
            <gtk-button
                label="Flat"
                :css-classes="['flat']"
            />
        </gtk-box>
        <adw-split-button
            label="Save"
            :menu-model="[
                { label: 'Save as…', action: 'app.save-as' },
                { label: 'Export', action: 'app.export' },
                { label: 'Print', action: 'app.print' },
            ]"
        />
        <gtk-box
            orientation="horizontal"
            :spacing="12"
            halign="center"
        >
            <gtk-toggle-button
                label="Mute"
                :active="true"
            />
            <gtk-toggle-button label="Loop" />
        </gtk-box>
        <gtk-box
            orientation="vertical"
            :spacing="6"
            halign="center"
        >
            <gtk-link-button
                uri="https://gnome.org"
                label="GNOME"
            />
            <gtk-link-button
                uri="https://docs.gtk.org/gtk4/"
                :visited="true"
            />
        </gtk-box>
        <gtk-scale-button
            :icons="['audio-volume-muted-symbolic', 'audio-volume-low-symbolic', 'audio-volume-high-symbolic']"
            :value="70"
        />
        <gtk-color-dialog-button :dialog="{  }" />
        <gtk-font-dialog-button
            :dialog="{  }"
            font-desc="Sans Bold 12"
        />
        <gtk-menu-button
            icon-name="open-menu-symbolic"
            :css-classes="['flat']"
            :menu-model="[
                { label: 'Preferences', action: 'app.preferences' },
                { label: 'Keyboard Shortcuts', action: 'win.show-help-overlay' },
                { label: 'About', action: 'app.about' },
            ]"
        />
        <gtk-entry
            placeholder-text="Search files…"
            :width-request="280"
        />
        <gtk-drop-down
            :model="['Automatic', 'Always', 'Never', 'When busy']"
            :selected="0"
            halign="center"
        />
        <gtk-box
            orientation="vertical"
            :spacing="12"
        >
            <gtk-scale
                :adjustment="{ lower: 0, upper: 100, value: 40, stepIncrement: 1, pageIncrement: 10 }"
                :digits="0"
                :draw-value="true"
                value-pos="top"
                :width-request="320"
            />
        </gtk-box>
        <gtk-box
            orientation="vertical"
            :spacing="12"
        >
            <gtk-spin-button
                :adjustment="{ lower: 0, upper: 10, value: 5, stepIncrement: 1, pageIncrement: 2 }"
                :digits="0"
                :numeric="true"
                :snap-to-ticks="true"
                halign="center"
            />
        </gtk-box>
        <gtk-password-entry
            :show-peek-icon="true"
            placeholder-text="Password"
        />
        <gtk-search-entry
            placeholder-text="Search…"
            :search-delay="150"
        />
        <gtk-check-button
            label="Enable networking"
            :active="true"
        />
        <gtk-switch
            :active="true"
            :state="true"
            halign="center"
        />
        <gtk-progress-bar
            :fraction="0.4"
            :show-text="true"
            :width-request="320"
            halign="center"
        />
        <gtk-level-bar
            :max-value="5"
            mode="discrete"
            :value="3"
            :width-request="240"
            halign="center"
        />
        <gtk-spinner
            :spinning="true"
            :width-request="32"
            :height-request="32"
        />
        <gtk-graphics-offload
            enabled="enabled"
            :black-background="true"
            :width-request="280"
            :height-request="96"
        >
            <gtk-label label="The child of an offloaded layer" />
        </gtk-graphics-offload>
        <gtk-gl-area
            :auto-render="true"
            :has-depth-buffer="false"
            :width-request="240"
            :height-request="160"
        />
        <gtk-box
            orientation="vertical"
            :spacing="16"
        >
            <gtk-drawing-area
                :content-width="160"
                :content-height="120"
            />
            <gtk-drawing-area
                :content-width="160"
                :content-height="60"
            />
        </gtk-box>
        <gtk-frame
            label="Details"
            :label-xalign="0"
        >
            <gtk-label label="A framed region: the label sits in the top edge of the border." />
        </gtk-frame>
        <gtk-aspect-frame
            :ratio="2"
            :obey-child="false"
            :xalign="0.5"
            :yalign="0.5"
        >
            <gtk-label label="The frame gives this child the ratio above, and puts it where xalign and yalign say." />
        </gtk-aspect-frame>
        <gtk-box
            orientation="vertical"
            :spacing="12"
        >
            <gtk-label label="Above" />
            <gtk-separator />
            <gtk-label label="Below" />
            <gtk-separator
                orientation="vertical"
                :css-classes="['spacer']"
            />
        </gtk-box>
        <gtk-overlay
            :width-request="260"
            :height-request="160"
        >
            <gtk-label
                label="Main child"
                halign="center"
                valign="center"
                :css-classes="['dimmed']"
            />
            <gtk-label
                slot="overlay"
                label="2"
                halign="end"
                valign="end"
            />
        </gtk-overlay>
        <gtk-text
            text="correct-horse-battery"
            placeholder-text="A single line"
            :max-length="32"
        />
        <gtk-editable-label text="Ada Lovelace" />
        <adw-bin>
            <gtk-label
                label="The one child of this bin."
                :wrap="true"
                :xalign="0"
                :css-classes="['card']"
            />
        </adw-bin>
        <adw-breakpoint-bin>
            <gtk-label
                label="Wide"
                ellipsize="end"
                :css-classes="['title-1']"
            />
        </adw-breakpoint-bin>
        <adw-clamp
            :maximum-size="400"
            :tightening-threshold="300"
        >
            <gtk-label
                label="This content is clamped: it stops growing past the maximum size and stays centred."
                :wrap="true"
                :xalign="0"
                :css-classes="['card']"
            />
        </adw-clamp>
        <adw-header-bar>
            <gtk-button
                slot="start"
                icon-name="go-previous-symbolic"
                :css-classes="['flat']"
            />
            <adw-window-title
                slot="title"
                title="Text Editor"
                subtitle="notes.md"
            />
            <gtk-menu-button
                slot="end"
                icon-name="open-menu-symbolic"
                :css-classes="['flat']"
            />
        </adw-header-bar>
        <adw-toolbar-view>
            <adw-header-bar slot="top">
                <adw-window-title
                    slot="title"
                    title="Documents"
                    subtitle="12 items"
                />
            </adw-header-bar>
            <adw-status-page
                slot="content"
                icon-name="folder-documents-symbolic"
                title="Your library"
                description="Content sits between the toolbars and scrolls independently of them."
            />
            <gtk-box
                slot="bottom"
                :css-classes="['toolbar']"
                :spacing="6"
            >
                <gtk-button
                    icon-name="list-add-symbolic"
                    :css-classes="['flat']"
                />
                <gtk-button
                    icon-name="list-remove-symbolic"
                    :css-classes="['flat']"
                />
                <gtk-label
                    label="Selection: none"
                    :hexpand="true"
                />
                <gtk-button
                    icon-name="send-to-symbolic"
                    :css-classes="['flat']"
                />
            </gtk-box>
        </adw-toolbar-view>
        <adw-wrap-box
            :child-spacing="8"
            :line-spacing="8"
        >
            <gtk-button
                label="Design"
                :css-classes="['pill']"
            />
            <gtk-button
                label="Adwaita"
                :css-classes="['pill']"
            />
            <gtk-button
                label="GNOME"
                :css-classes="['pill']"
            />
            <gtk-button
                label="GTK"
                :css-classes="['pill']"
            />
            <gtk-button
                label="TypeScript"
                :css-classes="['pill']"
            />
            <gtk-button
                label="Storybook"
                :css-classes="['pill']"
            />
            <gtk-button
                label="Wrapping"
                :css-classes="['pill']"
            />
            <gtk-button
                label="Layout"
                :css-classes="['pill']"
            />
        </adw-wrap-box>
        <adw-overlay-split-view :show-sidebar="true">
            <adw-toolbar-view slot="sidebar">
                <adw-header-bar slot="top">
                    <adw-window-title
                        slot="title"
                        title="Library"
                    />
                </adw-header-bar>
                <adw-status-page
                    slot="content"
                    icon-name="folder-music-symbolic"
                    title="Sections"
                />
            </adw-toolbar-view>
            <adw-toolbar-view slot="content">
                <adw-header-bar slot="top">
                    <adw-window-title
                        slot="title"
                        title="Your Library"
                    />
                </adw-header-bar>
                <adw-status-page
                    slot="content"
                    icon-name="folder-music-symbolic"
                    title="Your Library"
                    description="Toggle the sidebar to browse sections."
                />
            </adw-toolbar-view>
        </adw-overlay-split-view>
        <adw-navigation-split-view :show-content="true">
            <adw-navigation-page
                slot="sidebar"
                tag="sidebar"
                title="Mailboxes"
            >
                <adw-toolbar-view>
                    <adw-header-bar slot="top">
                        <adw-window-title
                            slot="title"
                            title="Mailboxes"
                        />
                    </adw-header-bar>
                    <adw-status-page
                        slot="content"
                        icon-name="mail-unread-symbolic"
                        title="Mailboxes"
                    />
                </adw-toolbar-view>
            </adw-navigation-page>
            <adw-navigation-page
                slot="content"
                tag="content"
                title="All Mail"
            >
                <adw-toolbar-view>
                    <adw-header-bar slot="top">
                        <adw-window-title
                            slot="title"
                            title="All Mail"
                        />
                    </adw-header-bar>
                    <adw-status-page
                        slot="content"
                        icon-name="mail-unread-symbolic"
                        title="All Mail"
                        description="Select a conversation from the list to read it here."
                    />
                </adw-toolbar-view>
            </adw-navigation-page>
        </adw-navigation-split-view>
        <adw-navigation-view>
            <adw-navigation-page
                tag="root"
                title="Contacts"
            >
                <adw-toolbar-view>
                    <adw-header-bar slot="top">
                        <adw-window-title
                            slot="title"
                            title="Contacts"
                        />
                    </adw-header-bar>
                    <adw-status-page
                        slot="content"
                        title="Contacts"
                        description="Push a page to see the transition."
                    />
                </adw-toolbar-view>
            </adw-navigation-page>
            <adw-navigation-page
                tag="detail"
                title="Ada Lovelace"
            >
                <adw-toolbar-view>
                    <adw-header-bar slot="top">
                        <adw-window-title
                            slot="title"
                            title="Ada Lovelace"
                        />
                    </adw-header-bar>
                    <adw-status-page
                        slot="content"
                        icon-name="avatar-default-symbolic"
                        title="Ada Lovelace"
                        description="Mathematician and writer, the first computer programmer."
                    />
                </adw-toolbar-view>
            </adw-navigation-page>
        </adw-navigation-view>
        <adw-avatar
            text="Ada Lovelace"
            :size="96"
            :show-initials="true"
            icon-name="avatar-default-symbolic"
        />
        <adw-banner
            title="Metered connection: updates paused"
            button-label="Resume"
            :revealed="true"
        />
        <adw-shortcut-label accelerator="<Control>C" />
        <adw-spinner
            :width-request="48"
            :height-request="48"
        />
        <adw-status-page
            icon-name="folder-symbolic"
            title="No Documents"
            description="Documents you create or open will appear here."
        >
            <gtk-button
                label="New Document"
                :css-classes="['pill', 'suggested-action']"
                halign="center"
            />
        </adw-status-page>
        <gtk-popover-menu :menu-model="[
                { label: 'New Window', accel: '<Control>N' },
                { section: [
                    { label: 'Cut' },
                    { label: 'Copy' },
                    { label: 'Paste' },
                ], label: 'Edit' },
                { label: 'Open With', submenu: [
                    { label: 'Text Editor' },
                    { label: 'Web Browser' },
                ] },
            ]" />
        <gtk-popover-menu-bar :menu-model="[
                { label: 'File', submenu: [
                    { label: 'New Window' },
                    { label: 'Open' },
                    { label: 'Quit' },
                ] },
                { label: 'Edit', submenu: [
                    { label: 'Undo' },
                    { label: 'Redo' },
                ] },
                { label: 'View', submenu: [
                    { label: 'Zoom In' },
                    { label: 'Zoom Out' },
                ] },
            ]" />
        <gtk-popover-bin
            :menu-model="[
                { label: 'Cut' },
                { label: 'Copy' },
                { label: 'Paste' },
                { label: 'Delete' },
            ]"
            :handle-input="true"
        />
        <adw-window-title
            title="Inbox"
            subtitle="3 unread messages"
        />
        <gtk-header-bar decoration-layout="menu:minimize,maximize,close">
            <gtk-button
                slot="start"
                label="Back"
                :css-classes="['flat']"
            />
            <gtk-label
                slot="title"
                label="Mailboxes"
            />
            <gtk-button
                slot="end"
                label="Search"
                :css-classes="['flat']"
            />
            <gtk-button
                slot="end"
                label="Menu"
                :css-classes="['flat']"
            />
        </gtk-header-bar>
        <gtk-window-controls
            side="end"
            decoration-layout="menu:minimize,maximize,close"
        />
    </gtk-box>
</template>
