<!-- GENERATED by scripts/generate-adwaita-framework-snippets.mjs — do not edit.

     Every gallery block that carries a Vue snippet, in ONE single-file component,
     compiled by `@gjsify/rolldown-plugin-vue` and asserted against the real GTK
     widget tree. The markup is the SAME TEXT the website ships. -->
<template>
    <gtk-box orientation="vertical" :spacing="24">
        <adw-preferences-group
            title="Account"
            description="Manage how this device signs in and syncs."
        >
            <adw-entry-row
                title="Display name"
                text="Grace Hopper"
            />
            <adw-switch-row
                title="Sync over Wi-Fi only"
                subtitle="Avoid using mobile data for backups"
                :active="true"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-action-row
                title="Wi-Fi"
                subtitle="Connected to Highgarden 5GHz"
                :activatable="true"
            >
                <gtk-image
                    slot="prefix"
                    icon-name="network-wireless-symbolic"
                />
                <gtk-button
                    slot="suffix"
                    icon-name="go-next-symbolic"
                    :css-classes="['flat']"
                    valign="center"
                />
            </adw-action-row>
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-switch-row
                title="Automatic updates"
                subtitle="Download and install updates without asking"
                :active="true"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-entry-row
                title="Display name"
                text="Ada Lovelace"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-password-entry-row
                title="Password"
                text="correct-horse-battery"
            />
        </adw-preferences-group>
        <adw-preferences-group>
            <adw-button-row
                title="Add account"
                start-icon-name="list-add-symbolic"
                :css-classes="['suggested-action']"
            />
        </adw-preferences-group>
        <gtk-button :css-classes="['suggested-action', 'pill']">
            <adw-button-content
                label="Download"
                icon-name="folder-download-symbolic"
            />
        </gtk-button>
        <gtk-box
            orientation="horizontal"
            :spacing="12"
            halign="center"
        >
            <gtk-button
                label="Pill"
                :css-classes="['pill']"
            />
            <gtk-button
                icon-name="list-add-symbolic"
                :css-classes="['circular']"
            />
            <gtk-button
                label="Suggested"
                :css-classes="['suggested-action']"
            />
            <gtk-button
                label="Delete"
                :css-classes="['destructive-action']"
            />
            <gtk-button
                label="Flat"
                :css-classes="['flat']"
            />
        </gtk-box>
        <gtk-entry
            placeholder-text="Search files…"
            :width-request="280"
        />
        <adw-clamp
            :maximum-size="400"
            :tightening-threshold="300"
        >
            <gtk-label
                label="This content is clamped: it stops growing past the maximum size and stays centred."
                :wrap="true"
                :xalign="0"
                :css-classes="['card']"
            />
        </adw-clamp>
        <adw-header-bar>
            <gtk-button
                slot="start"
                icon-name="go-previous-symbolic"
                :css-classes="['flat']"
            />
            <adw-window-title
                slot="title"
                title="Text Editor"
                subtitle="notes.md"
            />
            <gtk-menu-button
                slot="end"
                icon-name="open-menu-symbolic"
                :css-classes="['flat']"
            />
        </adw-header-bar>
        <adw-toolbar-view>
            <adw-header-bar slot="top">
                <adw-window-title
                    slot="title"
                    title="Documents"
                    subtitle="12 items"
                />
            </adw-header-bar>
            <adw-status-page
                slot="content"
                icon-name="folder-documents-symbolic"
                title="Your library"
                description="Content sits between the toolbars and scrolls independently of them."
            />
            <gtk-box
                slot="bottom"
                :css-classes="['toolbar']"
                :spacing="6"
            >
                <gtk-button
                    icon-name="list-add-symbolic"
                    :css-classes="['flat']"
                />
                <gtk-button
                    icon-name="list-remove-symbolic"
                    :css-classes="['flat']"
                />
                <gtk-label
                    label="Selection: none"
                    :hexpand="true"
                />
                <gtk-button
                    icon-name="send-to-symbolic"
                    :css-classes="['flat']"
                />
            </gtk-box>
        </adw-toolbar-view>
        <adw-wrap-box
            :child-spacing="8"
            :line-spacing="8"
        >
            <gtk-button
                label="Design"
                :css-classes="['pill']"
            />
            <gtk-button
                label="Adwaita"
                :css-classes="['pill']"
            />
            <gtk-button
                label="GNOME"
                :css-classes="['pill']"
            />
            <gtk-button
                label="GTK"
                :css-classes="['pill']"
            />
            <gtk-button
                label="Typescript"
                :css-classes="['pill']"
            />
            <gtk-button
                label="Storybook"
                :css-classes="['pill']"
            />
            <gtk-button
                label="Wrapping"
                :css-classes="['pill']"
            />
            <gtk-button
                label="Layout"
                :css-classes="['pill']"
            />
        </adw-wrap-box>
        <adw-overlay-split-view :show-sidebar="true">
            <adw-toolbar-view slot="sidebar">
                <adw-header-bar slot="top">
                    <adw-window-title
                        slot="title"
                        title="Library"
                    />
                </adw-header-bar>
                <adw-status-page
                    slot="content"
                    icon-name="folder-music-symbolic"
                    title="Sections"
                />
            </adw-toolbar-view>
            <adw-toolbar-view slot="content">
                <adw-header-bar slot="top">
                    <adw-window-title
                        slot="title"
                        title="Your Library"
                    />
                </adw-header-bar>
                <adw-status-page
                    slot="content"
                    icon-name="folder-music-symbolic"
                    title="Your Library"
                    description="Toggle the sidebar to browse sections."
                />
            </adw-toolbar-view>
        </adw-overlay-split-view>
        <adw-navigation-split-view :show-content="true">
            <adw-navigation-page
                slot="sidebar"
                tag="sidebar"
                title="Mailboxes"
            >
                <adw-toolbar-view>
                    <adw-header-bar slot="top">
                        <adw-window-title
                            slot="title"
                            title="Mailboxes"
                        />
                    </adw-header-bar>
                    <adw-status-page
                        slot="content"
                        icon-name="mail-unread-symbolic"
                        title="Mailboxes"
                    />
                </adw-toolbar-view>
            </adw-navigation-page>
            <adw-navigation-page
                slot="content"
                tag="content"
                title="All Mail"
            >
                <adw-toolbar-view>
                    <adw-header-bar slot="top">
                        <adw-window-title
                            slot="title"
                            title="All Mail"
                        />
                    </adw-header-bar>
                    <adw-status-page
                        slot="content"
                        icon-name="mail-unread-symbolic"
                        title="All Mail"
                        description="Select a conversation from the list to read it here."
                    />
                </adw-toolbar-view>
            </adw-navigation-page>
        </adw-navigation-split-view>
        <adw-navigation-view>
            <adw-navigation-page
                tag="root"
                title="Contacts"
            >
                <adw-toolbar-view>
                    <adw-header-bar slot="top">
                        <adw-window-title
                            slot="title"
                            title="Contacts"
                        />
                    </adw-header-bar>
                    <adw-status-page
                        slot="content"
                        title="Contacts"
                        description="Push a page to see the transition."
                    />
                </adw-toolbar-view>
            </adw-navigation-page>
            <adw-navigation-page
                tag="detail"
                title="Ada Lovelace"
            >
                <adw-toolbar-view>
                    <adw-header-bar slot="top">
                        <adw-window-title
                            slot="title"
                            title="Ada Lovelace"
                        />
                    </adw-header-bar>
                    <adw-status-page
                        slot="content"
                        icon-name="avatar-default-symbolic"
                        title="Ada Lovelace"
                        description="Mathematician and writer, the first computer programmer."
                    />
                </adw-toolbar-view>
            </adw-navigation-page>
        </adw-navigation-view>
        <adw-avatar
            text="Ada Lovelace"
            :size="96"
            :show-initials="true"
            icon-name="avatar-default-symbolic"
        />
        <adw-banner
            title="Metered connection: updates paused"
            button-label="Resume"
            :revealed="true"
        />
        <adw-shortcut-label accelerator="<Control>C" />
        <adw-spinner
            :width-request="48"
            :height-request="48"
        />
        <adw-status-page
            icon-name="folder-symbolic"
            title="No Documents"
            description="Documents you create or open will appear here."
        >
            <gtk-button
                label="New Document"
                :css-classes="['pill', 'suggested-action']"
                halign="center"
            />
        </adw-status-page>
        <adw-window-title
            title="Inbox"
            subtitle="3 unread messages"
        />
    </gtk-box>
</template>
