// AUTO-GENERATED by scripts/generate-adwaita-tokens.mjs. DO NOT EDIT BY HAND.
//
// Source: packages/web/adwaita-web/scss/_variables.scss (`light-theme`) and
// _theme.scss (`dark-theme`). ADR 0010 decision 2: these custom properties ARE
// the public theming contract of `@gjsify/adwaita-web`.

export interface AdwToken {
    /** The custom property, e.g. `--accent-bg-color`. */
    name: string;
    /** Its light-mode default. Dark mode re-declares the same names. */
    value: string;
}

export interface AdwTokenGroup {
    title: string;
    tokens: AdwToken[];
}

export const ADWAITA_TOKEN_GROUPS: AdwTokenGroup[] = [
    {
        title: 'Window',
        tokens: [
            {
                name: '--window-bg-color',
                value: '#fafafb',
            },
            {
                name: '--window-fg-color',
                value: 'rgba(0, 0, 6, 0.8)',
            },
        ],
    },
    {
        title: 'Views',
        tokens: [
            {
                name: '--view-bg-color',
                value: '#ffffff',
            },
            {
                name: '--view-fg-color',
                value: 'rgba(0, 0, 6, 0.8)',
            },
        ],
    },
    {
        title: 'Header bar',
        tokens: [
            {
                name: '--headerbar-bg-color',
                value: '#ffffff',
            },
            {
                name: '--headerbar-fg-color',
                value: 'rgba(0, 0, 6, 0.8)',
            },
            {
                name: '--headerbar-shade-color',
                value: 'rgba(0, 0, 6, 0.12)',
            },
        ],
    },
    {
        title: 'Hairline separators (header underline, sidebar/pane dividers)',
        tokens: [
            {
                name: '--separator-color',
                value: 'rgba(0, 0, 6, 0.1)',
            },
        ],
    },
    {
        title: 'The GENERIC shade the whole `*-shade-color` family below specialises (`_colors.scss:79,141`)',
        tokens: [
            {
                name: '--shade-color',
                value: 'rgba(0, 0, 6, 0.07)',
            },
        ],
    },
    {
        title: 'Sidebar / split panes',
        tokens: [
            {
                name: '--sidebar-bg-color',
                value: '#ebebed',
            },
            {
                name: '--sidebar-fg-color',
                value: 'rgba(0, 0, 6, 0.8)',
            },
            {
                name: '--sidebar-backdrop-color',
                value: '#f2f2f4',
            },
            {
                name: '--sidebar-shade-color',
                value: 'rgba(0, 0, 6, 0.07)',
            },
            {
                name: '--sidebar-border-color',
                value: 'rgba(0, 0, 6, 0.07)',
            },
        ],
    },
    {
        title: 'The MIDDLE pane of a three-pane setup',
        tokens: [
            {
                name: '--secondary-sidebar-bg-color',
                value: '#f3f3f5',
            },
            {
                name: '--secondary-sidebar-fg-color',
                value: 'rgba(0, 0, 6, 0.8)',
            },
            {
                name: '--secondary-sidebar-backdrop-color',
                value: '#f6f6fa',
            },
            {
                name: '--secondary-sidebar-shade-color',
                value: 'rgba(0, 0, 6, 0.07)',
            },
            {
                name: '--secondary-sidebar-border-color',
                value: 'rgba(0, 0, 6, 0.07)',
            },
        ],
    },
    {
        title: 'Cards / boxed lists',
        tokens: [
            {
                name: '--card-bg-color',
                value: '#ffffff',
            },
            {
                name: '--card-fg-color',
                value: 'rgba(0, 0, 6, 0.8)',
            },
            {
                name: '--card-shade-color',
                value: 'rgba(0, 0, 6, 0.07)',
            },
        ],
    },
    {
        title: 'Accent',
        tokens: [
            {
                name: '--accent-bg-color',
                value: '#3584e4',
            },
            {
                name: '--accent-fg-color',
                value: '#ffffff',
            },
            {
                name: '--accent-color',
                value: '#1c71d8',
            },
        ],
    },
    {
        title: 'Popover (menus, dropdowns) — an elevated surface above the window',
        tokens: [
            {
                name: '--popover-bg-color',
                value: '#ffffff',
            },
            {
                name: '--popover-fg-color',
                value: 'rgba(0, 0, 6, 0.8)',
            },
            {
                name: '--popover-shade-color',
                value: 'rgba(0, 0, 6, 0.07)',
            },
        ],
    },
    {
        title: 'Dialog scrim — the dimming wash behind a presented dialog (Adw dims with --shade-color at double alpha; this is the equivalent neutral wash)',
        tokens: [
            {
                name: '--dialog-scrim-color',
                value: 'rgba(0, 0, 6, 0.32)',
            },
        ],
    },
    {
        title: 'Buttons',
        tokens: [
            {
                name: '--button-bg-color',
                value: 'rgba(0, 0, 6, 0.08)',
            },
            {
                name: '--button-hover-color',
                value: 'rgba(0, 0, 6, 0.13)',
            },
            {
                name: '--button-active-color',
                value: 'rgba(0, 0, 6, 0.19)',
            },
        ],
    },
    {
        title: 'Entries',
        tokens: [
            {
                name: '--entry-bg-color',
                value: '#ffffff',
            },
            {
                name: '--entry-border-color',
                value: 'rgba(0, 0, 6, 0.18)',
            },
            {
                name: '--entry-border-hover-color',
                value: 'rgba(0, 0, 6, 0.28)',
            },
        ],
    },
    {
        title: 'Destructive action',
        tokens: [
            {
                name: '--destructive-bg-color',
                value: '#e01b24',
            },
            {
                name: '--destructive-fg-color',
                value: '#ffffff',
            },
        ],
    },
    {
        title: 'Semantic states',
        tokens: [
            {
                name: '--success-bg-color',
                value: '#2ec27e',
            },
            {
                name: '--success-fg-color',
                value: '#ffffff',
            },
            {
                name: '--success-color',
                value: 'oklab(from var(--success-bg-color) min(l, 0.5) a b)',
            },
            {
                name: '--warning-bg-color',
                value: '#e5a50a',
            },
            {
                name: '--warning-fg-color',
                value: 'rgba(0, 0, 0, 0.8)',
            },
            {
                name: '--warning-color',
                value: 'oklab(from var(--warning-bg-color) min(l, 0.5) a b)',
            },
            {
                name: '--error-bg-color',
                value: '#e01b24',
            },
            {
                name: '--error-fg-color',
                value: '#ffffff',
            },
            {
                name: '--error-color',
                value: 'oklab(from var(--error-bg-color) min(l, 0.5) a b)',
            },
        ],
    },
    {
        title: 'Switch',
        tokens: [
            {
                name: '--switch-off-bg',
                value: 'rgba(0, 0, 0, 0.2)',
            },
            {
                name: '--switch-knob-bg',
                value: '#ffffff',
            },
        ],
    },
    {
        title: 'Layout radii',
        tokens: [
            {
                name: '--window-radius',
                value: '15px',
            },
            {
                name: '--card-radius',
                value: '12px',
            },
            {
                name: '--button-radius',
                value: '9px',
            },
        ],
    },
    {
        title: 'Spacing scale',
        tokens: [
            {
                name: '--spacing-xs',
                value: '6px',
            },
            {
                name: '--spacing-s',
                value: '9px',
            },
            {
                name: '--spacing-m',
                value: '12px',
            },
            {
                name: '--spacing-l',
                value: '18px',
            },
            {
                name: '--spacing-xl',
                value: '24px',
            },
        ],
    },
    {
        title: 'Typography — GNOME default: Adwaita Sans 11',
        tokens: [
            {
                name: '--font-family',
                value: "'Adwaita Sans', 'Cantarell', 'Inter', 'Segoe UI', sans-serif",
            },
            {
                name: '--font-size-base',
                value: '11pt',
            },
            {
                name: '--font-size-small',
                value: '9pt',
            },
            {
                name: '--font-size-heading',
                value: '12pt',
            },
            {
                name: '--dim-opacity',
                value: '0.55',
            },
        ],
    },
    {
        title: "Borders and disabled dimming, as libadwaita's own two-step (_colors.scss:263, 317-329): an OPACITY token the high-contrast query moves, and a colour DERIVED from it against `currentColor` — so a border follows the text colour of the surface it is drawn on instead of being a fixed grey",
        tokens: [
            {
                name: '--border-opacity',
                value: '15%',
            },
            {
                name: '--border-color',
                value: 'color-mix(in srgb, currentColor var(--border-opacity), transparent)',
            },
            {
                name: '--disabled-opacity',
                value: '0.5',
            },
        ],
    },
    {
        title: 'Document + monospace families, behind `.document` / `.monospace` (_labels.scss:75-84)',
        tokens: [
            {
                name: '--document-font-family',
                value: 'var(--font-family)',
            },
            {
                name: '--document-font-size',
                value: 'var(--font-size-base)',
            },
            {
                name: '--monospace-font-family',
                value: "'Adwaita Mono', ui-monospace, 'SF Mono', 'Menlo', monospace",
            },
            {
                name: '--monospace-font-size',
                value: 'var(--font-size-base)',
            },
        ],
    },
];

/** How many tokens the contract carries — derived, never typed. */
export const ADWAITA_TOKEN_COUNT = 68;
