// AUTO-GENERATED by website/scripts/generate-coverage.mjs.
// DO NOT EDIT BY HAND — re-run `gjsify run generate-coverage` (or the build
// pre-step) to refresh.
//
// Source: `statusSummary()` in scripts/generate-status.mjs — the authored
// status data under status/ combined with facts derived from the package
// manifests. Each entry captures the Total / Full / Partial / Stub split for
// one category.

export interface PillarCoverage {
    /** Category label, as the status generator names it (verbatim). */
    category: string;
    /** Total surveyed entries in this pillar. */
    total: number;
    /** Fully implemented entries. */
    full: number;
    /** Partially implemented entries (core works; specific subsystems open). */
    partial: number;
    /** Stub-only entries (deprecated / browser-irrelevant / no-op). */
    stub: number;
}

export const pillarCoverage: readonly PillarCoverage[] = [
    {
        category: 'Node.js APIs',
        total: 41,
        full: 33,
        partial: 5,
        stub: 3,
    },
    {
        category: 'Node.js native bridges',
        total: 5,
        full: 5,
        partial: 0,
        stub: 0,
    },
    {
        category: 'Node.js meta',
        total: 2,
        full: 2,
        partial: 0,
        stub: 0,
    },
    {
        category: 'Web APIs',
        total: 19,
        full: 19,
        partial: 0,
        stub: 0,
    },
    {
        category: 'Web native bridges',
        total: 1,
        full: 1,
        partial: 0,
        stub: 0,
    },
    {
        category: 'Web meta',
        total: 1,
        full: 1,
        partial: 0,
        stub: 0,
    },
    {
        category: 'Browser UI / Adwaita',
        total: 5,
        full: 5,
        partial: 0,
        stub: 0,
    },
    {
        category: 'DOM',
        total: 2,
        full: 2,
        partial: 0,
        stub: 0,
    },
    {
        category: 'Framework',
        total: 17,
        full: 16,
        partial: 1,
        stub: 0,
    },
    {
        category: 'NativeScript bridges',
        total: 5,
        full: 5,
        partial: 0,
        stub: 0,
    },
    {
        category: 'GJS infrastructure',
        total: 3,
        full: 3,
        partial: 0,
        stub: 0,
    },
    {
        category: 'Build/Infra tools',
        total: 22,
        full: 17,
        partial: 5,
        stub: 0,
    },
    {
        category: 'Runtime engines',
        total: 5,
        full: 4,
        partial: 1,
        stub: 0,
    },
    {
        category: 'Showcases',
        total: 17,
        full: 17,
        partial: 0,
        stub: 0,
    },
    {
        category: 'Integration test suites',
        total: 36,
        full: 36,
        partial: 0,
        stub: 0,
    },
];

/** Pillars meaningful as a top-level coverage breakdown — meta + native-bridge
 *  rows are excluded (they aren't multi-entry "categories" that benefit from a
 *  bar). Keeps the visual hierarchy clean. */
export const overviewPillars: readonly PillarCoverage[] = pillarCoverage.filter(
    (p) => !/(meta|native bridges?)$/i.test(p.category),
);

/** Aggregate over the overview-tier pillars (all rendered in the bar grid). */
export function tallyOverview(): {
    total: number;
    full: number;
    partial: number;
    stub: number;
    implementedPct: number;
} {
    const acc = { total: 0, full: 0, partial: 0, stub: 0 };
    for (const p of overviewPillars) {
        acc.total += p.total;
        acc.full += p.full;
        acc.partial += p.partial;
        acc.stub += p.stub;
    }
    const implementedPct = acc.total === 0 ? 0 : Math.round(((acc.full + acc.partial) / acc.total) * 100);
    return { ...acc, implementedPct };
}
