// AUTO-GENERATED by website/scripts/generate-platform-matrix.mjs.
// DO NOT EDIT BY HAND — re-run `gjsify run generate:platform-matrix` (or the build
// pre-step) to refresh.
//
// Source: `platformRows()` + `platformMatrixData()` in
// scripts/manifest-conformance/rules/platforms-ci.mjs — the same functions behind
// `audit-runtimes.mjs --platforms` and the `--check` gate, so this page and the CI
// audit answer "where does this run?" from one rule.

/** One mark and what it asserts. */
export interface PlatformLegendEntry {
    mark: string;
    meaning: string;
}

/** One package's row: a mark per `<os>-<arch>` column. */
export interface PlatformMatrixRow {
    /** Published package name. */
    name: string;
    /** Stability tier (ADR 0003), or null where the package declares none. */
    tier: number | null;
    /** Column → mark. Every column in {@link platformColumns} is present. */
    cells: Readonly<Record<string, string>>;
}

/** The `<os>-<arch>` columns, sorted — the union of declared, built and committed. */
export const platformColumns: readonly string[] = [
    'darwin-arm64',
    'darwin-x64',
    'linux-arm64',
    'linux-ppc64',
    'linux-riscv64',
    'linux-s390x',
    'linux-x64',
    'win32-x64',
];

/** What each mark asserts. "A CI job targets it" is read out of the workflow YAML, so
 *  it claims exactly that — never that a green run of that job exists. */
export const platformLegend: readonly PlatformLegendEntry[] = [
    { mark: '✓', meaning: 'declared, a CI job targets it, artifact committed' },
    { mark: '○', meaning: 'declared, a CI job targets it, artifact NOT committed here' },
    { mark: '⚠', meaning: 'committed artifact, no CI job targets it' },
    { mark: '!', meaning: 'declared, no CI job targets it' },
    { mark: '?', meaning: 'produced, undeclared' },
    { mark: '·', meaning: 'unsupported' },
];

/** One row per native bridge — the packages that ship a compiled artifact. */
export const platformMatrix: readonly PlatformMatrixRow[] = [
    {
        name: '@gjsify/http-soup-bridge',
        tier: 1,
        cells: {
            'darwin-arm64': '✓',
            'darwin-x64': '✓',
            'linux-arm64': '✓',
            'linux-ppc64': '✓',
            'linux-riscv64': '✓',
            'linux-s390x': '✓',
            'linux-x64': '✓',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/http2-native',
        tier: 1,
        cells: {
            'darwin-arm64': '✓',
            'darwin-x64': '✓',
            'linux-arm64': '✓',
            'linux-ppc64': '✓',
            'linux-riscv64': '✓',
            'linux-s390x': '✓',
            'linux-x64': '✓',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/lightningcss-native',
        tier: 1,
        cells: {
            'darwin-arm64': '✓',
            'darwin-x64': '✓',
            'linux-arm64': '✓',
            'linux-ppc64': '✓',
            'linux-riscv64': '✓',
            'linux-s390x': '✓',
            'linux-x64': '✓',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/napi',
        tier: 3,
        cells: {
            'darwin-arm64': '○',
            'darwin-x64': '·',
            'linux-arm64': '·',
            'linux-ppc64': '·',
            'linux-riscv64': '·',
            'linux-s390x': '·',
            'linux-x64': '○',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/node-gi',
        tier: 2,
        cells: {
            'darwin-arm64': '○',
            'darwin-x64': '○',
            'linux-arm64': '○',
            'linux-ppc64': '·',
            'linux-riscv64': '·',
            'linux-s390x': '·',
            'linux-x64': '✓',
            'win32-x64': '○',
        },
    },
    {
        name: '@gjsify/oxfmt-native',
        tier: 1,
        cells: {
            'darwin-arm64': '✓',
            'darwin-x64': '✓',
            'linux-arm64': '✓',
            'linux-ppc64': '·',
            'linux-riscv64': '·',
            'linux-s390x': '·',
            'linux-x64': '✓',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/rolldown-native',
        tier: 1,
        cells: {
            'darwin-arm64': '✓',
            'darwin-x64': '✓',
            'linux-arm64': '✓',
            'linux-ppc64': '·',
            'linux-riscv64': '·',
            'linux-s390x': '·',
            'linux-x64': '✓',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/sab-native',
        tier: 1,
        cells: {
            'darwin-arm64': '·',
            'darwin-x64': '·',
            'linux-arm64': '✓',
            'linux-ppc64': '✓',
            'linux-riscv64': '✓',
            'linux-s390x': '✓',
            'linux-x64': '✓',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/terminal-native',
        tier: 1,
        cells: {
            'darwin-arm64': '✓',
            'darwin-x64': '✓',
            'linux-arm64': '✓',
            'linux-ppc64': '✓',
            'linux-riscv64': '✓',
            'linux-s390x': '✓',
            'linux-x64': '✓',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/tls-native',
        tier: 1,
        cells: {
            'darwin-arm64': '✓',
            'darwin-x64': '✓',
            'linux-arm64': '✓',
            'linux-ppc64': '✓',
            'linux-riscv64': '✓',
            'linux-s390x': '✓',
            'linux-x64': '✓',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/webgl',
        tier: 1,
        cells: {
            'darwin-arm64': '✓',
            'darwin-x64': '✓',
            'linux-arm64': '✓',
            'linux-ppc64': '✓',
            'linux-riscv64': '✓',
            'linux-s390x': '✓',
            'linux-x64': '✓',
            'win32-x64': '✓',
        },
    },
    {
        name: '@gjsify/webkit-native',
        tier: 1,
        cells: {
            'darwin-arm64': '✓',
            'darwin-x64': '✓',
            'linux-arm64': '·',
            'linux-ppc64': '·',
            'linux-riscv64': '·',
            'linux-s390x': '·',
            'linux-x64': '·',
            'win32-x64': '·',
        },
    },
    {
        name: '@gjsify/webrtc-native',
        tier: 1,
        cells: {
            'darwin-arm64': '·',
            'darwin-x64': '·',
            'linux-arm64': '✓',
            'linux-ppc64': '✓',
            'linux-riscv64': '✓',
            'linux-s390x': '✓',
            'linux-x64': '✓',
            'win32-x64': '·',
        },
    },
];
