// SPDX-License-Identifier: MIT
// @gjsify/napi — loud stubs for the not-yet-implemented Node-API surface.
//
// GENERATED by scripts/gen-stubs.py (checked in; regenerate after
// implementing a new ABI function — a newly implemented function that stays
// listed here fails the link with a duplicate-symbol error, the guard).
//
// Every declared `napi_*`/`node_api_*` symbol of the vendored headers
// (NAPI_VERSION=10, non-experimental) is DEFINED and exported, so an addon's
// undefined symbols always bind at dlopen (RTLD_NOW) — reaching past the
// implemented surface fails loud with napi_generic_failure + last_error
// (plan section 2 posture), never with an unresolved-symbol load failure and
// never with a crash. 28 stubs.

#include "common.h"

// env may be napi_env or node_api_basic_env — identical underlying type in
// the non-experimental configuration (js_native_api_types.h:74-81).
#define GJSIFY_NAPI_STUB(env)                                                 \
    do {                                                                      \
        GJSIFY_NAPI_CHECK_ENV(env);                                           \
        return gjsify_napi::set_last_error(                                   \
            const_cast<napi_env>(env), napi_generic_failure);                 \
    } while (0)

napi_status NAPI_CDECL node_api_create_external_string_latin1(napi_env env, char* str, size_t length, node_api_basic_finalize finalize_callback, void* finalize_hint, napi_value* result, bool* copied) {
    (void)str;
    (void)length;
    (void)finalize_callback;
    (void)finalize_hint;
    (void)result;
    (void)copied;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL node_api_create_external_string_utf16(napi_env env, char16_t* str, size_t length, node_api_basic_finalize finalize_callback, void* finalize_hint, napi_value* result, bool* copied) {
    (void)str;
    (void)length;
    (void)finalize_callback;
    (void)finalize_hint;
    (void)result;
    (void)copied;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL node_api_symbol_for(napi_env env, const char* utf8description, size_t length, napi_value* result) {
    (void)utf8description;
    (void)length;
    (void)result;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_create_external_arraybuffer(napi_env env, void* external_data, size_t byte_length, node_api_basic_finalize finalize_cb, void* finalize_hint, napi_value* result) {
    (void)external_data;
    (void)byte_length;
    (void)finalize_cb;
    (void)finalize_hint;
    (void)result;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_adjust_external_memory(node_api_basic_env env, int64_t change_in_bytes, int64_t* adjusted_value) {
    (void)change_in_bytes;
    (void)adjusted_value;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_create_bigint_words(napi_env env, int sign_bit, size_t word_count, const uint64_t* words, napi_value* result) {
    (void)sign_bit;
    (void)word_count;
    (void)words;
    (void)result;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_get_value_bigint_words(napi_env env, napi_value value, int* sign_bit, size_t* word_count, uint64_t* words) {
    (void)value;
    (void)sign_bit;
    (void)word_count;
    (void)words;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_async_init(napi_env env, napi_value async_resource, napi_value async_resource_name, napi_async_context* result) {
    (void)async_resource;
    (void)async_resource_name;
    (void)result;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_async_destroy(napi_env env, napi_async_context async_context) {
    (void)async_context;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_make_callback(napi_env env, napi_async_context async_context, napi_value recv, napi_value func, size_t argc, const napi_value* argv, napi_value* result) {
    (void)async_context;
    (void)recv;
    (void)func;
    (void)argc;
    (void)argv;
    (void)result;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL node_api_create_buffer_from_arraybuffer(napi_env env, napi_value arraybuffer, size_t byte_offset, size_t byte_length, napi_value* result) {
    (void)arraybuffer;
    (void)byte_offset;
    (void)byte_length;
    (void)result;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_create_async_work(napi_env env, napi_value async_resource, napi_value async_resource_name, napi_async_execute_callback execute, napi_async_complete_callback complete, void* data, napi_async_work* result) {
    (void)async_resource;
    (void)async_resource_name;
    (void)execute;
    (void)complete;
    (void)data;
    (void)result;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_delete_async_work(napi_env env, napi_async_work work) {
    (void)work;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_queue_async_work(node_api_basic_env env, napi_async_work work) {
    (void)work;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_cancel_async_work(node_api_basic_env env, napi_async_work work) {
    (void)work;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_get_node_version(node_api_basic_env env, const napi_node_version** version) {
    (void)version;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_get_uv_event_loop(node_api_basic_env env, struct uv_loop_s** loop) {
    (void)loop;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_open_callback_scope(napi_env env, napi_value resource_object, napi_async_context context, napi_callback_scope* result) {
    (void)resource_object;
    (void)context;
    (void)result;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_close_callback_scope(napi_env env, napi_callback_scope scope) {
    (void)scope;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_create_threadsafe_function(napi_env env, napi_value func, napi_value async_resource, napi_value async_resource_name, size_t max_queue_size, size_t initial_thread_count, void* thread_finalize_data, napi_finalize thread_finalize_cb, void* context, napi_threadsafe_function_call_js call_js_cb, napi_threadsafe_function* result) {
    (void)func;
    (void)async_resource;
    (void)async_resource_name;
    (void)max_queue_size;
    (void)initial_thread_count;
    (void)thread_finalize_data;
    (void)thread_finalize_cb;
    (void)context;
    (void)call_js_cb;
    (void)result;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_get_threadsafe_function_context(napi_threadsafe_function func, void** result) {
    (void)func;
    (void)result;
    return napi_generic_failure;
}

napi_status NAPI_CDECL napi_call_threadsafe_function(napi_threadsafe_function func, void* data, napi_threadsafe_function_call_mode is_blocking) {
    (void)func;
    (void)data;
    (void)is_blocking;
    return napi_generic_failure;
}

napi_status NAPI_CDECL napi_acquire_threadsafe_function(napi_threadsafe_function func) {
    (void)func;
    return napi_generic_failure;
}

napi_status NAPI_CDECL napi_release_threadsafe_function(napi_threadsafe_function func, napi_threadsafe_function_release_mode mode) {
    (void)func;
    (void)mode;
    return napi_generic_failure;
}

napi_status NAPI_CDECL napi_unref_threadsafe_function(node_api_basic_env env, napi_threadsafe_function func) {
    (void)func;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_ref_threadsafe_function(node_api_basic_env env, napi_threadsafe_function func) {
    (void)func;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_add_async_cleanup_hook(node_api_basic_env env, napi_async_cleanup_hook hook, void* arg, napi_async_cleanup_hook_handle* remove_handle) {
    (void)hook;
    (void)arg;
    (void)remove_handle;
    GJSIFY_NAPI_STUB(env);
}

napi_status NAPI_CDECL napi_remove_async_cleanup_hook(napi_async_cleanup_hook_handle remove_handle) {
    (void)remove_handle;
    return napi_generic_failure;
}
